### ISSUE TITLE
How about client_secret?

### ISSUE THREAD

**Issue by alex-v-ivanov** [MicrosoftDocs/powerquery-docs#10]
As I understand OAuth 2.0 standard flow, when we call the exchange function (TokenMethod in the example above) we must pass a client_secret as header. But it's unsafe if I want to share my connector with other people. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6f55e2-dc4a-c0ac-296b-c41d02bea7f5
* Version Independent ID: 767b1dbc-dd20-f5cd-7afa-bdd17458c233
* Content: [Microsoft Graph tutorial for Power Query](https://docs.microsoft.com/en-us/power-query/samples/mygraph/readme)
* Content Source: [powerquery-docs/samples/MyGraph/README.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/samples/MyGraph/README.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by qsnsjd** [comment]
client secret would only be used in case you dont want to delegate the calls

**Comment by mattmasson** [comment]
You can find out more about when you need to provide a client_secret value here: [https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-applications](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-applications)

**Comment by alex-v-ivanov** [comment]
I sorted it out by myself, thanks.
