### ISSUE TITLE
Can't find the Export Template option

### ISSUE THREAD

**Issue by p2gdeveloper** [MicrosoftDocs/powerquery-docs#101]
Re Step 2 of the section on exporting queries as templates, I cannot find the Export Template menu item in my Power Query Editor. Is there some sort of pre-requisite for this to appear or has the option been removed in recent updates? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83598a18-19b8-819f-ec6c-df970303c7ae
* Version Independent ID: 0827113c-e8e8-aba7-81cf-c574f83e613a
* Content: [Create Power Platform dataflows from queries in Microsoft Excel (Preview)](https://docs.microsoft.com/en-us/power-query/new-dataflow-from-template)
* Content Source: [powerquery-docs/new-dataflow-from-template.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/new-dataflow-from-template.md)
* Service: **powerquery**
* GitHub Login: @JorgeGabuardiMS
* Microsoft Alias: **jogabuar**

**Comment by DougKlopfenstein** [comment]
Hi @p2gdeveloper -
Are you a member of Office Insider? If not, the article [Create Power Platform dataflows from queries in Microsoft Excel (Preview)](https://docs.microsoft.com/power-query/new-dataflow-from-template) contains a link to the Office Insider program.

If this doesn't solve your problem, see [Power Query feedback](https://docs.microsoft.com/power-query/feedback) for places that will provide Power Query support.
