### ISSUE TITLE
Seems to be broken with Standard V2 dataflows

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/powerquery-docs#104]
Ever since the update to V2 dataflows im running into an issue when using related tables. 

**The error.** 
```
XXX,efec02bb-7ae2-4ab4-be36-a46c07eb0eed,"https:/XXX.crm4.dynamics.com\XXX",Microsoft.Mashup.Web.CdsUploaderService.Exceptions.JobAbortException:   There was a problem obtaining table XXXColumn   XXX.XXX information from Dataverse. Please verify that   column exist on Dataverse.
```

same issue as seen here. 
https://powerusers.microsoft.com/t5/Microsoft-Dataverse/Column-not-found-when-refreshing-dataflow-from-web-services-but/td-p/772438

It seems it cant find the specified key.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58177c4d-47bd-1c43-8bd5-c8781fc32244
* Version Independent ID: 8065fad5-3ec1-1257-c8a5-8a8a159c5915
* Content: [Mapping fields with relationships in standard dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/relationships-in-standard-dataflows)
* Content Source: [powerquery-docs/dataflows/relationships-in-standard-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/dataflows/relationships-in-standard-dataflows.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @Ballzer0 -

This appears to be a customer support issue rather than a documentation issue. For information about customer support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback).
