### ISSUE TITLE
How would you pass file specific information to a custom function (or anywhere else for that matter).

### ISSUE THREAD

**Issue by dwainew** [MicrosoftDocs/powerquery-docs#106]
I'm new to Power BI and am regretting not diving in earlier.  This was an amazingly informative article and I appreciate the quality content and delivery.

However, there seems to be an "elephant in the room" regarding the methodology of folder processing in power BI.  I'm hoping you can show me it's not really there.  How would you pass context specific attributes to a function?  File name is one very important example, not to mention size, date, etc.!  When processing files, file name is most often the only attribute you have to identify the source of the data and adjust downflow logic accordingly.  The methodology presented here results in the file content being presented to a function in a parameter, but all of the file specific metadata is unavailable down-stream.  

I've run into the same problem trying to use linked queries.  When creating a linked query from the converted table column you have provided, the key being used by the referencing query is the row ID!  This doesn't work because if you are modeling the query based on the expected filename, that row ID will change later if another file comes in at a later time, changing the row IDs!

I hope I'm just missing something basic due to my current knowledge level and would appreciate any information you can provide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adfb26bf-e0e4-fa66-409e-646c0b5ec2c6
* Version Independent ID: be67d882-0168-ea43-24aa-a3265552d983
* Content: [Using cCustom functions](https://docs.microsoft.com/en-us/power-query/custom-function?source=docs)
* Content Source: [powerquery-docs/custom-function.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/custom-function.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **v-miesco**

**Comment by ptyx507** [comment]
Hey!
The goal of this article is to provide a more thorough methodology to create a custom function and how a custom function works.
However, for combining files, I highly recommend that you check out these 2 other articles that go into the combine files experience in Power Query:

https://docs.microsoft.com/en-us/power-query/combine-files-overview

https://docs.microsoft.com/en-us/power-query/combine-files-csv

with the combine files experience your main query will end up with a “remove other columns” step that you can double click to select which attributes of the file you’d like to keep downstream.

For the situation with the navigation / drill down to the contents of a single column or cell, what I suggest is that you remove all columns from your query except the “Content” and “Name”. This will force Power Query to use the value from the “Name” column as a reference for the navigation. However, this concept is outside of the scope of this article so if you need further help with this we do have a community forum for Power BI:
https://community.powerbi.com/

As an alternative, there’s also this other community forum specific to Power Query questions:
https://docs.microsoft.com/en-us/answers/products/pwrqry

Hope this helps!
