### ISSUE TITLE
Language Specification - 12.1.6 Generalized Identifier - not wired in

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#11]
Hello,

In the [Power Query Language Specification](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#identifiers), the non-terminal `generalized-identifier` is defined in section 12.1.6. However, `generalized-identifier` is not used anywhere in the larger section 12.1—there is no path from section 12.1’s root element (`lexical-unit`) to this identifier.  

I believe this rule needs to be wired in somewhere, likely as an option under 12.1.6’s `identifier` non-terminal. However, since `generalized-identifier` can only be used in certain contexts (per section 2.6.3.1), it can’t simply be added as an alternative option under `identifier`; instead, some qualifier rule needs to be added in conjunction with it. 

Would you be able to provide the correct grammar logic/rules for wiring `generalized-identifier` in so that it can be tied back to `lexical-unit`? This would help with an interoperability project I'm working on.

Thank you,
Ben

(Microsoft Doc Helps case reference # 120033121002184f)

**Comment by CurtHagenlocher** [comment]
generalized-identifier and related elements probably belong under Syntactic Grammar instead of Lexical Grammar. I suspect they are in their current location just so that all the identifier-related elements are in one place. At the end of the day, the distinction between "syntactic" and "lexical" is as much about a choice of parsing implementation technology as it is about the language definition. So while we'll keep this in mind the next time we make larger-scale changes to the document, I don't think it's something we would change just now without a more-compelling reason.

**Comment by bgribaudo** [comment]
Hi @CurtHagenlocher!

Thanks for taking the time to look at this. 

> generalized-identifier and related elements probably belong under Syntactic Grammar instead of Lexical Grammar. I suspect they are in their current location just so that all the identifier-related elements are in one place. 

I'm having trouble figuring out how this would work. :-( 

Based on the way the grammar rules are currently written, the following Power Query is invalid because it does not match the 12.1 `lexical-unit` rule (however, Excel accepts it as valid): 
````
[ 2020Amount = 1 ]
````

`lexical-unit` says it is made up of an optional set of `lexical-items`, which in turn each can be whitespace, comments or tokens. A token can be an keyword, literal, operator/punctuator or identifier. An identifier, in turn can be either a `regular-identifier` or a `quoted-identifier`--and there's our problem. :-) "2020Amount" is neither. It's a `generalized-identifier`--but that's not valid here according to the rules given (regardless of whether `generalized-identifier` and related components are left here or moved down into the syntactic grammar). 

How do we get the above example to Power Query to pass 12.1's `lexical-unit` rule?

**Comment by CurtHagenlocher** [comment]
Here are the lexical-items which your example breaks down into:

operator-or-punctuator("[")
whitespace(" ")
number-literal("2020")
text-literal("Amount")
whitespace(" ")
operator-or-punctuator("=")
whitespace(" ")
number-literal("1")
whitespace(" ")
operator-or-punctuator("]")

The collapse of the lexical-items between the "[" and the "=" into a generalized-identifier happens in the parser. 

Have you seen the open source M parser at https://github.com/microsoft/powerquery-parser ?

**Comment by bgribaudo** [comment]
Thanks for your patience with me on this, @CurtHagenlocher! When I wrote my last reply, I forgot that it wasn't necessary for spaces to be present between different tokens. :-/

I do like the idea of maybe eventually moving `generalized-identifier` and components into the syntactic grammar at some point down the road, for clarity's sake.
