### ISSUE TITLE
[LOC]Back-Translation "電源プラットフォーム"→"Power Platform" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerquery-docs#111]
ja-jp:"https://docs.microsoft.com/ja-jp/power-query/dataflows/overview-dataflows-across-power-platform-dynamics-365"
![overview-dataflows-across-power-platform-dynamics-365_j](https://user-images.githubusercontent.com/40815708/114298330-c56cc300-9af0-11eb-868a-0c95512bb0f9.png)

en-us:"https://docs.microsoft.com/en-us/power-query/dataflows/overview-dataflows-across-power-platform-dynamics-365"
![overview-dataflows-across-power-platform-dynamics-365_e](https://user-images.githubusercontent.com/40815708/114298335-ca317700-9af0-11eb-9eb0-d30e8b4a4bc7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2653ddba-9221-f7b0-1437-9c7602cc0ade
* Version Independent ID: 52479bdb-4832-07d8-1610-f43f8b2e4f3a
* Content: [An overview of dataflows across Microsoft Power Platform and Dynamics 365 products](https://docs.microsoft.com/en-us/power-query/dataflows/overview-dataflows-across-power-platform-dynamics-365)
* Content Source: [powerquery-docs/dataflows/overview-dataflows-across-power-platform-dynamics-365.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/overview-dataflows-across-power-platform-dynamics-365.md)
* Service: **powerquery**
* GitHub Login: @radacad
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @hyoshioka0128 
 Thank you for your feedback. This is now under review and no further action is required at this time.
