### ISSUE TITLE
[LOC]Back-Translation "電源プラットフォーム"→"Power Platform" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerquery-docs#112]
ja-jp:"https://docs.microsoft.com/ja-jp/power-query/dataflows/create-use"
![reate-use_j](https://user-images.githubusercontent.com/40815708/114298559-f00b4b80-9af1-11eb-8223-8c3f2a761ecd.png)

en-us:"https://docs.microsoft.com/en-us/power-query/dataflows/create-use"
![reate-use_e](https://user-images.githubusercontent.com/40815708/114298563-f4376900-9af1-11eb-8f12-70fa9159485a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a367fd4-1f8d-e001-7a4e-29589b6b5d70
* Version Independent ID: ecb282ea-72c4-0a41-a520-48d014f9d4a0
* Content: [Create and use dataflows in Microsoft Power Platform](https://docs.microsoft.com/en-us/power-query/dataflows/create-use)
* Content Source: [powerquery-docs/dataflows/create-use.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/create-use.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @hyoshioka0128 
 Thank you for your feedback. This is now under review and no further action is required at this time.
