### ISSUE TITLE
[LOC]Back-Translation "Power オートメーション"→"Power Automate" (ja-jp) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerquery-docs#113]
ja-jp:"https://docs.microsoft.com/ja-jp/power-query/dataflows/dataflow-power-automate-connector-templates"
![dataflow-power-automate-connector-templates_j](https://user-images.githubusercontent.com/40815708/114369088-ffa19780-9bb8-11eb-9c79-9a88f0a9bec0.png)

en-us:"https://docs.microsoft.com/en-us/power-query/dataflows/dataflow-power-automate-connector-templates"
![dataflow-power-automate-connector-templates_e](https://user-images.githubusercontent.com/40815708/114369095-016b5b00-9bb9-11eb-9112-7b45cfe3c76d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 522d587b-b495-5053-9d37-7f659d5fd16e
* Version Independent ID: 9ac1dd26-627f-23d7-cde1-7bbe6f1ae6b5
* Content: [Power Automate Templates for the Dataflows Connector](https://docs.microsoft.com/en-us/power-query/dataflows/dataflow-power-automate-connector-templates)
* Content Source: [powerquery-docs/dataflows/dataflow-power-automate-connector-templates.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/dataflow-power-automate-connector-templates.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @hyoshioka0128 
 Thank you for your feedback. This is now under review and no further action is required at this time.
