### ISSUE TITLE
Data migration from legacy systems scenario is duplicated

### ISSUE THREAD

**Issue by hugobarona** [MicrosoftDocs/powerquery-docs#114]
Hi there,

I was reviewing this page for examples of scenarios for Data Flows and noticed that the scenario _Data migration from legacy systems_ is duplicated.

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2653ddba-9221-f7b0-1437-9c7602cc0ade
* Version Independent ID: 52479bdb-4832-07d8-1610-f43f8b2e4f3a
* Content: [An overview of dataflows across Microsoft Power Platform and Dynamics 365 products](https://docs.microsoft.com/en-us/power-query/dataflows/overview-dataflows-across-power-platform-dynamics-365)
* Content Source: [powerquery-docs/dataflows/overview-dataflows-across-power-platform-dynamics-365.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/overview-dataflows-across-power-platform-dynamics-365.md)
* Service: **powerquery**
* GitHub Login: @radacad
* Microsoft Alias: **gepopell**

**Comment by MattRudy** [comment]
Hi Hugo, good catch! I'll submit a change that removes the duplicates.
