### ISSUE TITLE
Incorrect Instructions for Address being used

### ISSUE THREAD

**Issue by Laura-GB** [MicrosoftDocs/powerquery-docs#116]
The article states using the whole address for the environment. This will return an error. You need to strip the https:// and / from the address.

Regards

Laura GB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e182c32-ef1e-2092-9e8f-0643f991c17a
* Version Independent ID: 11d6812e-4d94-9024-72ad-a8ae7aa429a6
* Content: [Power Query Dataverse connector](https://docs.microsoft.com/en-us/power-query/connectors/dataverse#feedback)
* Content Source: [powerquery-docs/Connectors/Dataverse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Dataverse.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @Laura-GB -
Thanks for your feedback. This issue has been fixed.
