### ISSUE TITLE
[LOC]Back-Translation " 電源自動化"→"Power Automate" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerquery-docs#117]
ja-jp:"https://docs.microsoft.com/ja-jp/power-query/dataflows/load-dataflow-metadata-into-excel-online"
![load-dataflow-metadata-into-excel-online_j](https://user-images.githubusercontent.com/40815708/114844582-e77a8400-9e15-11eb-9f28-13817fe1274a.png)

en-us:"https://docs.microsoft.com/en-us/power-query/dataflows/load-dataflow-metadata-into-excel-online"
![load-dataflow-metadata-into-excel-online_e](https://user-images.githubusercontent.com/40815708/114844607-eba6a180-9e15-11eb-91d9-69eebaa74633.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54afa86a-fff2-8de0-6b52-d7a7de7af223
* Version Independent ID: 3d6cb561-c65e-d056-8986-7a581d133d63
* Content: [Load Data into Excel Online and build a Dataflows Monitoring Report with Power BI](https://docs.microsoft.com/en-us/power-query/dataflows/load-dataflow-metadata-into-excel-online)
* Content Source: [powerquery-docs/dataflows/load-dataflow-metadata-into-excel-online.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/load-dataflow-metadata-into-excel-online.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @hyoshioka0128 
 Thank you for your feedback. This is now under review and no further action is required at this time.
