### ISSUE TITLE
Referenced Templates are not in store - 

### ISSUE THREAD

**Issue by mscottsewell** [MicrosoftDocs/powerquery-docs#118]
There's no Power Automate template named "Trigger a dataflow refresh after my dataflow refresh completed successfully". as referenced by the document.

Not sure if the Template needs to be restored or the document needs to remove the reference to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53048912-9c2a-1cae-4e9a-02cf79307e3c
* Version Independent ID: d21f1dab-c67e-2100-f11a-82d3ba6fda9b
* Content: [Trigger Dataflows and Power BI Datasets sequentially](https://docs.microsoft.com/en-us/power-query/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially?source=docs)
* Content Source: [powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @mscottsewell -
Thanks for your feedback. The documentation has been fixed and updated.
