### ISSUE TITLE
Referenced Template is not in store

### ISSUE THREAD

**Issue by mscottsewell** [MicrosoftDocs/powerquery-docs#119]
There's no Power Automate template named "When a dataflow refresh completes, output status into CDS entity".. as referenced by the document.

Not sure if the Template needs to be restored or the document needs to remove the reference to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 664fcb9a-1542-c9f1-a76a-fe57a3afbbdd
* Version Independent ID: 0c37c598-889a-4c2f-0da9-b638006b0d1f
* Content: [Load data into a Dataverse table and build a dataflows monitoring report with Power BI](https://docs.microsoft.com/en-us/power-query/dataflows/load-dataflow-metadata-into-dataverse-table)
* Content Source: [powerquery-docs/dataflows/load-dataflow-metadata-into-dataverse-table.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/load-dataflow-metadata-into-dataverse-table.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @mscottsewell -
Thanks for your feedback. The documentation has been fixed and updated.
