### ISSUE TITLE
Language Grammar - #!"..." Syntax

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#12]
In Excel and Power BI’s Power Query editors, syntactically invalid M code can be entered and saved in the advanced editor window. However, this code cannot be inserted verbatim into the M `section-document`, as its presence would cause that document to have invalid syntax. To work around this, the editor wraps the invalid mashup code inside `#!"…"` then writes in into the document

Example: 
````
shared Query1 = let Source = #!"let a" in Source;
````

However, this `#!` syntax isn’t mentioned anywhere in the specification. 

I'm guessing the rule for this syntax should be the same as `text-literal` (e.g. supporting the same escape sequences), except, of course, this literal starts with `#!`--so something like:
````
invalid-syntax-literal: #!" text-literal-characters(opt) "
````

Can you confirm whether this is correct?

**Comment by DougKlopfenstein** [comment]
@bgribaudo Thanks for your feedback. Syntax has been added to the Consolidated grammar topic at [Literals](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#literals). The name that was used is **verbatim-literal**, to more properly match the internal name. This syntax was also added to the Lexical structure topic.

**Comment by bgribaudo** [comment]
Thank you, @DougKlopfenstein!
