### ISSUE TITLE
[LOC]Back-Translation "Power 自動"→"Power Automate" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerquery-docs#120]
ja-jp:"https://docs.microsoft.com/ja-jp/power-query/dataflows/load-dataflow-metadata-into-power-bi-dataset"
![load-dataflow-metadata-into-power-bi-dataset_j](https://user-images.githubusercontent.com/40815708/115106006-40285900-9f9d-11eb-84f0-9d0c439e39fe.png)

en-us:"https://docs.microsoft.com/en-us/power-query/dataflows/load-dataflow-metadata-into-power-bi-dataset"
![load-dataflow-metadata-into-power-bi-dataset_e](https://user-images.githubusercontent.com/40815708/115106020-4b7b8480-9f9d-11eb-9d3c-9feed05c15dd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec98c05-d02a-8bf4-52e9-3f3783accfc0
* Version Independent ID: 8247ddbe-2928-e10a-8bb5-8f42ed73016b
* Content: [Load Data into a Power BI streaming dataset and build a Dataflows Monitoring Report with Power BI](https://docs.microsoft.com/en-us/power-query/dataflows/load-dataflow-metadata-into-power-bi-dataset)
* Content Source: [powerquery-docs/dataflows/load-dataflow-metadata-into-power-bi-dataset.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/load-dataflow-metadata-into-power-bi-dataset.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @hyoshioka0128 
 Thank you for your feedback. This is now under review and no further action is required at this time.
