### ISSUE TITLE
Doesn't specify the products this applies to

### ISSUE THREAD

**Issue by edhans** [MicrosoftDocs/powerquery-docs#121]
the Cluster of Values button only exists today in the online versions, not desktop versions, of Power Query. The article doesn't make that clear that I can see. Should have an "Applies to" at the top.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d60d874-f2be-3d00-cabd-9810e7e7a415
* Version Independent ID: 5ebfbeba-7e11-0a28-5fcd-a63670914d47
* Content: [Cluster values](https://docs.microsoft.com/en-us/power-query/cluster-values)
* Content Source: [powerquery-docs/cluster-values.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/cluster-values.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **v-miesco**

**Comment by ptyx507** [comment]
Thank you for the feedback,  @edhans !

We've now added a note within the first section of the article to point this out.
