### ISSUE TITLE
[LOC]Back-Translation "電源自動化"→"Power Automate" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerquery-docs#122]
ja-jp:"https://docs.microsoft.com/ja-jp/power-query/dataflows/send-notification-when-dataflow-refresh-completes"
![send-notification-when-dataflow-refresh-completes_j](https://user-images.githubusercontent.com/40815708/115492150-30aa5800-a29c-11eb-850e-45db20db10c8.png)

en-us:"https://docs.microsoft.com/en-us/power-query/dataflows/send-notification-when-dataflow-refresh-completes"
![send-notification-when-dataflow-refresh-completes_e](https://user-images.githubusercontent.com/40815708/115492156-33a54880-a29c-11eb-8dc0-7899d54e3524.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09b19bcc-dc9d-62c4-0093-815839ef54a5
* Version Independent ID: c9228618-2fb9-52b4-d813-e3c79411d82b
* Content: [Send a Notification when a Dataflow Refresh Completes](https://docs.microsoft.com/en-us/power-query/dataflows/send-notification-when-dataflow-refresh-completes)
* Content Source: [powerquery-docs/dataflows/send-notification-when-dataflow-refresh-completes.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/send-notification-when-dataflow-refresh-completes.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @hyoshioka0128 
 Thank you for your feedback. This is now under review and no further action is required at this time.
