### ISSUE TITLE
Order Id and other fields can't be mapped 

### ISSUE THREAD

**Issue by xairrick** [MicrosoftDocs/powerquery-docs#125]
In the documentation [it suggests](https://docs.microsoft.com/en-us/power-query/dataflows/get-best-of-standard-dataflows#set-the-key-field-in-the-entity) that Order Id be used as an alternate key, but this is currently impossible because Order Id (aka OrderNumber)  can't not be mapped.

There is a "_design limitation_" that prevents a number of fields from being mapped (see support ticket 2102240040005262).    

Besides changing the example, there should be separate section noting this limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402b18e7-5542-37ae-08dd-f526c2d2b9c7
* Version Independent ID: c0ce55d5-81d3-04b5-170d-c3ca2fec48a2
* Content: [Field mapping considerations for standard dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/get-best-of-standard-dataflows)
* Content Source: [powerquery-docs/dataflows/get-best-of-standard-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/get-best-of-standard-dataflows.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @xairrick 

Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. In addition, the support ticket no longer appears to be accessible. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
