### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by Boerseuntjie** [MicrosoftDocs/powerquery-docs#126]
Got this when I searched for this template:

We couldn't find any templates that matched your search

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53048912-9c2a-1cae-4e9a-02cf79307e3c
* Version Independent ID: d21f1dab-c67e-2100-f11a-82d3ba6fda9b
* Content: [Trigger Dataflows and Power BI Datasets sequentially](https://docs.microsoft.com/en-ca/power-query/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially)
* Content Source: [powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by Boerseuntjie** [comment]
In fact there are not templates with the word "dataflows" in it??

**Comment by DougKlopfenstein** [comment]
Hi @Boerseuntjie 
Thanks for your feedback. The documentation has been fixed and updated.
