### ISSUE TITLE
[LOC]Back-Translation "Power 自動"→"Power Automate" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerquery-docs#127]
ja-jp:"https://docs.microsoft.com/ja-jp/power-query/dataflows/open-support-ticket-when-dataflow-refresh-completes"
![open-support-ticket-when-dataflow-refresh-completes_j](https://user-images.githubusercontent.com/40815708/116066341-eae9f700-a6c2-11eb-90f1-de012cab24b2.png)

en-us:"https://docs.microsoft.com/en-us/power-query/dataflows/open-support-ticket-when-dataflow-refresh-completes"
![open-support-ticket-when-dataflow-refresh-completes_e](https://user-images.githubusercontent.com/40815708/116066356-f0dfd800-a6c2-11eb-9821-fb94cfe334fc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1b1dbb-f8cb-a205-2069-ae3e664b7947
* Version Independent ID: 4f9e2c85-b57f-d75f-66ae-7e34257e5f87
* Content: [Open a Ticket when a Dataflow Refresh Fails](https://docs.microsoft.com/en-us/power-query/dataflows/open-support-ticket-when-dataflow-refresh-completes)
* Content Source: [powerquery-docs/dataflows/open-support-ticket-when-dataflow-refresh-completes.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/open-support-ticket-when-dataflow-refresh-completes.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by hyoshioka0128** [comment]
#PingMSFTDoc

**Comment by DougKlopfenstein** [comment]
Hi @hyoshioka0128 
 Thank you for your feedback. This is now under review and no further action is required at this time.
