### ISSUE TITLE
For Oauth did you mean Dec 2020 or Dec 2021

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/powerquery-docs#128]
Under Enabling OAuth Authentication in Power BI Desktop, should we wait until Dec 2021 or did you mean Dec 2020?
Jon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4c81dc-0503-5134-ddaf-2ce3e166b52d
* Version Independent ID: e4e84344-d034-5f1f-9739-7623e311672f
* Content: [Power Query QuickBooks Online connector](https://docs.microsoft.com/en-us/power-query/connectors/quickbooksonline)
* Content Source: [powerquery-docs/Connectors/QuickBooksOnline.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/QuickBooksOnline.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @pcgeekus -
Thanks for your feedback. The date has been corrected to Dec. 2020.
