### ISSUE TITLE
Language Grammar - Missing logical-literal

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#13]
`logical-literal` is referenced by `any-literal` in https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar; however, `logical-literal` isn't defined anywhere in the grammar. :-) 

Could adding `logical-literal` be put on the list for a future language specification revision?

Thanks!

**Comment by DougKlopfenstein** [comment]
@bgribaudo Thanks for the feedback. The logic-literal syntax has been added.

**Comment by bgribaudo** [comment]
Thanks, @DougKlopfenstein!
