### ISSUE TITLE
You are missing steps

### ISSUE THREAD

**Issue by ripstaur** [MicrosoftDocs/powerquery-docs#130]
I'm trying to learn to use the "Invoke Custom Function" option in Power Query. It took me a while to figure out how to get started, because you left out the instruction at the beginning that when you connect with the data you have to click on the "Transform" button to get the view that you show. 

I am now at the step where I'm trying to filter the rows using the parameter, but you don't say how to do that. I can't find the function or button or menu option to get that "Filter Rows" screen to pop up. 

Please, if you really want this to be educational, don't assume that the people you are trying to teach already know a lot of these things off the tops of their heads. We need a coherent and complete walk-through. I now see the potential in this functionality, but you haven't given me the know-how to be able to use it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adfb26bf-e0e4-fa66-409e-646c0b5ec2c6
* Version Independent ID: be67d882-0168-ea43-24aa-a3265552d983
* Content: [Using custom functions in Power Query](https://docs.microsoft.com/en-us/power-query/custom-function)
* Content Source: [powerquery-docs/custom-function.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/custom-function.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **v-miesco**

**Comment by ptyx507** [comment]
Thank you for your feedback!

We've added a new note to better explain the way that the article is laid out. The article focuses on the core concepts of the creation of a custom function and provides links and notes to learn more about specific transformations that are used throughout the article. These links take you to a thorough article that explains in detail what the transformation does, when you might want to use it and how you can use them.

We've also taken your feedback and added a more descriptive sentence that explains the process that needs to happen when you use the Folder connector.

Thanks again and let us know what you think about the new updated article.
