### ISSUE TITLE
Updated connector is not reflected in this doc -

### ISSUE THREAD

**Issue by mscottsewell** [MicrosoftDocs/powerquery-docs#133]
Yo! - 
This connector information is out of date - This describes the Dataverse connector as OData, but the current version is based on TDS - and has a very different interface and connection format - 

See this document  https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector 

Reach out and I'm happy to help clarify.  Or reach out to Rich Dickinson, the PM who owns the interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e182c32-ef1e-2092-9e8f-0643f991c17a
* Version Independent ID: 11d6812e-4d94-9024-72ad-a8ae7aa429a6
* Content: [Power Query Dataverse connector](https://docs.microsoft.com/en-us/power-query/connectors/dataverse?source=docs)
* Content Source: [powerquery-docs/Connectors/Dataverse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Dataverse.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by bezhan-msft** [comment]
@cpopell can you please take a look at this?

**Comment by DougKlopfenstein** [comment]
Hi @mscottsewell -
Thank you for your feedback. This issue has been fixed.
