### ISSUE TITLE
Graph Data Connect

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerquery-docs#136]
If Power Query still supports Microsoft Graph's Data Connect, where's your documentation about connecting to it from Power Query?  Thanks.
@bezhan-msft 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c3291b5-08aa-d48f-b7d3-aba6175ff3e5
* Version Independent ID: 3ad1ab75-5c37-e524-e6f6-a619ba0d1b85
* Content: [Power Query Microsoft Graph Security connector](https://docs.microsoft.com/en-us/power-query/connectors/microsoftgraphsecurity#deprecation)
* Content Source: [powerquery-docs/Connectors/MicrosoftGraphSecurity.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/MicrosoftGraphSecurity.md)
* Service: **powerquery**
* GitHub Login: @BEZHAN
* Microsoft Alias: **bezhan**

**Comment by bezhan-msft** [comment]
Connectivity to Microsoft Graph in Power Query is outlined in this article. - https://docs.microsoft.com/en-us/power-query/connecting-to-graph
