### ISSUE TITLE
Missing explanations about how to get items in folders in SharePoint.Tables with Implementation 2.0

### ISSUE THREAD

**Issue by santiagoti** [MicrosoftDocs/powerquery-docs#139]
The artice is missing instructions about how to retrieve items within sharepoint lists folders.

Following these instructions with the 2.0 implementation powerquery only retrieves root level folder
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a940527b-d529-0808-1bd9-33c720c5c878
* Version Independent ID: 2895e1da-ce3e-abe5-247c-78dbd545b75c
* Content: [Power Query SharePoint Online List connector](https://docs.microsoft.com/en-us/power-query/connectors/sharepointonlinelist)
* Content Source: [powerquery-docs/Connectors/SharePointOnlineList.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointOnlineList.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @santiagoti 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
