### ISSUE TITLE
Language Grammar - Is null a keyword?

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#14]
The list of [Keywords and predefined identifiers ](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#keywords-and-predefined-identifiers)does not include `null`. However, based on testing in Excel, `null` is a reserved word.

Should `null` be added to the keywords/identifiers list?

**Comment by DougKlopfenstein** [comment]
@bgribaudo Thanks for the feedback. Null has been added to the list of keywords and predefined identifiers.

**Comment by bgribaudo** [comment]
Thank you!
