### ISSUE TITLE
Mixed up function name in the docs : `Table.Reverse`

### ISSUE THREAD

**Issue by ninmonkey** [MicrosoftDocs/powerquery-docs#142]
The page for `Table.Reverse` has the signature `Text.Reverse(text as nullable text) as nullable text`

- https://docs.microsoft.com/en-us/powerquery-m/table-reverse

`Table.Reverse` doesn't exist.

![image](https://user-images.githubusercontent.com/3892031/120728365-5bdeb480-c4a2-11eb-85ef-6e9b2c78e707.png)

I'm not sure if this was the right repo?

**Comment by DougKlopfenstein** [comment]
Hi @ninmonkey 

Table.Reverse never existed. The documentation page has been removed
