### ISSUE TITLE
Process would not work and more than likely should be removed.

### ISSUE THREAD

**Issue by cvillegashak** [MicrosoftDocs/powerquery-docs#147]
Not only does the template not exist for this process in Power Automate, but you cannot create a composite model with a Real Time streaming dataset which means you cannot generate duration or meaningful data for the most part with the streaming dataset option. Also the screenshot for Power Automate isn't correct as you'd need to generate a payload in JSON format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec98c05-d02a-8bf4-52e9-3f3783accfc0
* Version Independent ID: 8247ddbe-2928-e10a-8bb5-8f42ed73016b
* Content: [Load Data into a Power BI streaming dataset and build a Dataflows Monitoring Report with Power BI](https://docs.microsoft.com/en-us/power-query/dataflows/load-dataflow-metadata-into-power-bi-dataset)
* Content Source: [powerquery-docs/dataflows/load-dataflow-metadata-into-power-bi-dataset.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/load-dataflow-metadata-into-power-bi-dataset.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @cvillegashak 
Thanks for your feedback! The article in question has been updated several times since you provided this issue. Is the issue still there in the article? Please let me know so I can update the article.

**Comment by DougKlopfenstein** [comment]
Hi @cvillegashak 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
