### ISSUE TITLE
Noticed a small correction.  Excel Power Query has and supports the Power BI datasets connector

### ISSUE THREAD

**Issue by mikem-MS** [MicrosoftDocs/powerquery-docs#148]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72df40f2-3c58-cbda-79ec-c65ba5cc32ac
* Version Independent ID: ab483b41-107f-2027-c65f-63285a847c63
* Content: [List of all Power Query connectors](https://docs.microsoft.com/en-us/power-query/connectors/#feedback)
* Content Source: [powerquery-docs/Connectors/index.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/index.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @mikem-MS -

Could you be more specific about what you would like to see corrected in the documentation? The List of all Power Query connectors article already shows that Power BI datasets are supported by Excel.

**Comment by mikem-MS** [comment]
Not from what I'm seeing.  If you look at the connector (first column) and look for the Power BI datasets row and then look alongside at the second column (Excel) in the same row, there is an x

**Comment by rootsmusic** [comment]
@DougKlopfenstein, I suggest deleting the rows for Power BI dataflows (Beta) and Power BI datasets.

**Comment by rootsmusic** [comment]
@mikem-MS, I just realized that the column header for the first column is connectors.  But the rest of the column headers are products.  So if you're looking for the product Excel, then it'd be the second column.  Within the second column, Excel doesn't support connectors for Power BI dataflows (Beta) and for Power BI datasets.

**Comment by mikem-MS** [comment]
Hi rootsmusic, I think you are saying the same thing as my previous post ??  Excel does support the Power BI datasets connector and it's prominent in Excel Power Query.  Hence, why I raised the issue.

**Comment by DougKlopfenstein** [comment]
Hi @mike-MS and @rootsmusic 
Thanks for your feedback. This issue has been fixed.
