### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by ceidinjur** [MicrosoftDocs/powerquery-docs#149]
[Enter feedback here]
Great tutorial so far.

Returning the full list of people with pagination returns a 500 error.
I recreated the pagination in Powershell for troubleshooting and it seems that the issue is caused by a null value in the FirstName field:

Invoke-RestMethod : {"error":{"code":"InternalServerError","message":"The property 'FirstName[Nullable=False]' of type 'Edm.String' has a null value, which is not allowed.","innererror":{"message":"The prope
rty 'FirstName[Nullable=False]' of type 'Edm.String' has a null value, which is not allowed.","type":"Microsoft.OData.Core.ODataException","stacktrace":"   at Microsoft.OData.Core.WriterValidationUtils.Valid
ateNullPropertyValue(IEdmTypeReference expectedPropertyTypeReference, String propertyName, ODataWriterBehavior writerBehavior, IEdmModel model, Boolean bypassValidation)\r\n   at Microsoft.OData.Core.JsonLig 
ht.ODataJsonLightPropertySerializer.WriteProperty(ODataProperty property, IEdmStructuredType owningType, Boolean isTopLevel, Boolean allowStreamProperty, DuplicatePropertyNamesChecker duplicatePropertyNamesC 
hecker, ProjectedPropertiesAnnotation projectedProperties)\r\n   at Microsoft.OData.Core.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable`1 properties, Bo 
olean isComplexValue, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, ProjectedPropertiesAnnotation projectedProperties)\r\n   at Microsoft.OData.Core.JsonLight.ODataJsonLightWriter.StartEntry(O 
DataEntry entry)\r\n   at Microsoft.OData.Core.ODataWriterCore.c__DisplayClass14.b__12()\r\n   at Microsoft.OData.Core.ODataWriterCore.InterceptException(Action action)\r\n   at Microsoft.OData.Core.ODataWri 
terCore.WriteStartEntryImplementation(ODataEntry entry)\r\n   at Microsoft.OData.Core.ODataWriterCore.WriteStart(ODataEntry entry)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.ResponseWriter.WriteE 
ntry(ODataWriter writer, Object element, IEdmNavigationSource entitySource, ODataVersion targetVersion, SelectExpandClause selectExpandClause, Dictionary`2 incomingHeaders)\r\n   at Microsoft.Test.OData.Serv 
ices.ODataWCFService.ResponseWriter.WriteFeed(ODataWriter writer, IEdmEntityType entityType, IEnumerable entries, IEdmEntitySetBase entitySet, ODataVersion targetVersion, SelectExpandClause selectExpandClaus 
e, Nullable`1 count, Uri deltaLink, Uri nextPageLink, Dictionary`2 incomingHeaders)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.QueryHandler.Process(IODataRequestMessage requestMessage, I 
ODataResponseMessage responseMessage)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.RequestHandler.Process(Stream requestStream)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handl 
ers.RootRequestHandler.Process(Stream requestStream)"}}}
At C:\Users\lunmi\OneDrive - Vestas Wind Systems A S\Scripts\PBICustomConnector\test.ps1:11 char:17
+ ... $response = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4867f9e3-aed1-7c2b-294e-cac264664a90
* Version Independent ID: a34a9995-0668-5574-a44a-753df829b31d
* Content: [TripPin 5 - Paging](https://docs.microsoft.com/en-us/power-query/samples/trippin/5-paging/readme)
* Content Source: [powerquery-docs/samples/TripPin/5-Paging/README.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/samples/TripPin/5-Paging/README.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @ceidinjur -
This appears to be a customer support request rather than an issue with the documentation.
