### ISSUE TITLE
Language Grammar - Missing item-selector

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#15]
Hello,

The definitions in [Item access expression](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#item-access-expression) reference `item-selector` twice but this non-terminal is not defined in the grammar. However, its definition is in the old language specification PDF under section 6.4.1. 

I'm guessing it should be copied into the grammar. :-)

**Comment by DougKlopfenstein** [comment]
@bgribaudo Thanks for the feedback. The item-selector syntax has been added back to the grammar.

**Comment by bgribaudo** [comment]
@DougKlopfenstein, thanks for working on this! I'm still only seeing `item-selector` referenced by two rules but not defined in the consolidated grammar.

**Comment by DougKlopfenstein** [comment]
@bgribaudo My mistake leaving out a carriage return in the consolidated grammar. Fixed now.

**Comment by bgribaudo** [comment]
Thanks, @DougKlopfenstein!
