### ISSUE TITLE
Language Specification - Identifier References and Section Members

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#151]
Under Basic Concepts, [Identifier references](https://docs.microsoft.com/en-us/powerquery-m/m-spec-basic-concepts#identifier-references), the spec says that 
>It is an error for an exclusive-identifier-reference to refer to ... an identifier that is currently being initialized.

However, the current M engine (at least, the version Excel uses) does not enforce this for section member references. The following is accepted as valid and successfully executed:
````
// Query1
(x) => if x <= 0 then 0 else x + Query1(x - 1)

// Query2
let
    Source = Query1(4)
in
    Source
````

Per the language spec, Query1's reference to itself should be disallowed; in order for it to be valid, it should be prepended with "@" (a.k.a. be an inclusive identifier reference).

Unsure whether the language specification is in error here or the M engine isn't strictly following the spec.

If the spec is in error, could it be revised to clarify? Maybe something along the lines of:
>In a record or let expression, it is an error for an exclusive-identifier-reference to refer to ... an identifier that is currently being initialized.

**Comment by bgribaudo** [comment]
@CurtHagenlocher, do you have thoughts on whether this is a spec error or the M engine going in the extra mile trying to be helpful?

**Comment by CurtHagenlocher** [comment]
Query1 is a member of the section document and as such is part of the global environment, which is always in scope.

**Comment by bgribaudo** [comment]
> Query1 is a member of the section document and as such is part of the global environment, which is always in scope.

Is that because Query1 is shared or would a non-shared Query1 also be part of the global doc and so always be in scope?

**Comment by CurtHagenlocher** [comment]
The documentation on sections says "Section member expressions may refer to other section members within the same section directly by member name." So whether or not a member is shared, any other member in the same section may refer to it. A shared member may also be referenced from other sections.

**Comment by bgribaudo** [comment]
Thanks, @CurtHagenlocher.

**Comment by ninmonkey** [comment]
Is that file in this repository ? I couldn't find it
![image](https://user-images.githubusercontent.com/3892031/144322566-6385fda4-c465-4c37-84a6-e6541d2a404f.png)

-----

The example in the 2nd paragraph of [recursive functions](https://docs.microsoft.com/en-us/powerquery-m/m-spec-functions#recursive-functions) is similar to the original


## Recursive Functions (quote)

Similarly, **mutually recursive functions can be written as long as each function that needs to
be accessed has a name**. In the following example, part of the `Factorial` function has been
refactored into a second `Factorial2` function.

```ts
[
    Factorial = (x) => if x = 0 then 1 else Factorial2(x),
    Factorial2 = (x) => x * Factorial(x – 1),
    Result = Factorial(3) // 6
]
```

**Comment by JasonWHowell** [comment]
@ninmonkey The doc code is here: https://github.com/MicrosoftDocs/query-docs-pr/blob/main/query-languages/m/m-spec-basic-concepts.md

**Comment by bgribaudo** [comment]
Hi @JasonWHowell,

I see this was assigned to me, but I don't have access to the repo to submit a PR. Can you grant me access, or submit an appropriate PR for me?

Thanks,
Ben

**Comment by JasonWHowell** [comment]
The public contributor URL is this one: https://github.com/MicrosoftDocs/query-docs/blob/main/query-languages/m/m-spec-basic-concepts.md

**Comment by bgribaudo** [comment]
Thanks, @JasonWHowell. Submitted a PR to that file.

**Comment by JasonWHowell** [comment]
Thanks for the fix @bgribaudo 
Resolving this issue. #please-close
