### ISSUE TITLE
QuickBooks Online connector page - incorrect date in troubleshooting section

### ISSUE THREAD

**Issue by mattmasson** [MicrosoftDocs/powerquery-docs#152]
The page says `Starting in December 2021` .... it should read `2020`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4c81dc-0503-5134-ddaf-2ce3e166b52d
* Version Independent ID: e4e84344-d034-5f1f-9739-7623e311672f
* Content: [Power Query QuickBooks Online connector](https://docs.microsoft.com/en-us/power-query/connectors/quickbooksonline)
* Content Source: [powerquery-docs/Connectors/QuickBooksOnline.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/QuickBooksOnline.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @mattmasson -
Thanks for your feedback. The date has been corrected to Dec. 2020.
