### ISSUE TITLE
Power Query's Table.PartitionValues page is copied and pasted from the Table.Partition page

### ISSUE THREAD

**Issue by DubbySlashy** [MicrosoftDocs/powerquery-docs#153]
The [Table.PartitionValues](https://docs.microsoft.com/en-us/powerquery-m/table-partitionvalues) page is largely identical to the [Table.Partition](https://docs.microsoft.com/en-us/powerquery-m/table-partition) page. Please make sure that the content on both of these pages reflects their respective functions.

**Comment by DubbySlashy** [comment]
Previously posted here: https://github.com/MicrosoftDocs/feedback/issues/2782

**Comment by DougKlopfenstein** [comment]
Hi @DubbySlashy 
Thanks for your feedback. This issue has been fixed.
