### ISSUE TITLE
Enabling Microsoft Edge (Chromium) for OAuth Authentication in Power BI Desktop description needs to be updated

### ISSUE THREAD

**Issue by mattmasson** [MicrosoftDocs/powerquery-docs#154]
The [Enabling Microsoft Edge (Chromium) for OAuth Authentication in Power BI Desktop](https://docs.microsoft.com/en-us/power-query/connectors/salesforceobjects#enabling-microsoft-edge-chromium-for-oauth-authentication-in-power-bi-desktop) section needs to be updated to reflect current behavior. 

- Setting `PQ_EnableEdgeChromiumOAuth` to `true` is no longer required
- We now enable Edge Chromium by default for Salesforce and Quickbooks (if it is available on the users machine) 
- Additional data sources can be forced to use Edge Chromium using the `PQ_ExtendEdgeChromiumOAuthAllowList` environment variable. 

For example, if the connector was named “MyConnector”:

setx PQ_ExtendEdgeChromiumOAuthAllowList "MyConnector"

Multiple data sources would be separated by ;.

setx PQ_ExtendEdgeChromiumOAuthAllowList "MyConnector;MyConnector2"

This note applies to all pages that had this blurb (salesforce connectors, quickbooks online). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c78a664-32c4-68c5-97ec-99d5fa4e5aab
* Version Independent ID: 75152c2f-8bed-c5df-5fa3-2470920f6dde
* Content: [Power Query Salesforce Objects connector](https://docs.microsoft.com/en-us/power-query/connectors/salesforceobjects)
* Content Source: [powerquery-docs/Connectors/SalesforceObjects.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SalesforceObjects.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by mattmasson** [comment]
Looking at the code, there are some additional environment variables that control this behavior. We should discuss which are meant to be temporary and which will last until Edge Chromium becomes the default browser.

**Comment by DougKlopfenstein** [comment]
Hi @mattmasson -
This information is now available live.
