### ISSUE TITLE
Licencing is out of date

### ISSUE THREAD

**Issue by binnall** [MicrosoftDocs/powerquery-docs#155]
The section under the heading [Link entities in Power Apps](https://docs.microsoft.com/en-us/power-query/dataflows/linked-entities#linked-entities-in-power-apps) does not contain up to date licencing information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 474d74d7-1c4b-310e-e381-c5ef6de14f65
* Version Independent ID: d8532777-57e4-51b1-306f-29cd3178bfda
* Content: [Link entities between dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/linked-entities)
* Content Source: [powerquery-docs/dataflows/linked-entities.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/linked-entities.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
Sorry for the delay on this issue. It appears that the license bit says this. Is that the problem statement?
> To be refreshed, linked entities require a [Power BI Premium](https://docs.microsoft.com/en-us/power-bi/service-premium-what-is) subscription. Linked entities are available in any dataflow on a workspace that's hosted on Power BI Premium capacity. There are no limitations on the source dataflow.

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @binnall 
Sorry for the delay in getting to this feedback. The licensing information in this article was updated some time ago, and now contains a link to more up-to-date information about Power Apps licensing. This change has made this issue moot, so I'm closing the issue.
