### ISSUE TITLE
Page needs link to example of data shaping with Power Query, especially handling of nested name/value pairs

### ISSUE THREAD

**Issue by theSaj** [MicrosoftDocs/powerquery-docs#156]
"Due to the fact that many XML documents have ragged or nested data, you may have to do extra data shaping to get it in the sort of form that will make it convenient to do analytics."

^ This is exactly what I am trying to find guidance on. The page mentions the need to do it, then provides no information, links, or resources for helping to guide how to do this.

Specifically, many XML/JSON files have nested data in "name","value" pairs.  It would be helpful to have an example that shows how to handle this very common scenario, and to have a query allows you to take data in the format of.

<xml>
  <files>
   <file>
     <property name="filename" value="myfile"/>
     <property name="filetype" value="xml"/>
     <property name="created" value="20210805"/>
     <property name="size" value="1400kb"/>
   </file>
   <file>
     <property name="filename" value="backupfile"/>
     <property name="filetype" value="json"/>
     <property name="created" value="20191204"/>
     <property name="size" value="3902kb"/>
   </file>
   <file>
     <property name="filename" value="legacydata"/>
     <property name="filetype" value="csv"/>
     <property name="created" value="20160128"/>
     <property name="size" value="58464kb"/>
   </file>
  </files>
</xml>

Now please understand, I am NOT advocating for such XML structures.  However, tons of COTS products return XML/JSON data in this fashion with nested name/value pair properties.  It would be really helpful to have an example linked to from the above section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e410e60f-00f2-b922-412e-730a846da25f
* Version Independent ID: a055c597-5c37-045c-7f30-7eb87274a2f6
* Content: [Power Query XML connector](https://docs.microsoft.com/en-us/power-query/connectors/xml)
* Content Source: [powerquery-docs/Connectors/XML.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/XML.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Thanks @theSaj  for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
