### ISSUE TITLE
Power Apps connectors

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerquery-docs#158]
Since there's already a [list of all Power Apps connectors](https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-powerapps-connectors), is it redundant to have a column in this table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72df40f2-3c58-cbda-79ec-c65ba5cc32ac
* Version Independent ID: ab483b41-107f-2027-c65f-63285a847c63
* Content: [List of all Power Query connectors](https://docs.microsoft.com/en-us/power-query/connectors/#feedback)
* Content Source: [powerquery-docs/Connectors/index.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/index.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @rootsmusic -
The Power Query documentation is the primary source of Power Query connector information, including all connectors associated with Power BI Desktop, Power BI service, Power Apps, Dynamics 365 Customer Insights, and Analysis Services. We are currently working on consolidating the generic connector information in the Power Query docs, which will provide the most up-to-date information. This is an ongoing process.

**Comment by rootsmusic** [comment]
Ok @DougKlopfenstein, then I suggest linking the [List of all Power Apps connectors](https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-powerapps-connectors) under "Next Steps".
