### ISSUE TITLE
Language Grammar - Multiple Sections

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#16]
Hello,

The [language grammar](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#section-documents) allows a `section-document` to contain exactly one section:
````
section-document:
      section
````

However, the language specification section on sections shows that documents are allowed to have multiple sections (see second example at https://docs.microsoft.com/en-us/powerquery-m/m-spec-sections).

Should the grammar be revised to allow multiple selections? Something like:
````
section-document:
      section
      section section-document
````

**Comment by CurtHagenlocher** [comment]
Any discussion about multiple sections -- whether in a single document or in multiple documents -- should be considered largely aspirational. This is a place where the internal implementation has support for something that isn't supported by any user-facing stuff today and which we currently have no plans to expose to users. We'll try to figure out how best to reflect this in the specification.

**Comment by bgribaudo** [comment]
Would it be simplest to simply rework the examples so that they don't show or allude to multiple sections in the same document and then maybe add a note stating for clarity that "Each section document must contain only one section"?

> This is a place where the internal implementation has support for something that isn't supported by any user-facing stuff today and which we currently have no plans to expose to users. We'll try to figure out how best to reflect this in the specification.

Actually, I have encountered a couple places where multiple sections are available (custom data connectors run in a world where five? sections are defined; also each embedded content item shows up as a separate section in Query Editor). :-) :-) Based on this, maybe it would be okay to leave the part of the spec that talks about accessing other sections as-is since it has relevance in describing how to access these other sections.

**Comment by DougKlopfenstein** [comment]
Hi @bgribaudo -
Thanks for your feedback. The article has been reworded so that it no longer implies that multiple sections are possible.

**Comment by bgribaudo** [comment]
Thank you, @DougKlopfenstein!
