### ISSUE TITLE
Typo in index menu

### ISSUE THREAD

**Issue by patrickdeline** [MicrosoftDocs/powerquery-docs#162]
Typo in index. Here's a screenshot.

![image](https://user-images.githubusercontent.com/85367106/132216430-c4daadc0-bca3-4d54-856c-c0f259b8341c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d0340e-4a63-4bf8-c403-2b400aac508a
* Version Independent ID: af32eaf0-8ed1-9df6-0a06-2fca7076a43a
* Content: [Using an on-premises data gateway in Power Platform dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/using-dataflows-with-on-premises-data)
* Content Source: [powerquery-docs/dataflows/using-dataflows-with-on-premises-data.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/using-dataflows-with-on-premises-data.md)
* Service: **powerquery**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by DougKlopfenstein** [comment]
Hi @patrickdeline 
Thanks for the feedback. The issue is fixed.
