### ISSUE TITLE
Powerquery  - Salesforce Authentication requirements / pre-requisites

### ISSUE THREAD

**Issue by stevie-p** [MicrosoftDocs/powerquery-docs#163]
I have found for some unknown reason, that Users also require the Manage Users permission (as well as API User) to successfully authenticate with Salesforce.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c78a664-32c4-68c5-97ec-99d5fa4e5aab
* Version Independent ID: 75152c2f-8bed-c5df-5fa3-2470920f6dde
* Content: [Power Query Salesforce Objects connector](https://docs.microsoft.com/en-us/power-query/connectors/salesforceobjects)
* Content Source: [powerquery-docs/Connectors/SalesforceObjects.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SalesforceObjects.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Thanks @stevie-p for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
