### ISSUE TITLE
about source of the table in the example

### ISSUE THREAD

**Issue by ranganathgandikota** [MicrosoftDocs/powerquery-docs#165]
[Hello Sir, It would be really helpful if you could include the source of the table database to import and practice the example 
as per the steps. Thank you for your generous support!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa9fd82-71d1-0a3f-4034-f9b5f48f544c
* Version Independent ID: 5ae72e59-d997-d53d-12ac-92285918acb8
* Content: [Promote or demote column headers](https://docs.microsoft.com/en-us/power-query/table-promote-demote-headers)
* Content Source: [powerquery-docs/table-promote-demote-headers.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/table-promote-demote-headers.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **v-miesco**

**Comment by DougKlopfenstein** [comment]
Hi @ranganathgandikota -
Thanks for your feedback. The samples in the Power Query docs were written by the original author of the articles exclusively for each individual article. There are no current plans to remake the samples and supply them online.
