### ISSUE TITLE
Connect to a SharePoint folder from Power Query Desktop

### ISSUE THREAD

**Issue by MonicaR151** [MicrosoftDocs/powerquery-docs#166]
On what version of Excel is this functionality available. I have Microsoft Business and I don't have it. It's not clear from the text if it is only available for certain versions. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7fa007-53f0-1fa5-bbff-b59fe142c804
* Version Independent ID: acb9ddd9-08ea-79ea-3537-cf8bda64282b
* Content: [Power Query SharePoint folder connector](https://docs.microsoft.com/en-us/power-query/connectors/sharepointfolder)
* Content Source: [powerquery-docs/Connectors/SharePointFolder.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointFolder.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @MonicaR151
Thanks for your feedback. Information about what versions of Excel are supported for each connector has been added as a note to the [list of connectors](https://docs.microsoft.com/power-query/connectors/). The note contains a link to the [version information](https://support.microsoft.com/office/power-query-data-sources-in-excel-versions-e9332067-8e49-46fc-97ff-f2e1bfa0cb16) available in the Excel documentation.
