### ISSUE TITLE
Does refresh of dataflows also launches refresh of linked entities?

### ISSUE THREAD

**Issue by FireFighter1017** [MicrosoftDocs/powerquery-docs#167]
The doc says "When the dataflow is refreshed, it takes the latest data for the entity from the source dataflow."  What do you mean by "latest data from linked entities"?
Does it mean the entity in question is getting refreshed as well or does it mean that the dataflow containing the linked entities only gets the data in linked entities obtained on last refresh of these entities .
Even I am not sure I explain this properly.

Let's say a Dataflow named "source1" has entity named "table1" that gets data from an Excel spreadsheet.
Then you have a dataflow named "linked1" which is linking several dataflow entities, including "table1" from "source1".
When "linked1" is refreshed, does it trigger refresh of "table1" in "source1" or does it just refresh other entities (since "table1" is kept up-to-date through refresh logic documented later in the same chapter of this page.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 474d74d7-1c4b-310e-e381-c5ef6de14f65
* Version Independent ID: d8532777-57e4-51b1-306f-29cd3178bfda
* Content: [Link entities between dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/linked-entities)
* Content Source: [powerquery-docs/dataflows/linked-entities.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/linked-entities.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Thanks @FireFighter1017 for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by FireFighter1017** [comment]
Yeah well, had I known there was a prescription delay I would've used my time elsewhere.
Thanks for nothing

**Comment by FireFighter1017** [comment]
#please-open
just trying your new bot
