### ISSUE TITLE
Missing Code Snippets?

### ISSUE THREAD

**Issue by Dacromir** [MicrosoftDocs/powerquery-docs#17]
This page mentions code snippets ("The following code snippets describe how to...") but I'm not seeing them. They'd be tremendously helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34dea978-c117-47ff-a6be-057a372b2a8f
* Version Independent ID: 377fb0ed-0e42-7d64-69b9-ac506976e15b
* Content: [Handling paging for Power Query connectors](https://docs.microsoft.com/en-us/power-query/handlingpaging#feedback)
* Content Source: [powerquery-docs/HandlingPaging.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/HandlingPaging.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by tasgray** [comment]
I second that. Examples would be great.

**Comment by DougKlopfenstein** [comment]
@Dacromir @tasgray Thanks for your feedback. The topic now contains a link to the code snippets mentioned in the paragraph.
