### ISSUE TITLE
Team in charge of VS extension says they're no longer updating it, pointing to VS Code as the new supported solution

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerquery-docs#170]
Someone from Microsoft [posted](https://marketplace.visualstudio.com/items?itemName=Dakahn.PowerQuerySDK&ssr=false#qna) on 5/7/2021 that:

> "We aren't planning on making further updates to the Visual Studio based Power Query SDK. All future development efforts are focused on enabling a similar experience in VS Code."

This is confirmed by the fact the VS Power Query SDK was last updated on 8/18/2019 while the latest [VS Code extension](https://marketplace.visualstudio.com/items?itemName=PowerQuery.vscode-powerquery) is from 8/2/2021.

The intro paragraph should be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7197933-1715-939b-1236-7b29268f1fc7
* Version Independent ID: 129d4a85-4de2-e380-1700-f71e9c6faa41
* Content: [Start developing custom connectors for Power Query](https://docs.microsoft.com/en-us/power-query/startingtodevelopcustomconnectors)
* Content Source: [powerquery-docs/StartingToDevelopCustomConnectors.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/StartingToDevelopCustomConnectors.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by otravers** [comment]
Chris Webb tells me that: _"You can’t develop custom connectors in VS Code yet, although the plan is that you will be able to in the future. The VS Code extension you linked to only allows you to write M code, not custom connectors."_

**Comment by DougKlopfenstein** [comment]
Hi @otravers -
From the Power Query team:
"We are maintaining and improving the current Power Query SDK with various features. But, we are working toward a VS Code-based Power Query SDK in the future."
