### ISSUE TITLE
Excel Content copy/paste

### ISSUE THREAD

**Issue by ptacquet** [MicrosoftDocs/powerquery-docs#174]
[There's a problem in this page, it explains how to use excel, not a streaming dataset]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec98c05-d02a-8bf4-52e9-3f3783accfc0
* Version Independent ID: 8247ddbe-2928-e10a-8bb5-8f42ed73016b
* Content: [Load Data into a Power BI Streaming Dataset and build a Dataflows Monitoring Report with Power BI](https://docs.microsoft.com/en-us/power-query/dataflows/load-dataflow-metadata-into-power-bi-dataset)
* Content Source: [powerquery-docs/dataflows/load-dataflow-metadata-into-power-bi-dataset.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/load-dataflow-metadata-into-power-bi-dataset.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @ptacquet -
Thanks for your feedback. The page has been fixed and updated.
