### ISSUE TITLE
Dead links in the notes on generating certificates

### ISSUE THREAD

**Issue by ParkerM** [MicrosoftDocs/powerquery-docs#178]
The "New-SelfSignedCertificate in PowerShell" and "How to create a PKCS#12 (PFX) file on a Windows server" links referenced [here](https://github.com/MicrosoftDocs/powerquery-docs/blob/6c79fcb4f31c17339b7ae584e21acbf0b63e9ace/powerquery-docs/HandlingConnectorSigning.md?plain=1#L22-L26) both lead to 404 pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31ae22e9-a9c4-1c9f-fa5d-4519aa4b9ae2
* Version Independent ID: 1ec143fa-0b4b-0a2c-ca78-fde24ea45fe8
* Content: [Handling Connector Signing](https://docs.microsoft.com/en-us/power-query/handlingconnectorsigning)
* Content Source: [powerquery-docs/HandlingConnectorSigning.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/HandlingConnectorSigning.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @ParkerM -
Thanks for your feedback. The links have been fixed.
