### ISSUE TITLE
Language Grammar - Field access expression implicit-target-projection

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#18]
Hello,

In the language grammar, [Field access expressions](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#field-access-expressions) defines `field-access-expression` as one of several alternatives including `projection` and `implicit-target-projection`. In turn, `implicit-target-projection` is also defined as `projection`. I believe the latter is incorrect.

`projection` requires the presence of an explicit target (i.e. the presence of a `primary-expression`), which, by definition, shouldn't be expected for an implicit target (e.g. `[[Field1]]`, which Excel accepts as valid but this grammar rule rejects). 

It seems like the correct definition for `implicit-target-projection` should be along the lines of the following:
````
implicit-target-projection:
  required-projection
  optional-projection
````
(e.g. eliminate the requirement that a `primary-expression` be used before the projection)

Can you confirm?

Thank you!

**Comment by DougKlopfenstein** [comment]
@bgribaudo Thanks for the feedback. Yes, we can confirm. The implicit-target-projection syntax now includes the optional-projection syntax.

**Comment by bgribaudo** [comment]
Thank you, @DougKlopfenstein!
