### ISSUE TITLE
The world I'm in does not work this way

### ISSUE THREAD

**Issue by Ripstaur623** [MicrosoftDocs/powerquery-docs#181]
So, the world I work in does not work this way. When I go to a sharepoint folder, I don't get the nice clean url you show here. What I get is (If I just go to the sharepoint site url) every single file in the whole site in the list. If I try to put in the url for the actual folder, I get errors.  This feature would be perfect for what I'm trying to do, but it just doesn't work. Is it because we have all sharepoint online? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7fa007-53f0-1fa5-bbff-b59fe142c804
* Version Independent ID: acb9ddd9-08ea-79ea-3537-cf8bda64282b
* Content: [Power Query SharePoint folder connector](https://docs.microsoft.com/en-us/power-query/connectors/sharepointfolder)
* Content Source: [powerquery-docs/Connectors/SharePointFolder.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointFolder.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @Ripstaur623 -
This appears to be a customer support issue rather than a documentation issue. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
