### ISSUE TITLE
Next steps link is to same page

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/powerquery-docs#183]
The 'Next steps' link at the foot of the page seems to go back to the same page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4c81dc-0503-5134-ddaf-2ce3e166b52d
* Version Independent ID: e4e84344-d034-5f1f-9739-7623e311672f
* Content: [Power Query QuickBooks Online connector](https://docs.microsoft.com/en-gb/power-query/connectors/quickbooksonline)
* Content Source: [powerquery-docs/Connectors/QuickBooksOnline.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/QuickBooksOnline.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @biterbit -
Thanks for your feedback. The information that wasy originally at the Next steps link was moved to the QuickBooks Online connector page, so the link was removed.
