### ISSUE TITLE
Diagram text is unreadable in dark mode

### ISSUE THREAD

**Issue by sshquack** [MicrosoftDocs/powerquery-docs#186]
Can't read the text in Firefox and Safari on macOS dark mode.

<img width="1552" alt="Screen Shot 2021-11-21 at 5 45 04 PM" src="https://user-images.githubusercontent.com/5678459/142789194-1fa8e30c-81b1-4be0-831c-9d24c3ac65e3.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9b1e7c-616b-87e0-7858-7f9e83b69ea5
* Version Independent ID: 5ffba9ae-ac08-3375-df06-507e7b6336f3
* Content: [What is Power Query?](https://docs.microsoft.com/en-us/power-query/power-query-what-is-power-query)
* Content Source: [powerquery-docs/power-query-what-is-power-query.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-what-is-power-query.md)
* Service: **powerquery**
* GitHub Login: @mllopis
* Microsoft Alias: **millopis**

**Comment by DougKlopfenstein** [comment]
Hi @sshquack 
Thanks for your feedback. The problem has been fixed.
