### ISSUE TITLE
resources

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerquery-docs#188]
This doc links to "[website resources](https://powerquery.microsoft.com/en-us/resources/)".  Since your documentation (on Microsoft Docs) has a folder for "resources", please move your resources to a Microsoft Doc.  (Doing so would allow feedback like this about the Microsoft Doc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd6b034-1753-6368-19d9-bb699a24b768
* Version Independent ID: 5b80c524-3870-f774-e4cd-950e56da9653
* Content: [Power Query feedback](https://docs.microsoft.com/en-us/power-query/feedback)
* Content Source: [powerquery-docs/feedback.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/feedback.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
@rootsmusic Unfortunately, we are behind on responding to feedback, and this is a nice-to-have idea, but we can't work on it right now. Since the current resources page functions well, I think we will need to leave it as is.
