### ISSUE TITLE
Cannot log in Quickbooks account 

### ISSUE THREAD

**Issue by Jerryxoxo** [MicrosoftDocs/powerquery-docs#189]
![image](https://user-images.githubusercontent.com/63485422/144166609-7ddc560a-8d2a-4343-9368-8316ef6708c9.png)
I can't log in to my Quickbooks account while connecting Power BI to my dataset.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4c81dc-0503-5134-ddaf-2ce3e166b52d
* Version Independent ID: e4e84344-d034-5f1f-9739-7623e311672f
* Content: [Power Query QuickBooks Online connector](https://docs.microsoft.com/en-us/power-query/connectors/quickbooksonline)
* Content Source: [powerquery-docs/Connectors/QuickBooksOnline.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/QuickBooksOnline.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @Jerryxoxo -
This appears to be a customer support issue rather than a documentation issue. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
