### ISSUE TITLE
Language Grammar - record-type requires at least one field

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#19]
In the language grammar, [Type expression](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#type-expression)’s definition of `record-type` requires that at least one field be specified, or an `open-record-marker` be provided. This disallows the following, both of which are valid Power Query syntax, per testing in Excel: 
````
type []
type table []
````

To rectify, I believe `record-type`'s definition should be changed so that the field specification list is optional--something like:
```
record-type:
      [ open-record-marker ]
      [ field-specification-list(opt) ]
      [ field-specification-list , open-record-marker ]
````

Can you confirm that this is the correct definition?

Thank you!

**Comment by DougKlopfenstein** [comment]
@bgribaudo Thanks for the feedback. Yes, this is the correct definition. This information has been added.
