### ISSUE TITLE
Web query parameters not explained

### ISSUE THREAD

**Issue by adam-nielsen** [MicrosoftDocs/powerquery-docs#190]
When creating a web query and selecting the 'advanced' mode, there is the option to supply multiple URL parts.

<img src="https://docs.microsoft.com/en-us/power-query/connectors/web/webadvancedurl.png"/>

The tooltip for these fields (visible by hovering over the "i" next to the "URL parts" text) says they can "reference a parameter", however the documentation here does not go into details about what those parameters are.

For example it leads me to think that within Excel I can use a cell value as a component of the URL, however I am unable to see how this could be done.

Would it be possible to add some explanations about what these parameters are and how to enter a reference to them?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a98d1ec-7541-bea3-8a81-f6866fc44987
* Version Independent ID: caa83640-71e7-f7e2-4ab7-5f9b5c9a9004
* Content: [Power Query Web connector](https://docs.microsoft.com/en-us/power-query/connectors/web/web)
* Content Source: [powerquery-docs/Connectors/Web/Web.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Web/Web.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by adam-nielsen** [comment]
Many thanks, that made much more sense!  It just wasn't obvious how to get there from that page in the docs!  It looks like the version that pops up in Excel is a cut down dialog box, and it's not until you go back and edit the query that you see all the other information, which isn't obvious for a first-time user.

**Comment by robbiepaine** [comment]
Is there a plan to upgrade the web browser from Internet Explorer 10? Some websites aren't compatible with IE, so the "From Web" function doesn't work.
