### ISSUE TITLE
Full outer Join for unique records 

### ISSUE THREAD

**Issue by semohammadi** [MicrosoftDocs/powerquery-docs#191]
[Enter feedback here]
Hi
The example given is incomplete and does not show the state in which we need unique records

Br,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b423ec9-b5ae-5cc4-90dc-9f2f272229f2
* Version Independent ID: a9af2218-897f-4a31-9b04-131ff3a6774b
* Content: [Full outer join](https://docs.microsoft.com/en-us/power-query/merge-queries-full-outer)
* Content Source: [powerquery-docs/merge-queries-full-outer.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/merge-queries-full-outer.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **dougklo**

**Comment by ptyx507x** [comment]
Hey @semohammadi 

Sorry for the late reply. Could you further explain what the article is missing or how we could improve it?

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by JasonWHowell** [comment]
@semohammadi thanks for the feedback. 

We need about clarification on the issue, but haven't heard back in a while. Closing it for now, but please respond and reopen  if you have a chance.  Thanks, Jason

#please-close
