### ISSUE TITLE
Lack of Solutioning!

### ISSUE THREAD

**Issue by bbrown44** [MicrosoftDocs/powerquery-docs#194]
I understand knowing the core concept can help resolve an issue, but this is way too dense!!!

Many of us are coming here to determine how to cure the thrown error.  Brevity can be your best friend!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cf52bcc-93b4-7ffe-8ba6-1eba7acb7be1
* Version Independent ID: 4bcfbf05-8981-99c2-e736-d103e9126371
* Content: [Behind the scenes of the Data Privacy Firewall - Power Query](https://docs.microsoft.com/en-us/power-query/dataprivacyfirewall)
* Content Source: [powerquery-docs/DataPrivacyFirewall.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/DataPrivacyFirewall.md)
* Service: **powerquery**
* GitHub Login: @ehrenMSFT
* Microsoft Alias: **gepopell**

**Comment by ehrenMSFT** [comment]
Are you looking for the kind of info contained in the Example section at the end?

**Comment by ehrenMSFT** [comment]
I'm referring to this section:
https://docs.microsoft.com/en-us/power-query/dataprivacyfirewall#example-passing-data-from-one-data-source-to-another

This is the data privacy error we're most often asked about.

**Comment by JasonWHowell** [comment]
This error could be added to a simple troubleshooting page, though I do see a bunch of blogs that already touch on the topic.

**Comment by JasonWHowell** [comment]
We haven't heard back in a long time. Unfortunately, we can't proceed without a specific scenario in mind.
