### ISSUE TITLE
Google BigQuery missing

### ISSUE THREAD

**Issue by margobeyer8** [MicrosoftDocs/powerquery-docs#195]
Google BigQuery missing from the list of connectors that support Native Database queries.

https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/data-integration/google-bigquery-connector-native-query-support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d406515e-e0a3-1342-e6ba-50249fc76ee3
* Version Independent ID: 69dd8c4e-1dbe-dad6-54f3-5c5203d89fde
* Content: [Import data from a database using native database query - Power Query](https://docs.microsoft.com/en-us/power-query/native-database-query)
* Content Source: [powerquery-docs/native-database-query.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/native-database-query.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @margobeyer8 
Thanks for your feedback. This issue has been fixed.
