### ISSUE TITLE
Missed Invoke Custom Function

### ISSUE THREAD

**Issue by semohammadi** [MicrosoftDocs/powerquery-docs#198]
[Enter feedback here]

Hi
I couldn't find Invoke Custom Function in this Article

Br
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d60d874-f2be-3d00-cabd-9810e7e7a415
* Version Independent ID: 5ebfbeba-7e11-0a28-5fcd-a63670914d47
* Content: [Cluster values - Power Query](https://docs.microsoft.com/en-us/power-query/cluster-values)
* Content Source: [powerquery-docs/cluster-values.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/cluster-values.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **dougklo**

**Comment by DougKlopfenstein** [comment]
Hi @semohammadi 
The document you mention is about cluster values. Are you looking for information that's in the 
[Using custom functions](https://docs.microsoft.com/power-query/custom-function) article? Could you provide more details about your issue?

**Comment by JasonWHowell** [comment]
Hoping Doug's link will resolve the inquiry. 

Looks like this issue has been idle for a while, and we haven't heard back with the clarification requested. I'm resolving this issue for now, but please let us know if further assistance is needed.
