### ISSUE TITLE
SAP HANA Database connector properties

### ISSUE THREAD

**Issue by rjagdon** [MicrosoftDocs/powerquery-docs#199]
In the section : Connect to an SAP HANA database Power Query Online, the SAP HANA database connector for dataflows is slightly different from the documentation. Now, it looks like the snapshot below.

![image](https://user-images.githubusercontent.com/53030174/146117314-d7a02c30-c4e7-4b1d-b4d1-043111d03c46.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2004a868-d222-b312-3234-76a04202dfb1
* Version Independent ID: 06071015-8348-9c7b-9497-c4af21c176ea
* Content: [Power Query SAP HANA database connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/sap-hana/overview)
* Content Source: [powerquery-docs/Connectors/sap-hana/overview.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/sap-hana/overview.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @rjagdon 
Thanks for your feedback! The [Connect to an SAP HANA database from Power Query Online](https://docs.microsoft.com/en-us/power-query/connectors/sap-hana/overview#connect-to-an-sap-hana-database-from-power-query-online) section is now up to date.
