### ISSUE TITLE
Tutorial Link 404s

### ISSUE THREAD

**Issue by saviourofdp** [MicrosoftDocs/powerquery-docs#2]
The link to the Tutorial page (https://docs.microsoft.com/en-us/samples/TripPin/README.md) results in a 404 page not found error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8894707-356e-6c86-76fd-c8d6d6c199b6
* Version Independent ID: a4ab5009-5153-df99-e515-8c4c2e4949d5
* Content: [Installing the Power Query SDK](https://docs.microsoft.com/en-us/power-query/installingsdk)
* Content Source: [powerquery-docs/InstallingSDK.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/InstallingSDK.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Link fixed. See here:
https://review.docs.microsoft.com/en-us/power-query/installingsdk?branch=master

Fourth link under the "Additional links and resources" header.

Ready to go live.

**Comment by KumarVivek** [comment]
@saviourofdp This issue is fixed; closing it.
