### ISSUE TITLE
Language Grammar - literal-item-list missing single item option

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#20]
In the grammar, [Literal Attributes](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#literal-attributes) contains the following definition:
````
literal-item-list:
      any-literal , literal-item-list
````

The above is missing the state for a single item, resulting in it (recursively) requiring an infinite number of items. I believe this definition should be changed to the following:
````
literal-item-list:
      any-literal
      any-literal , literal-item-list
````

Does this sound correct?

Thanks!

**Comment by DougKlopfenstein** [comment]
@bgribaudo Thanks for the feedback. Yes, you are correct. This information has been updated.

**Comment by bgribaudo** [comment]
Thank you, @DougKlopfenstein!
