### ISSUE TITLE
Data privacy analysis - "TOP 1000" - why?

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#201]
Hello,

The [Data privacy analysis](https://docs.microsoft.com/en-us/power-query/multiple-queries#data-privacy-analysis) section of this article says:

> Data privacy does its own evaluations of each query to determine whether the queries are safe to run together. This evaluation can sometimes cause multiple requests to a data source. A telltale sign that a given request is coming from data privacy analysis is that it will have a “TOP 1000” condition (although not all data sources support such a condition). [...]

However, [Behind the scenes of the Data Privacy Firewall](https://docs.microsoft.com/en-us/power-query/dataprivacyfirewall) doesn't seem to mention anything about the firewall needing to fetch actual data rows (e.g. to do a "TOP 1000"); rather, from the description given, it sounds like the firewall can compute whether two data sources can fold together based on data _source_-level (not data _set_-level) information, principally by looking at the configured privacy level settings for the sources (which doesn't involve needing to fetch actual row data).

Could you shed some light on why enforcing privacy can involve fetching data/doing "TOP 1000"s?

Is the data fetching (e.g. "TOP 1000") done as part of determining whether it would be efficient to write values from one source into the native request sent to another source when that is allowed by the privacy level settings? So not per se for privacy reasons but rather for efficiency reasons (i.e. to determine the most efficient way to perform query folding)?

Thank you,
Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd55b51f-8893-993d-b798-1ac3ba62f513
* Version Independent ID: fd55b51f-8893-993d-b798-1ac3ba62f513
* Content: [Why does my query run multiple times - Power Query](https://docs.microsoft.com/en-us/power-query/multiple-queries)
* Content Source: [powerquery-docs/multiple-queries.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/multiple-queries.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **dougklo**

**Comment by bgribaudo** [comment]
CC @migueesc123

**Comment by JasonWHowell** [comment]
My guess is that connectors to databases often check metadata (data types) by querying a few rows to get the shape of the data to allocate data types before accepting many rows.

**Comment by bgribaudo** [comment]
Thanks, @JasonWHowell.

Sometime after posting this issue, a similar question was posted and answered on the Power Query forums. I missed noting that answer here (my apologizes!). 

From @ehrenMSFT ([original reply link](https://community.powerbi.com/t5/Power-Query/Data-Protection-Firewall-Why-TOP-1000/m-p/2303998/highlight/true#M68521)):

> The mashup engine doesn't have any static info about what data sources are being accessed by a given query or step. That info is surfaced at runtime, when a given query is being evaluated. So in order for the firewall to perform the logic described in the "Behind the scenes" article, it pulls the first 1k rows for any partition it's interested in. Doing so results in the partition's data source(es) being surfaced.
