### ISSUE TITLE
Bigquery  native connector for Desktop

### ISSUE THREAD

**Issue by bamakus** [MicrosoftDocs/powerquery-docs#203]
Hi power query team 

1)
ERROR [HY000] [Microsoft][BigQuery] (131) Unable to authenticate with Google BigQuery Storage API. Check your account permissions  
<-- sorry we dont' see this warning (Desktop & refresh history)   all the time ,   if readsessions* permission are missing
 Can you check please ?  

2) Why is your underlying techno is  still **ODBC in 2022 ,please**  ? can you go to a more modern connector please?

3) ODBC seems not to like the Google Storage API perfectly (rows missing without warning for large volume)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf2a1e4a-489b-36e7-3c01-9590bc22a232
* Version Independent ID: 6d317817-8ea4-e601-7260-bf41632eef29
* Content: [Google BigQuery connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/googlebigquery)
* Content Source: [powerquery-docs/Connectors/GoogleBigQuery.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/GoogleBigQuery.md)
* Service: **powerquery**
* GitHub Login: @BEZHAN
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @bamakus 
This seems to be product feedback or a request for product support. For information about product feedback or customer support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback).
