### ISSUE TITLE
ODBC underlying techno ? 

### ISSUE THREAD

**Issue by bamakus** [MicrosoftDocs/powerquery-docs#204]
Why is your underlying techno is still ODBC  in 2022 ,please ? can you go to a more modern connector please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38e8eb21-ce6a-dae6-8a93-a68659aedd30
* Version Independent ID: 112cbadd-b770-66af-a3d8-7291c157e9c2
* Content: [Power Query Snowflake connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/snowflake)
* Content Source: [powerquery-docs/Connectors/Snowflake.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Snowflake.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @bamakus 
This seems to be product feedback or a request for product support. For information about product feedback or customer support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback).
