### ISSUE TITLE
Misleading limitations of capabilities: DirectQuery mode

### ISSUE THREAD

**Issue by slavatrofimov** [MicrosoftDocs/powerquery-docs#205]
This documentation page lists a limitation in supported capabilities stating that DirectQuery is supported only for Power BI Desktop. This is incorrect -- the Power BI Service supports connectivity to BigQuery in DirectQuery mode. Please remove the misleading capability limitation from this documentation page. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf2a1e4a-489b-36e7-3c01-9590bc22a232
* Version Independent ID: 6d317817-8ea4-e601-7260-bf41632eef29
* Content: [Google BigQuery connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/googlebigquery#connect-to-google-bigquery-data-from-power-query-online)
* Content Source: [powerquery-docs/Connectors/GoogleBigQuery.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/GoogleBigQuery.md)
* Service: **powerquery**
* GitHub Login: @BEZHAN
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @slavatrofimov 
Thanks for your feedback. This issue has been fixed.

**Comment by VitalyMCT** [comment]
@DougKlopfenstein There may be some intricacies around this that require clarification in documentation.

I've just tried to use DirectQuery with this connector from both Dataflows and Dataflows Gen2 (i.e. from Power Query Online). The option to select DirectQuery is missing in both of these scenarios.

Can you please research these aspects and update this page to clarify what's available around DirectQuery?
