### ISSUE TITLE
Enable SQL Server Failover support <> ApplicationIntent=ReadOnly

### ISSUE THREAD

**Issue by somunteanu** [MicrosoftDocs/powerquery-docs#207]
Hi Team,

This is regarding the PowerQuery SQL Server connector and the advanced option: Enable SQL Server Failover support.

In order to achieve a connection to the Read Only Replica of a SQL DB from Power BI, I've noticed this more or less official practice of using this advanced option based on the assumption that once choosing the option: Enable SQL Server Failover support, simultaneously and "under the hood" the parameter ApplicationIntent is set to ReadOnly.

Is this something we recommend? Or is the "Enable SQL Server Failover support" rather for failover purposes?

Thanks,
Sorin
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e77b6456-8d48-b1fc-cba3-993d1f8d5cae
* Version Independent ID: 0ca84a81-e16e-a2f7-1cac-00082cf0d86b
* Content: [Power Query SQL Server connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/sqlserver)
* Content Source: [powerquery-docs/Connectors/SQLServer.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SQLServer.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @somunteanu 
Thanks for your feedback.
This appears to be a customer support issue rather than a documentation issue. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
