### ISSUE TITLE
Using incremental refresh with dataflows - XMLA endpoint

### ISSUE THREAD

**Issue by bslattz** [MicrosoftDocs/powerquery-docs#208]
[Enter feedback here]
Please elaborate on the following statement...

 After XMLA-endpoints for Power BI Premium are available, the partitions become visible.

How can we manage dataflow partitions via XMLA-endpoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc816e2-78f6-ca70-92a3-b2153461759d
* Version Independent ID: e6fec9a8-1c47-b739-5146-0fa717c4535e
* Content: [Using incremental refresh with dataflows - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/incremental-refresh)
* Content Source: [powerquery-docs/dataflows/incremental-refresh.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/incremental-refresh.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @bslattz 
Thanks for your feedback.
This appears to be a customer support issue rather than a documentation issue. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
