### ISSUE TITLE
Misleading information about Dataflows partitions regarding XMLA endpoints

### ISSUE THREAD

**Issue by bstar92** [MicrosoftDocs/powerquery-docs#209]
[Enter feedback here]
https://docs.microsoft.com/en-us/power-query/dataflows/incremental-refresh#incremental-refresh-implementation-details

The second sentence from the paragraph is misleading. Unless there is ADLS Gen2 subscription attached, the dataflows partitions 
are not visible. And XMLA-endpoints do not work for Dataflows, they only work for Datasets.

Source:
Incremental refresh implementation details
Dataflows use partitioning for incremental refresh. **After XMLA-endpoints for Power BI Premium are available, the partitions become visible**...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc816e2-78f6-ca70-92a3-b2153461759d
* Version Independent ID: e6fec9a8-1c47-b739-5146-0fa717c4535e
* Content: [Using incremental refresh with dataflows - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/incremental-refresh#feedback)
* Content Source: [powerquery-docs/dataflows/incremental-refresh.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/incremental-refresh.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @bstar92 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
