### ISSUE TITLE
Add a link to the next lesson.

### ISSUE THREAD

**Issue by Dilipsam1** [MicrosoftDocs/powerquery-docs#21]
Add a link to the next lesson.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea5ab12-0b6e-20b5-1659-d872db778b6d
* Version Independent ID: d642b0fd-460c-c8aa-922a-28569d7cf986
* Content: [TripPin 1 - OData](https://docs.microsoft.com/en-us/power-query/samples/trippin/1-odata/readme)
* Content Source: [powerquery-docs/samples/TripPin/1-OData/README.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/samples/TripPin/1-OData/README.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
@Dilipsam1 Thanks for your feedback. The entire TripPin tutorial now contains links at the end of each topic that point to the next topic in the tutorial.
