### ISSUE TITLE
The link to the sp online documentation in the paragraph is broken

### ISSUE THREAD

**Issue by mastershake2020** [MicrosoftDocs/powerquery-docs#213]
The link to the sp online documentation in the paragraph is broken

SharePoint join limit
This issue is limited to the SharePoint Online list v2.0 connector

The SharePoint Online list v2.0 connector uses a different API than the v1.0 connector and, as such, is subject to a maximum of 12 join operations per query, as documented in the **SharePoint Online documentation** under List view lookup threshold. This issue will manifest as SharePoint queries failing when more than 12 columns are accessed simultaneously from a SharePoint list.

https://docs.microsoft.com/en-us/SharePoint/SharePointServer/install/software-boundaries-limits-2019?source=docs#list-and-library-limits

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a940527b-d529-0808-1bd9-33c720c5c878
* Version Independent ID: 2895e1da-ce3e-abe5-247c-78dbd545b75c
* Content: [Power Query SharePoint Online list connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/sharepointonlinelist#connect-to-sharepoint-online-list-v20-beta)
* Content Source: [powerquery-docs/Connectors/SharePointOnlineList.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointOnlineList.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @mastershake2020 
Thanks for your feedback. The link has been fixed.
