### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by heschelpop** [MicrosoftDocs/powerquery-docs#215]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7fa007-53f0-1fa5-bbff-b59fe142c804
* Version Independent ID: acb9ddd9-08ea-79ea-3537-cf8bda64282b
* Content: [Power Query SharePoint folder connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/sharepointfolder#connect-to-a-sharepoint-folder-from-power-query-desktop)
* Content Source: [powerquery-docs/Connectors/SharePointFolder.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointFolder.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @heschelpop 
Due to lack of feedback, this issue was closed. If you think the issue was closed in error or if you want to supply more information in the future, you can reopen the issue.
