### ISSUE TITLE
Incremental refresh

### ISSUE THREAD

**Issue by ptacquet** [MicrosoftDocs/powerquery-docs#217]
Hi,

I use dataflows in a project.
I have a big table (180 Millions of rows).
I refresh it with an incremental refresh as you recommend it in this page.

But i have a problem refreshing the dataset based on this dataflow => I can't use incremental dataset refresh based on a dataflow with incremental refresh. You support team tells me not to use dataflows but directly SQL...

It's not coherent with this page. You should precise this in this page ! 
It makes me lost a lot of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3eb5e57-5f02-acca-6344-847ff0432f14
* Version Independent ID: 9f805c9b-fe75-4bf5-b532-6061d88e1d9e
* Content: [Best practices for creating a data warehouse using dataflows - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/best-practices-for-data-warehouse-using-dataflows)
* Content Source: [powerquery-docs/dataflows/best-practices-for-data-warehouse-using-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/best-practices-for-data-warehouse-using-dataflows.md)
* Service: **powerquery**
* GitHub Login: @radacad
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @ptacquet 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
