### ISSUE TITLE
AAD Authentication - handling access token expiration when querying from Gateway

### ISSUE THREAD

**Issue by jgibbycsc** [MicrosoftDocs/powerquery-docs#218]
The documentation for OAuth2 provides code examples of implementing token refresh prior to expiration. 

AAD Auth examples only provide Resource and Authorization URI. 

It appears that access refresh occurs when using AAD authentication from Power BI Desktop, but when implemented using Power BI Enterprise Gateway, the token is not refreshed and a 401 error response is returned.

Could an example please be provided for implementation of token refresh that works with the Gateway?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58e66f41-e084-8f8a-8828-12474f21f0d7
* Version Independent ID: 77eafe80-5569-eee6-042e-e425a9056570
* Content: [Handling authentication for Power Query connectors - Power Query](https://docs.microsoft.com/en-us/power-query/handlingauthentication#azure-active-directory-authentication)
* Content Source: [powerquery-docs/HandlingAuthentication.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/HandlingAuthentication.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by syendev** [comment]
+ 1

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @jgibbycsc @syendev 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
