### ISSUE TITLE
Now titled Computed tables

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerquery-docs#219]
The term computed entities which is used throughout this document is no longer applicable as they are now titled computed tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 016cc5b0-e90e-c87e-874f-d71cc5d740b8
* Version Independent ID: 486eeb0a-d69d-3a9a-f17d-10482de0dcf2
* Content: [Computed entity scenarios and use cases - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/computed-entities-scenarios)
* Content Source: [powerquery-docs/dataflows/computed-entities-scenarios.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/computed-entities-scenarios.md)
* Service: **powerquery**
* GitHub Login: @radacad
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @itsnotaboutthecell 
All instances of computed entity throughout the Power Query documentation has been updated to "computed table" or "computed tables".
