### ISSUE TITLE
OAuth flow links are outdated/broken

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/powerquery-docs#22]
In the first section of the page, these links are broken, and send users to the Graph homepage:
Microsoft Graph App authentication using Azure AD
Permission scopes

Additionally, the "Authentication Code Grant Flow" link sends to the v1 page. Should forward to the more recent v2 page: (https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6f55e2-dc4a-c0ac-296b-c41d02bea7f5
* Version Independent ID: 767b1dbc-dd20-f5cd-7afa-bdd17458c233
* Content: [Microsoft Graph tutorial for Power Query](https://docs.microsoft.com/en-us/power-query/samples/mygraph/readme#writing-an-oauth-v2-flow-with-power-bi-desktop)
* Content Source: [powerquery-docs/samples/MyGraph/README.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/samples/MyGraph/README.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
@joshtransient Thanks for the feedback.

This issue is being marked as "Closed" because the MyGraph topic no longer exists.
