### ISSUE TITLE
Support for Onpremises data source

### ISSUE THREAD

**Issue by reshimiz** [MicrosoftDocs/powerquery-docs#220]
This article says only the following connections can connect to on-premises data, but according to [this article](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources), some other connectors support the on-premises data gateway.
How can we understand this gap?

> With a gateway, you can connect to on-premises data through these connections:
> 
> SharePoint
> SQL Server
> Oracle
> Informix
> Filesystem
> DB2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d0340e-4a63-4bf8-c403-2b400aac508a
* Version Independent ID: af32eaf0-8ed1-9df6-0a06-2fca7076a43a
* Content: [Using an on-premises data gateway in Power Platform dataflows - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/using-dataflows-with-on-premises-data)
* Content Source: [powerquery-docs/dataflows/using-dataflows-with-on-premises-data.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/using-dataflows-with-on-premises-data.md)
* Service: **powerquery**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by DougKlopfenstein** [comment]
Hi @reshimiz 
Thanks for your feedback. The text you highlighted is confusing and contradictory, so it was removed.
