### ISSUE TITLE
Missing diference between Documentation.Description and Documentation.LongDescription

### ISSUE THREAD

**Issue by tirnovar** [MicrosoftDocs/powerquery-docs#224]
[Enter feedback here]

You are speaking here about Documentation.LongDescription in Function Documentation, but you can use Documentation.Description and the result will look very the same. People can be confused when they will see the usage of Documentation.Description and have no information about it in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a834875-02f7-683d-5845-618a5d02d888
* Version Independent ID: 36b3e58d-e580-a9fd-4239-7d51b24fdeb6
* Content: [Adding function documentation - Power Query](https://docs.microsoft.com/en-us/power-query/handlingdocumentation)
* Content Source: [powerquery-docs/HandlingDocumentation.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/HandlingDocumentation.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by tirnovar** [comment]
Hello, do you know if there is any progress?

**Comment by DougKlopfenstein** [comment]
Hi @tirnovar 
Thanks for your dedication to our documentation. Unfortunately, we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response.

The Documentation.Description field is only used in the Microsoft documentation to fill in the tables used in the function category articles. As such, it's not meant to be used by connector developers. From what I've seen in the article you are commenting on, only Documentation.LongDescription is mentioned for custom connectors, so there's no need to explain what the Documentation.Description field does. If someone inadvertently uses Documentation.Description, there's no guarantee that this field will be supported in the future.

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
