### ISSUE TITLE
Import/Direct Query page is not shown for Dataverse as source

### ISSUE THREAD

**Issue by AnushaAnanthRao** [MicrosoftDocs/powerquery-docs#225]
This page doesn't seem to be valid on the Desktop Version: 2.102.845.0 64-bit (February 2022).

I am not getting an option to choose between the Import/Direct Query for Power BI with Dataverse as Source.
It is directly taking me to sign-in page without showing the page to select Import/Direct Query.
![image](https://user-images.githubusercontent.com/98304348/155691865-d093d0f6-9aeb-40fb-9fd2-c91924ea46fd.png)

Could you please clarify if this is option was available and has been removed? or if it is expected in the newer versions?

[Enter feedback here]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e182c32-ef1e-2092-9e8f-0643f991c17a
* Version Independent ID: 11d6812e-4d94-9024-72ad-a8ae7aa429a6
* Content: [Power Query Dataverse connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/dataverse)
* Content Source: [powerquery-docs/Connectors/Dataverse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Dataverse.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @AnushaAnanthRao 
Thanks for the feedback. The Dataverse article has been updated.
