### ISSUE TITLE
Microsoft Power Query UI Documentation is for Windows Only

### ISSUE THREAD

**Issue by ezs314159** [MicrosoftDocs/powerquery-docs#226]
This documentation is misleading.  It does not explain how to use Power Query on MacOS (where it is crippled and very much less useful than on windows).  The page should explain that it applies to Windows only.  It would also help if there was a link to documentation for MacOS.  It would help even more if there was an explanation of what functions of Power Query (Get & Transform) were supported for MacOS and which ones were missing (e.g.  Transform and Power Query Editor).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de794a3c-1a2b-ea25-a5ee-9f5e2486dc79
* Version Independent ID: d0ee45da-d64f-d594-bfa4-1b7f371646e3
* Content: [The Power Query user interface - Power Query](https://docs.microsoft.com/en-us/power-query/power-query-ui)
* Content Source: [powerquery-docs/power-query-ui.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-ui.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **dougklo**

**Comment by ptyx507x** [comment]
Thanks for the feedback, @ezs314159 !

Our goal with our docs site is to publish content that is product agnostic and let each product reflect the specific integrations and details of what experience from Power Query they have decided to enable. For Excel for Mac, you can find the documentation on the available experience in the link down below:
https://support.microsoft.com/en-us/office/import-data-in-excel-for-mac-power-query-7b2f337d-e7d2-4fdf-bf00-3dfbb1e5e9c5

Nevertheless, we absolutely value your feedback and will take it into consideration when doing the next update of this article and other articles taking into consideration the new developments happening in Excel for Mac related with Power Query.

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @ezs314159 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Some of the requested updates have been made since the creation of this issue. We continue will continue to make MacOS updates as resources become available. We are closing this issue for now, but feel free to comment here as necessary. #please-close
