### ISSUE TITLE
The try section does not have enough information

### ISSUE THREAD

**Issue by Domenyk** [MicrosoftDocs/powerquery-docs#227]
I would like some examples of how to use try to check text entered dates before I convert them.

At present I have text that will convert to a date using the column change data type.   Then I can replace the errors in this conversion with a null.  However I would like to trap the entered bad dates in a notes field so I have to try the conversion first when creating the notes field. 

My workaround without try is complex adding to the note any record with a duplicated text column before the conversion, to the a Text.from value  the converted date.  However if someone has used a valid date in another format that will show in the notes this way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fd77780-7917-bed1-edce-ad517e15986b
* Version Independent ID: 41ba55f3-de60-f2cd-4115-0754f271f81e
* Content: [Error handling for Power Query connectors - Power Query](https://docs.microsoft.com/en-us/power-query/handlingerrors)
* Content Source: [powerquery-docs/HandlingErrors.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/HandlingErrors.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **dougklo**

**Comment by ptyx507x** [comment]
Hey!

Let us know if this other article helps you for your case:
https://docs.microsoft.com/en-us/power-query/error-handling

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by JasonWHowell** [comment]
I'm closing this issue, hoping that the error handling article was helpful. If not, please reopen it as needed.
