### ISSUE TITLE
Not sure this is correct,  Needed to install Npgsql connection software

### ISSUE THREAD

**Issue by v-maquay** [MicrosoftDocs/powerquery-docs#228]
Prerequisites
As of the December 2019 release, NpgSQL 4.0.10 shipped with Power BI Desktop and no additional installation is required. GAC Installation overrides the version provided with Power BI Desktop, which will be the default. Refreshing is supported both through the cloud in the Power BI Service and also on premise through the Gateway. In the Power BI service, NpgSQL 4.0.10 will be used, while on premise refresh will use the local installation of NpgSQL, if available, and otherwise use NpgSQL 4.0.10.

I had to install this connection software to connect to Postgresql for machine running Power BI Desktop Feb 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f05c74-8262-6610-bd9e-efe4f112bbe1
* Version Independent ID: 09570cd3-3a8b-18c6-da4c-46beada3a387
* Content: [Power Query PostgreSQL connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/postgresql)
* Content Source: [powerquery-docs/Connectors/PostgreSQL.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/PostgreSQL.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Thanks @v-maquay  for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. However, this appears to be product feedback or a request for product support. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback). 

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
