### ISSUE TITLE
Synapse workspace auth types

### ISSUE THREAD

**Issue by mikem-MS** [MicrosoftDocs/powerquery-docs#229]
Service account is listed as an authentication type for this connector.  However, when using it there is no option for a service account.  The pattern should be documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Version Independent ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Content: [Power Query Azure Synapse Analytics workspace connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/synapse?source=docs#feedback)
* Content Source: [powerquery-docs/Connectors/Synapse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Synapse.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @mikem-MS 
Thanks for your feedback. Synapse workspace only accepts an organizational account, and the article has been updated to reflect this.
