### ISSUE TITLE
Documenting a function which takes an Uri.Type

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/powerquery-docs#23]
I'm trying to document a function which takes an Uri.

Normally, you'd use something like
```
shared MyConnector.Contents = Value.ReplaceType(MyConnector.Contents, type function (url as Uri.Type) as any);
```
to ascribe the type and get special handling of functions taking URIs from PowerBI.

But when I try to do
```
shared MyConnector.Contents = Value.ReplaceType(MyConnector.Contents, MyConnector.DocumentedFunction);
MyConnector.DocumentedFunction = type function (
    url as (type Uri.Type meta [
        Documentation.FieldCaption = "API endpoint",
        Documentation.FieldDescription = "The location of the API used to retrieve data")",
        Documentation.SampleValues = { "https://example.com/api/measures.json" }
    ]))
    as table;
```

I get syntax errors. If I try to use `url as (Uri.Type meta [` (without the `type`) it works, but I lose PowerBI's special handling of functions taking URIs.

What should I do to keep the special handling of functions taking URIs and document my connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a834875-02f7-683d-5845-618a5d02d888
* Version Independent ID: 36b3e58d-e580-a9fd-4239-7d51b24fdeb6
* Content: [Adding function documentation](https://docs.microsoft.com/en-us/power-query/handlingdocumentation)
* Content Source: [powerquery-docs/HandlingDocumentation.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/HandlingDocumentation.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by NGromann** [comment]
You need to replace `type Uri.Type meta [...]` to `Uri.Type meta [...]`

```
fnType = Type.ForFunction([
    Parameters = [
        server = Uri.Type meta [
            Documentation.FieldCaption = Extension.LoadString("ConnectionFormServerParameterCaption"),
            Documentation.SampleValues = {Extension.LoadString("ConnectionFormServerSampleValues")}
        ]
    ],
    ReturnType = type table
], 1),
```

**Comment by sylveon** [comment]
Thats's something I've tried, as I wrote here:
> If I try to use `url as (Uri.Type meta [` (without the `type`) it works, but I lose PowerBI's special handling of functions taking URIs.

Or does `Type.ForFunction` not have this issue?

**Comment by NGromann** [comment]
I tried it similar to your upper example and this one is working for me:

```
shared MyConnector.Contents = Value.ReplaceType(MyConnector.Connect, MyConnector.DocumentedFunction);
MyConnector.DocumentedFunction = type function (
    url as (Uri.Type meta [
        Documentation.FieldCaption = "API endpoint",
        Documentation.FieldDescription = "The location of the API used to retrieve data",
        Documentation.SampleValues = { "https://example.com/api/measures.json" }
    ]))
    as table;

shared MyConnector.Connect = (server) as table => ...
```

 Note that in this line 
```
shared MyConnector.Contents = Value.ReplaceType(MyConnector.Connect, 
```
The first argument is not referencing itself anymore (`MyConnector.Connect` instead of `MyConnector.Contents`).

**Comment by sylveon** [comment]
It works but we lose the special handling for credential storage as described [here](https://docs.microsoft.com/en-us/power-query/handlingresourcepath#functions-with-a-uri-parameter).

**Comment by sylveon** [comment]
Bump

**Comment by cpopell** [comment]
Please note in the sample you linked the function is GithubSample.Contents and then the first argument is Github.Contents.

**Comment by sylveon** [comment]
Yes, that was just a mistake when I sent a minimum repro here... The original issue applies to my code, which doesn't have that mistake

**Comment by sylveon** [comment]
Looks like I was mislead here. I forgot PowerBI saved my credentials so was thinking it called the API credential-less (which is possible with the API I'm interacting with). Wiping the saved credentials makes it behave as expected (ask the credentials when adding the connection)
