### ISSUE TITLE
Question about WebView2, PBI and Salesforce

### ISSUE THREAD

**Issue by cleschack** [MicrosoftDocs/powerquery-docs#230]
Can you please provide an example of how to make sure that Salesforce Reports and Salesforce Objects will be forced not to use Webview2?  We have Okta in the backend doing authentication and through Power BI, after the Okta splash page, it freezes when clicking on PIV/CAC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d59f5124-28ba-3688-aa97-7061c8ecd750
* Version Independent ID: 8e58b489-ad6c-22c0-765a-2e27630bd7f4
* Content: [Enabling Microsoft Edge (Chromium) for OAuth authentication in Power BI Desktop - Power Query](https://docs.microsoft.com/en-us/power-query/oauth-edge-chromium)
* Content Source: [powerquery-docs/oauth-edge-chromium.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/oauth-edge-chromium.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **dougklo**

**Comment by DougKlopfenstein** [comment]
Hi @cleschack 
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
