### ISSUE TITLE
Suggest alternative approaches to get Graph data

### ISSUE THREAD

**Issue by wiweb** [MicrosoftDocs/powerquery-docs#231]
This article is very helpful in explaining why we can't query Graph from Power Query. However it doesn't provide any options for solving the problem. It would be helpful to suggest at least one alternative approach to get this data into Power Query. Using Power Automate/Logic Apps to write Graph data to another data source, or something like that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd778de-88e0-7de1-dac1-32db460ec158
* Version Independent ID: 4b608698-3cc3-1c10-7cd2-843ebe8bc131
* Content: [Lack of Support for Microsoft Graph in Power Query - Power Query](https://docs.microsoft.com/en-us/power-query/connecting-to-graph)
* Content Source: [powerquery-docs/connecting-to-graph.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connecting-to-graph.md)
* Service: **powerquery**
* GitHub Login: @mattmasson
* Microsoft Alias: **mmasson**

**Comment by mattmasson** [comment]
The article does suggest the use of Microsoft Graph Data Connect as an alternative - I believe it's what the Graph team recommends when running BI/Analytics scale workloads off Graph data.

https://docs.microsoft.com/en-us/graph/overview#access-microsoft-graph-data-at-scale-using-microsoft-graph-data-connect

**Comment by rootsmusic** [comment]
@wiweb Power Apps, Logic Apps and Power Automate still has a [connector for Graph Security](https://docs.microsoft.com/en-us/connectors/microsoftgraphsecurity/).
