### ISSUE TITLE
Power BI custom extension change from .mez to .pqx

### ISSUE THREAD

**Issue by DrewGei** [MicrosoftDocs/powerquery-docs#235]
Should add a comment about the extension change from .mez to .pqx as mentioned [here ](https://docs.microsoft.com/en-us/power-query/installingsdk#query-file)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea5ab12-0b6e-20b5-1659-d872db778b6d
* Version Independent ID: d642b0fd-460c-c8aa-922a-28569d7cf986
* Content: [TripPin 1 - OData - Power Query](https://docs.microsoft.com/en-us/power-query/samples/trippin/1-odata/readme)
* Content Source: [powerquery-docs/samples/TripPin/1-OData/README.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/samples/TripPin/1-OData/README.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Thanks @DrewGei for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
