### ISSUE TITLE
including joining on multiple columns

### ISSUE THREAD

**Issue by Jorellus** [MicrosoftDocs/powerquery-docs#236]
[Enter feedback here]
Could be nice to explicitly include the fact that you can join on multiple columns using ctrl + click.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b423ec9-b5ae-5cc4-90dc-9f2f272229f2
* Version Independent ID: a9af2218-897f-4a31-9b04-131ff3a6774b
* Content: [Full outer join - Power Query](https://docs.microsoft.com/en-us/power-query/merge-queries-full-outer)
* Content Source: [powerquery-docs/merge-queries-full-outer.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/merge-queries-full-outer.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @Jorellus 
Thanks for the feedback! The information about selecting multiple columns has been added to the article.
