### ISSUE TITLE
Usage of data type conversion matrix unclear

### ISSUE THREAD

**Issue by jacklinke** [MicrosoftDocs/powerquery-docs#237]
It is clear from viewing the matrix that '*conversion friendliness*' is asymmetrical - meaning converting from A to B does not necessarily have the same value of friendliness as converting from B to A. Unfortunately, whoever designed this visual did not denote whether we are converting from column value to row value or vice versa.

For instance, one combination of conversions between Decimal numbers and Currency results in a yellow exclamation, while the other results in a green check.

But which direction are we converting from/to? It's ambiguous. Without this information, the tool is unusable for any of the many asymmetrical relationships.

This matrix has been shared via social media a lot lately, and will likely induce some confusion in beginners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b014c6-8d41-9f48-4c08-ae0579109734
* Version Independent ID: 6bc72e07-856e-18f2-119b-94e3ede0f213
* Content: [Data types in Power Query - Power Query](https://docs.microsoft.com/en-us/power-query/data-types)
* Content Source: [powerquery-docs/data-types.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/data-types.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @jacklinke 
Thanks for the feedback! The conversion information has been added in a note before the table.
