### ISSUE TITLE
Out-of-date

### ISSUE THREAD

**Issue by matt40k** [MicrosoftDocs/powerquery-docs#24]
The screenshots are out of date and doesn't include Account Key for authentication. We now also have the extra options around Data Views - either File System View or CDM Folder View

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de89bef7-dbd7-c901-d329-f9838f8dbaf9
* Version Independent ID: 583cc4ae-3fdb-0d6c-6314-8aaf8e51e922
* Content: [Analyze data in Azure Data Lake Storage Gen2 by using Power BI](https://docs.microsoft.com/en-us/power-query/connectors/datalakestorage#feedback)
* Content Source: [powerquery-docs/Connectors/DataLakeStorage.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/DataLakeStorage.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
@matt40k This issue has been fixed.
