### ISSUE TITLE
Impact of "AppId Uri require use of verified domains"

### ISSUE THREAD

**Issue by DeChrist** [MicrosoftDocs/powerquery-docs#242]
The documentation page states:

> Power Query can then initiate the OAuth flow against the authorization Uri. Power Query requests an Azure AD Resource or Audience value equal to the domain of the URL being requested. This value would be the value you use for your Azure Application ID URL value in your API/service registration. For example, if accessing https://api.myservice.com/path/to/data/api, Power Query would expect your Application ID URL value to be equal to https://api.myservice.com.

However, in October 2021, this Azure AD breaking change has been deployed, that has an impact on the documented use case:
[AppId Uri in single tenant applications will require use of default scheme or verified domains](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#appid-uri-in-single-tenant-applications-will-require-use-of-default-scheme-or-verified-domains)

The documented setup is hence now incomplete and, it is not clear if, after registering the URL, the use case will be operational.

Therefore, the documentation should be adapted to reflect the impact of this change into account, either by:
- documenting that this use case is no longer available (possibly providing alternatives)
- adapting the documentation to clarify the additional steps now required to keep the use case operational

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bae8544-11ae-3d75-3466-141bd22e900d
* Version Independent ID: dededa48-e69d-92f8-2932-be3a708cdabb
* Content: [Authentication with a data source - Power Query](https://docs.microsoft.com/en-us/power-query/connectorauthentication#connecting-with-azure-active-directory-using-the-web-and-odata-connectors)
* Content Source: [powerquery-docs/ConnectorAuthentication.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/ConnectorAuthentication.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @DeChrist 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
