### ISSUE TITLE
Language Specification - Document Type Claims Feature

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#243]
In M, a type value can have an associated claim (sometimes called a subtype). For example, the standard library's `Int64.Type` returns a type value of `type number` with an "Int64.Type" type claim.

Type claims are not described in the language specification. For completeness's sake, would you consider adding a mention of them there?

Thank you for your consideration!

---
Rough draft of one possible language spec. amendment:

> A type value may have a _type claim_ associated with it. This informational notation provide a means to communicate a more refined level of detail about what the particular type value claims to represent. 
>
> The language does not provide a mechanism create type claims using M code. Instead, typically, the standard library provides a predefined set of type values with associated claims which M expressions may reference.
> ````
> Int64.Type // Int64.Type is a type number value with an “Int64.Type” claim
> Value.ReplaceType(123, Int64.Type) // 123 is now of type number with an “Int64.Type” claim 
>````
> Type claims are strictly claims. They are unenforced by the mashup engine, have no effect on mashup engine behavior and are ignored by operators. 
>
>````
> Value.ReplaceType(123.456, Int64.Type) // 123.456 is clearly not an integer; however, since type claims are not validated by the mashup engine, this ascription is accepted without complaint
>````
>
> However, other M code, as well as the application that receives the mashup’s output, may read and take action based on these claims. For example, if a type number with an “Int64.Type” claim is received by the host application, it could choose to use the “Int64.Type” type claim when determining how to store associated values in the application’s database and error if an associated value does not comply with the claim.
>

**Comment by bgribaudo** [comment]
As an aside, it would be really nice to have a standard library function for directly getting a type's claim. Maybe something like `Type.Claim = (type as type) as text) => ...`?

This would be much simpler to use than the code that's currently required to get the claim--which is something like:
````
(input as type) as text => Table.SingleRow(Table.Schema(#table(type table [Col1 = input], {})))[TypeName]
````

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @bgribaudo 
Hi @bgribaudo
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Because this issue has been open for more than two years, we are closing this issue for now. However, if you feel that this issue should be addressed in the documentation, you can always open a pull request in the powerquery-docs repo.

**Comment by DougKlopfenstein** [comment]
#please-close
