### ISSUE TITLE
Moving Power BI Columns

### ISSUE THREAD

**Issue by LimKaamen** [MicrosoftDocs/powerquery-docs#244]
The instructions for moving Power BI columns do not work with the current version of Power BI Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd156d86-a695-872c-1823-0d9181cf67cf
* Version Independent ID: 50ea6b24-9d9d-2bef-baae-361263c514be
* Content: [Move columns - Power Query](https://docs.microsoft.com/en-us/power-query/move-columns)
* Content Source: [powerquery-docs/move-columns.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/move-columns.md)
* Service: **powerquery**
* GitHub Login: @jessli20
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @LimKaamen 
Could you be more specific about what doesn't work? I tested moving columns with the April 2022 version of Power BI and was able to successfully move columns by using the Move option in the column dropdown and by dragging and dropping.

**Comment by DougKlopfenstein** [comment]
Closed due to lack of customer input.
