### ISSUE TITLE
Images need to be updated

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerquery-docs#246]
Hi - the images need to be updated. The computed entities now show a yellow lightening symbol instead of black. A colleague was looking for info but said couldn't find it because he didn't see the updated images. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 016cc5b0-e90e-c87e-874f-d71cc5d740b8
* Version Independent ID: 486eeb0a-d69d-3a9a-f17d-10482de0dcf2
* Content: [Computed entity scenarios and use cases - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/computed-entities-scenarios)
* Content Source: [powerquery-docs/dataflows/computed-entities-scenarios.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/computed-entities-scenarios.md)
* Service: **powerquery**
* GitHub Login: @radacad
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add tags). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @pawarbi 
All of the images you specified needing updates have been updated along with all mentions of computed entities being updated to computed tables throughout the Power Query documentation.
