### ISSUE TITLE
Table.TransformColumns - Missing description of 3rd transformation config param

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#247]
Hello,

The docs for [`Table.TransformColumns`](https://docs.microsoft.com/en-us/powerquery-m/table-transformcolumns) describe parameter `transformOptions` as having the format "{ column name, transformation }". No mention is made that the transformation spec list is allowed to have an optional third item that specifies the type output by the transformation -- e.g. "{ column name, transformation, type }".

Could this page be updated to reflect this optional third item?

Thank you!

----
Example of providing this additional config param item:
````
let
    Data = #table({"X"}, {{123}}),
    // with optional third item *not* provided
    // Transformed = Table.TransformColumns(Data,  {"X", each _ * 2})
    // with optional third item provided - notice how providing this results in the column's icon and formatting changing in Query Editor
    Transformed = Table.TransformColumns(Data,  {"X", each _ * 2, Currency.Type})    
in
    Transformed
````

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add tags). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @bgribaudo 
Thanks for the input. The Table.TransformColumns article has been updated with new examples, the fourth of which contains the third optional item.

**Comment by bgribaudo** [comment]
Thank you, @DougKlopfenstein!
