### ISSUE TITLE
Suggestion of an additional benefit offered by Power query

### ISSUE THREAD

**Issue by Josh-BI-UK** [MicrosoftDocs/powerquery-docs#248]
[In the paragraph entitled "How Power Query helps with data acquisition" https://docs.microsoft.com/en-us/power-query/power-query-what-is-power-query#how-power-query-helps-with-data-acquisition, it would be helpful to add the benefit of "Delivery (or Sharing) of the cleaned, shaped processed data.". I think this would further enhance this section.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9b1e7c-616b-87e0-7858-7f9e83b69ea5
* Version Independent ID: 5ffba9ae-ac08-3375-df06-507e7b6336f3
* Content: [What is Power Query? - Power Query](https://docs.microsoft.com/en-us/power-query/power-query-what-is-power-query?source=docs)
* Content Source: [powerquery-docs/power-query-what-is-power-query.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-what-is-power-query.md)
* Service: **powerquery**
* GitHub Login: @mllopis
* Microsoft Alias: **millopis**

**Comment by ptyx507x** [comment]
Great suggestion @Josh-BI-UK !

While Power Query is the tool that helps you create queries that shape your data, [Dataflows](https://docs.microsoft.com/power-query/dataflows/overview-dataflows-across-power-platform-dynamics-365) is the component that lets you load the output of your queries into the destination of your choice and then consume such data using your tool of choice.

Perhaps we need another matrix like the one from the "What is Power Query?" article in the Dataflows article.

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add tags). #please-open

**Comment by DougKlopfenstein** [comment]
Thanks @Josh-BI-UK for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
