### ISSUE TITLE
Historical

### ISSUE THREAD

**Issue by ptacquet** [MicrosoftDocs/powerquery-docs#250]
Hi, 

For builing a dwh, a regullar is task is to store into historical tables from daily files.
How do you do this with a dataflow storage ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9b25778-3fbc-c602-b6dd-73b34a717af6
* Version Independent ID: 3fce6eb2-1a42-85ef-4574-733b09c999e2
* Content: [Best practices for creating a dimensional model using dataflows - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/best-practices-for-dimensional-model-using-dataflows)
* Content Source: [powerquery-docs/dataflows/best-practices-for-dimensional-model-using-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/best-practices-for-dimensional-model-using-dataflows.md)
* Service: **powerquery**
* GitHub Login: @radacad
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @ptacquet 
Thanks for your feedback. This appears to be a customer support issue rather than a documentation issue. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
