### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by kokkulaumakanth** [MicrosoftDocs/powerquery-docs#251]
[Enter feedback here]

Hi Team,

I would like to correct a spelling mistake here. "Zoho Creater"  is mentioned instead of "Zoho Creator".
Request to change it. Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72df40f2-3c58-cbda-79ec-c65ba5cc32ac
* Version Independent ID: ab483b41-107f-2027-c65f-63285a847c63
* Content: [List of all Power Query connectors - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/)
* Content Source: [powerquery-docs/Connectors/index.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/index.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @kokkulaumakanth 
Thanks for your feedback. The spelling has been corrected.
