### ISSUE TITLE
Dataflow Add Data to Dataverse • "All Data In That Table Will Be Overwritten"

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/powerquery-docs#253]
> Warning
> 
> If you use Power Query to add data to an existing table, all data in that table will be overwritten.

This sentence needs more context. As written I would never use the Dataflows feature.

I read the warning literally as "the entire table is dropped and replaced by the Dataflow". I *think* it's trying to say that based on the Primary key of the Dataflow, all records and columns mapped from the dataflow will upsert the table.

Also, in the screenshot there's a "Delete rows that no longer exist in the query output". Would be great if that was documented too, as it probably would add additional clarification to the warning message.

Thanks,

Joel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12795c71-e2fa-4ad0-abca-95fe5c5c5c75
* Version Independent ID: 9b7d14ce-f391-db56-c68d-e508fca06e0d
* Content: [Add data to a table in Microsoft Dataverse by using Power Query - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/add-data-power-query)
* Content Source: [powerquery-docs/dataflows/add-data-power-query.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/add-data-power-query.md)
* Service: **powerquery**
* GitHub Login: @mllopis
* Microsoft Alias: **millopis**

**Comment by DougKlopfenstein** [comment]
Hi @JoelLeichty 
Thanks for the feedback. the warning has been clarified with more context.
