### ISSUE TITLE
Dataverse connection in Customer Insights

### ISSUE THREAD

**Issue by saviegas** [MicrosoftDocs/powerquery-docs#254]
When we use the Power Plattform Dataverse Connector in Customer Insights we do see different Advanced Options: Include relationship columns.
Can this be added to the documentation to better guide customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e182c32-ef1e-2092-9e8f-0643f991c17a
* Version Independent ID: 11d6812e-4d94-9024-72ad-a8ae7aa429a6
* Content: [Power Query Dataverse connector - Power Query](https://review.docs.microsoft.com/en-us/power-query/connectors/dataverse?source=docs)
* Content Source: [powerquery-docs/Connectors/Dataverse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Dataverse.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add tags). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @saviegas 
Thanks for the feedback! Information about the advanced options in the Dataverse connector has been added to the article.
