### ISSUE TITLE
API Pagination in JSON Body (not Headers) - How to Access  in Custom Connector?

### ISSUE THREAD

**Issue by rrredirect** [MicrosoftDocs/powerquery-docs#255]
Hello,

 

I have built a customer connector to connect to the Vimeo API via OAuth2. Everything is working well, but it appears I need to come up with a solution to deal with pagination, as I am only getting back 25 items on each page.

 
I see the documentation on how to use Table.GenerateByPage  and getNextPage here:

[https://docs.microsoft.com/en-us/power-query/samples/trippin/5-paging/readme#tablegeneratebypage](https://docs.microsoft.com/en-us/power-query/samples/trippin/5-paging/readme#tablegeneratebypage)

As well as the implementation within the example GitHub custom connector

[https://github.com/microsoft/DataConnectors/blob/master/samples/Github/github.pq](https://github.com/microsoft/DataConnectors/blob/master/samples/Github/github.pq)

A sample of functions from that example:

 
```
Github.Contents = (url as text) =>
    let
        content = Web.Contents(url),
        link = GetNextLink(content),
        json = Json.Document(content),
        table = Table.FromList(json, Splitter.SplitByNothing())
    in
        table meta [Next=link];

Github.PagedTable = (url as text) => Table.GenerateByPage((previous) =>
    let
        // If we have a previous page, get its Next link from metadata on the page.
        next = if (previous <> null) then Value.Metadata(previous)[Next] else null,
        // If we have a next link, use it, otherwise use the original URL that was passed in.
        urlToUse = if (next <> null) then next else url,
        // If we have a previous page, but don't have a next link, then we're done paging.
        // Otherwise retrieve the next page.
        current = if (previous <> null and next = null) then null else Github.Contents(urlToUse),
        // If we got data back from the current page, get the link for the next page
        link = if (current <> null) then Value.Metadata(current)[Next] else null
    in
        current meta [Next=link]);


GetNextLink = (response, optional request) =>
    let
        // extract the "Link" header if it exists
        link = Value.Metadata(response)[Headers][#"Link"]?,
        links = Text.Split(link, ","),
        splitLinks = List.Transform(links, each Text.Split(Text.Trim(_), ";")),
        next = List.Select(splitLinks, each Text.Trim(_{1}) = "rel=""next"""),
        first = List.First(next),
        removedBrackets = Text.Range(first{0}, 1, Text.Length(first{0}) - 2)
    in
        try removedBrackets otherwise null;
 
```
 

However, my issue is that the metadata on pagination that returns from the Vimeo API is coming through the JSON body response instead of within the headers, as is assumed in the documentation and examples. Is there an easy way or helper function within Power Query/M that would allow me to look into the body of the JSON response, grab the pagination JSON objects (as below), and built out my code from there?

 

Here is what comes back regarding pagination from Vimeo's API within the JSON body:

 

 

    "total": 1012,
    "page": 1,
    "per_page": 25,
    "paging": {
        "next": "/users/{our-user-id}/videos?page=2",
        "previous": null,
        "first": "/users/{our-user-id}/videos?page=1",
        "last": "/users/{our-user-id}/videos?page=41"
    },
 

 

Many thanks for any help - it is very much appreciated!

Best,

-Josh

**Comment by DougKlopfenstein** [comment]
Hi @rrredirect 
Thanks for the feedback. This appears to be a customer support issue rather than a documentation issue. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
