### ISSUE TITLE
Adding second parameter to URL parameter fails

### ISSUE THREAD

**Issue by zebrassimo** [MicrosoftDocs/powerquery-docs#26]
Hi all,

While developing a custom connector, I'm trying to add another parameter besides the url as Uri.Type. Didn't find any documentation on this (expected [here](https://github.com/microsoft/DataConnectors/blob/master/docs/m-extensions.md#data-source-paths)) and tried myself. After enabling logging, I find this error message:

`DataMashup.Trace Information: 24579 : {"Start":"2020-05-11T12:04:05.4712959Z","Action":"UiExtensionHost/DynamicExtensionLoading/Unload","Service":[],"ProductVersion":"2.80.5803.1061 (20.04)","ActivityId":"00000000-0000-0000-0000-000000000000","Process":"PBIDesktop","Pid":14680,"Tid":1,"Duration":"00:00:00.0000783"}
`

This is how the connector starts:

[DataSource.Kind="Service ", Publish="Service .Publish"]
shared Jira.Contents = Value.ReplaceType(Service NavTable, Service Type);

[...]

**This works**
`ServiceType = type function (
    url as (Uri.Type meta[
        Documentation.FieldCaption = Extension.LoadString("ServiceServerURLCaption"),
        Documentation.FieldDescription = Extension.LoadString("ServiceServerURLDescription"),
        Documentation.SampleValues = {"http://www.contoso.com"}
    ]))
        as table meta [
            Documentation.Name = Extension.LoadString("Service"),
            Documentation.LongDescription = Extension.LoadString("Service management system")
        ];
`

**This doesn't work:**
`ServiceType = type function (
    url as (Uri.Type meta[
        Documentation.FieldCaption = Extension.LoadString("ServiceServerURLCaption"),
        Documentation.FieldDescription = Extension.LoadString("ServiceServerURLDescription"),
        Documentation.SampleValues = {"http://www.contoso.com"}
    ]),
    filter as (Text.Type meta[
        IsParameterQuery=true, Type="Text", 
        IsParameterQueryRequired=true,
        Documentation.FieldCaption = Extension.LoadString("ServiceQueryCaption"),
        Documentation.FieldDescription = Extension.LoadString("ServiceQueryDescription"),
        Documentation.SampleValues = {"08154711"}
    ]))
        as table meta [
            Documentation.Name = Extension.LoadString("Service"),
            Documentation.LongDescription = Extension.LoadString("Service management system")
        ];
`
The logging doesn't provide any indication on why UiExtensionHost/DynamicExtensionLoading/Unload occurs.

**This would be awesome**
The secondary parameter would ideally be filled as a dropdown on a secondary page based on the url parameter. Can you guide me to to a resource for this?

Thanks and greets!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea5ab12-0b6e-20b5-1659-d872db778b6d
* Version Independent ID: d642b0fd-460c-c8aa-922a-28569d7cf986
* Content: [TripPin 1 - OData](https://docs.microsoft.com/en-us/power-query/samples/trippin/1-odata/readme)
* Content Source: [powerquery-docs/samples/TripPin/1-OData/README.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/samples/TripPin/1-OData/README.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @zebrassimo -

This appears to be a customer support issue rather than a documentation issue. For any kind of customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
