### ISSUE TITLE
Sharepoint folder - Power Query Authentication issue

### ISSUE THREAD

**Issue by andymcw** [MicrosoftDocs/powerquery-docs#260]
Hi,

Your article indicates that I should be able to do what I want, which is to specify the contents of a Sharepoint Folder as a source for a Power Query. I have followed your steps as best I can but keep running into an authentication issue.

My Excel interface is slightly different from yours, but I start with **Get Data - From Web**, (no Sharepoint specific option).
I paste my Sharepoint URL into the address box. My Sharepoint address is of the form https://<site-name>.sharepoint.com/sites/FinanceRecords31/Shared Documents/General/Time Journal Engine/Current TS
I don't believe that contains any invalid characters. I have entered a specific pathname, rather than one higher up the tree, to reduce the number of items the PQ tries to load.

I have several different organisational MS365 accounts on my desktop, but am only signed in to the one corresponding to this sharepoint site. In Data Source Settings / Global Permissions I have credentials set to Organisational Account. But quite often the system is forgetting the Organisation Account setting, and also telling me I'm not signed in (when I am).

When I try to Connect is just get the message 'We couldn't authenticate with the credentials provided. Please try again.'

In the same project I am reliably accessing specific files within the same folder using 

    Source = Excel.Workbook(Web.Contents("https://<site-name>.sharepoint.com/sites/FinanceRecords31/Shared%20Documents/General/Time%20Journal%20Engine/Current%20TS/AB-TS.xlsx"), null, true),

I see this has the invalid character % automatically inserted several times. Yet this works.

It would be great if you could help me resolve this.

Thanks,

Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7fa007-53f0-1fa5-bbff-b59fe142c804
* Version Independent ID: acb9ddd9-08ea-79ea-3537-cf8bda64282b
* Content: [Power Query SharePoint folder connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/sharepointfolder)
* Content Source: [powerquery-docs/Connectors/SharePointFolder.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointFolder.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @andymcw 
This appears to be a customer support issue rather than a documentation issue. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
