### ISSUE TITLE
Power Apps Plan 2

### ISSUE THREAD

**Issue by olasandness** [MicrosoftDocs/powerquery-docs#266]
This document claims that you need Power Apps Plan 2 to use incremental refresh. However, Power Apps Plan 2 is no longer available. What current Power App license is required to use incremental refresh?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc816e2-78f6-ca70-92a3-b2153461759d
* Version Independent ID: e6fec9a8-1c47-b739-5146-0fa717c4535e
* Content: [Using incremental refresh with dataflows - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/incremental-refresh)
* Content Source: [powerquery-docs/dataflows/incremental-refresh.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/incremental-refresh.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add tags). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @olasandness 
Thanks very much for your feedback. The article has been updated to reflect the current Power App license information.
