### ISSUE TITLE
SQL Server Connector Prerequisites is incorrect

### ISSUE THREAD

**Issue by dbrownems** [MicrosoftDocs/powerquery-docs#268]
The SQL Server connector uses Microsoft.Data.SqlClient, which has no dependency on the old NativeClient or any OleDb or ODBC driver.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e77b6456-8d48-b1fc-cba3-993d1f8d5cae
* Version Independent ID: 0ca84a81-e16e-a2f7-1cac-00082cf0d86b
* Content: [Power Query SQL Server connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/sqlserver#feedback)
* Content Source: [powerquery-docs/Connectors/SQLServer.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SQLServer.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
Please ignore: I'm closing and opening this issue to get automation to add tags. #please-open

**Comment by DougKlopfenstein** [comment]
Hi @dbrownems 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. 

However, we have updated the connector article by removing the obsolete prerequisite. #please-close
