### ISSUE TITLE
Need sample documentation on how to implement refresh and logout

### ISSUE THREAD

**Issue by syendev** [MicrosoftDocs/powerquery-docs#269]
request is the power query documentation, for the area of "Create custom Power Query connectors" does not contain any samples for how to use the refresh token that is available for the current authenticated user.

The topic is mentioned in:
[(Docs / Power Query / Power Query documentation / Concepts)](https://docs.microsoft.com/en-us/power-query/handlingauthentication)

See table: OAuth fields Refresh, Logout both marked optional. Implementing an OAuth Flow section below only presents the signatures for these functions.

The [Github sample](https://docs.microsoft.com/en-us/power-query/samples/github/readme) only covers StartLogin and FinishLogin functions.

Let me know if this explains the request.

Thanks,
S.

this request is duplicate of issue #249 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58e66f41-e084-8f8a-8828-12474f21f0d7
* Version Independent ID: 77eafe80-5569-eee6-042e-e425a9056570
* Content: [Handling authentication for Power Query connectors - Power Query](https://docs.microsoft.com/en-us/power-query/handlingauthentication)
* Content Source: [powerquery-docs/HandlingAuthentication.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/HandlingAuthentication.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
Please ignore: I'm closing and opening this issue to get automation to add tags. #please-close

**Comment by JasonWHowell** [comment]
#please-open

**Comment by syendev** [comment]
@JasonWHowell thanks.

**Comment by simon-r-watson** [comment]
@syendev Did you end up getting this worked out? I'm having a similar issue with implementing this

**Comment by DougKlopfenstein** [comment]
Thanks @syendev for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
