### ISSUE TITLE
Help page isn't very useful

### ISSUE THREAD

**Issue by jbruneFei** [MicrosoftDocs/powerquery-docs#272]
I'm getting the error "An error happened while reading data from the provider: 'The remote certificate is invalid according to the validation procedure.'"  Seems like there are a more steps that need to be carried out.  https://www.tradefinanceglobal.com/posts/connecting-powerbi-web-to-postgressql-hosted-on-aws-relational-database-service-rds/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f05c74-8262-6610-bd9e-efe4f112bbe1
* Version Independent ID: 09570cd3-3a8b-18c6-da4c-46beada3a387
* Content: [Power Query PostgreSQL connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/postgresql)
* Content Source: [powerquery-docs/Connectors/PostgreSQL.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/PostgreSQL.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
Please ignore: I'm closing and opening this issue to get automation to add tags. #please-close

**Comment by JasonWHowell** [comment]
#please-open

**Comment by DougKlopfenstein** [comment]
Thanks @jbruneFei for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. However, this appears to be product feedback or a request for product support. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback). 

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
