### ISSUE TITLE
Add license note to helper functions page?

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#277]
Would it make sense to add a note about licensing to the helper functions page?

Some of the helpers are included in Microsoft-owned projects on GitHub that are MIT licensed, so maybe that is the correct licensing for these helpers as a whole. If so, could a note be added on this page indicating such?

Or--better yet--since these functions tend to be on the small side, maybe the licensing statement could simply be "these functions may be freely used, modified and redistributed." This would avoid the need for a copy of the MIT license to travel with each connector that uses them.

Just an idea. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63706099-f414-4f48-165d-a3609437a37e
* Version Independent ID: 1807dacc-1bf2-79aa-70b1-bebd2f2c6331
* Content: [Helper functions for M extensions for Power Query connectors - Power Query](https://docs.microsoft.com/en-us/power-query/helperfunctions)
* Content Source: [powerquery-docs/HelperFunctions.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/HelperFunctions.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
Please ignore: I'm closing and opening this issue to get automation to add tags. #please-close

**Comment by JasonWHowell** [comment]
#please-open

**Comment by DougKlopfenstein** [comment]
Thanks @bgribaudo for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
