### ISSUE TITLE
What does "authoring" mean in this context?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerquery-docs#291]
Can you please clarify what "authoring" mean? When is that timeout applied exactly? Are we talking about the preview phase while authoring a query and/or the overall evaluation phase (the popup with checkmarks) when a dataflow is being saved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3faffe45-9b88-7ca0-4fb9-1eaac7859baa
* Version Independent ID: 1781cb1b-0976-62e1-3060-7e3fdcd96225
* Content: [Power Query Online Usage Limits - Power Query](https://docs.microsoft.com/en-us/power-query/power-query-online-limits)
* Content Source: [powerquery-docs/power-query-online-limits.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-online-limits.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
Please ignore: I'm closing and opening this issue to get automation to add tags. #please-close

**Comment by JasonWHowell** [comment]
#please-open

**Comment by DougKlopfenstein** [comment]
Hi @otravers 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. 

However, the article has been updated with new information that more fully defines what is meant by authoring. 

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
