### ISSUE TITLE
This doesn't make sense, it just goes in a loop to refresh the dataflow, once the dataflow refreshes???

### ISSUE THREAD

**Issue by TIM-ME** [MicrosoftDocs/powerquery-docs#299]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53048912-9c2a-1cae-4e9a-02cf79307e3c
* Version Independent ID: d21f1dab-c67e-2100-f11a-82d3ba6fda9b
* Content: [Trigger dataflows and Power BI datasets sequentially - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially)
* Content Source: [powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
#assign:miquelladeboer in case you have a quick opinion

**Comment by JasonWHowell** [comment]
#assign:@miquelladeboer

**Comment by DougKlopfenstein** [comment]
Hi @TIM-ME 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We've mad some minor changes to the article to indicate that the refresh of the initial analytical dataflow will be used to trigger the refresh of a standard dataflow.

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
