### ISSUE TITLE
SupportsStringLiterals not recognised

### ISSUE THREAD

**Issue by rymurr** [MicrosoftDocs/powerquery-docs#3]
When I set SupportsStringLiterals to true in SqlCapabilities:

Source = Odbc.DataSource("Provider=MSDASQL.1;DSN=foo", [ HierarchicalNavigation=true,
                        SqlCapabilities=[SupportsStringLiterals = true]
                    ]),

I get an Expression.Error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3601125c-b8cc-1d6d-df32-098d43ecfadc
* Version Independent ID: 7cd229d3-3d6a-bcbe-c44a-f6f92761f38c
* Content: [Enabling DirectQuery for an ODBC-based Power Query connector](https://docs.microsoft.com/en-us/power-query/odbc#feedback)
* Content Source: [powerquery-docs/odbc.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/odbc.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by mattmasson** [comment]
@rymurr , The code looks right (see the [SqlODBC sample](https://github.com/microsoft/DataConnectors/blob/master/samples/ODBC/SqlODBC/SqlODBC.pq)). Note this is something that would only work from inside of a custom connector, and not in a regular M query. Is that what you're doing here? And are you sure that this is the line that is causing an error?

**Comment by rymurr** [comment]
Hey @mattmasson it was indeed from a regular M query. That was the only option that wasn't working. Will follow your guides for a custom connector and try again. Thanks!

**Comment by rymurr** [comment]
@mattmasson I successfully built the custom connector and have a mez file however its not clear to me how to load this into excel. Am I missing something obvious? My end goal is to leverage the M language to make Power Query in excel push SQL to my database
