### ISSUE TITLE
Language Grammar - generalized-identifier Syntax

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#30]
Hello,

If I'm understanding the language specification correctly, a [`generalized-identifier` ](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#identifiers)that starts with a decimal digit must be followed with a letter or underscore. However, both Power BI and Excel do not enforce the "must be followed by" rule--they both allow a single decimal digit to be used by itself:

````
[9 = true][9]
````

To align the specification with this behavior, would it make sense to update the spec by adding (opt) as noted below:
````
generalized-identifier-part:
      generalized-identifier-segment
      decimal-digit-character generalized-identifier-segment (opt)
````

**Comment by CurtHagenlocher** [comment]
The definition of generalized-identifier is ... not great. This is largely because the implementation doesn't really lend itself to a usable grammar. For instance, `[9=1]` and `[9.0=1]` are legal, while `[9.=1]` is not.

**Comment by bgribaudo** [comment]
@CurtHagenlocher, would there be any chance of the current implementation being tweaked so that it aligns with a usable grammar? If not, any chance you could share the logic currently used, even if it doesn't express well in formal grammar syntax.

I'd like to align the [Data Mashup Cmdlets](https://bengribaudo.com/tools/datamashupcmdlets) code validation to the current implementation, but of course that's about impossible without a grammar. :-) It also looks like Microsoft's Power Query Parser's behavior doesn't align with the current implementation--which could possibly (???) be due to the lack of a good rule here. 

So some clarity here, or a tweak to the existing implementation, could potentially help a couple of projects.

Thanks!

**Comment by CurtHagenlocher** [comment]
Characters which are always valid in generalized-identifier are in the Unicode categories Uppercase Letter, Lowercase Letter, Titlecase Letter, Modifier Letter, Other Letter, Nonspacing Mark, Spacing Mark, Decimal Number, Connector Punctation and Format. The one character which is valid only situationally is the period (code point 46). Periods are not valid as the first or last character of the identifier, and it is not legal to have two consecutive periods. They are otherwise permitted.

**Comment by bgribaudo** [comment]
Thank you, @CurtHagenlocher!

Does this look right?

```
space:
    literal space character (code point 20)
period: 
    literal period character (code point 46)
generalized-identifier-always-valid-character: 
    any character from Unicode categories Uppercase Letter, Lowercase Letter, Titlecase Letter, Modifier Letter, Other Letter, Nonspacing Mark, Spacing Mark, Decimal Number, Connector Punctation and Format
generalized-identifier-inner-valid-character: 
    generalized-identifier-always-valid-character | space
generalized-identifier: 
    generalized-identifier-always-valid-character ((period? generalized-identifier-inner-valid-character)* generalized-identifier-always-valid-character)?
```

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by JasonWHowell** [comment]
This issue seems to be about this page:
URL: https://docs.microsoft.com/en-us/powerquery-m/m-spec-lexical-structure#generalized-identifiers
Source: https://github.com/MicrosoftDocs/query-docs/blob/main/query-languages/m/m-spec-lexical-structure.md

@bgribaudo if you have time and are willing, feel free to propose the change in the public repo. Thanks much, Jason
#please-open

**Comment by bgribaudo** [comment]
@CurtHagenlocher, do you time to look at the proposed grammar definition in my last comment (above)?

**Comment by bgribaudo** [comment]
Thanks, @egorelik93! How about the following?

````
space:
    literal space character (code point 20)
period: 
    literal period character (code point 46)
generalized-identifier-always-valid-character: 
    any character from the following Unicode categories: Uppercase Letter, Lowercase Letter, Titlecase Letter, Modifier Letter, Letter Number, Other Letter, Nonspacing Mark, Spacing Mark, Decimal Number, Connector Punctuation and Format
generalized-identifier: 
    generalized-identifier-always-valid-character (space* period? space* generalized-identifier-always-valid-character)*
````

**Comment by egorelik93** [comment]
@bgribaudo No dice; this gross thing apparently is valid M:

`[9 ab.  .   .   c= 0]`

Yours I believe forces every intermediate 'space dot space' piece to end in an always-valid-character, so it doesn't cover the above.

**Comment by egorelik93** [comment]
@bgribaudo Possibly this? I'd need to think about it a bit longer to check for errors.

```
space:
    literal space character (code point 20)
period: 
    literal period character (code point 46)
generalized-identifier-always-valid-character: 
    any character from the following Unicode categories: Uppercase Letter, Lowercase Letter, Titlecase Letter, Modifier Letter, Letter Number, Other Letter, Nonspacing Mark, Spacing Mark, Decimal Number, Connector Punctuation and Format
generalized-identifier-inner-valid-character: 
    generalized-identifier-always-valid-character | space
generalized-identifier: 
    generalized-identifier-always-valid-character ((period? generalized-identifier-inner-valid-character)* period? generalized-identifier-always-valid-character)?

**Comment by bgribaudo** [comment]
Oooh! Good catch on period-space-period.

**Comment by DougKlopfenstein** [comment]
@bgribaudo @egorelik93 
What needs to be done to the documentation to resolve this issue?

**Comment by bgribaudo** [comment]
Hi @DougKlopfenstein,

I think what should happen here/if anything should happen is dependent on the outcome of this PR: https://github.com/MicrosoftDocs/query-docs/pull/167. In essence, this PR is blocked by that one.

**Comment by DougKlopfenstein** [comment]
Hi @bgribaudo 
This issue has been open for almost 4 years. Since the issue is being handled in the PR you mention [above](https://github.com/MicrosoftDocs/query-docs/pull/167), I'm closing this issue so it doesn't continue to skew our internal reports.
#please-close

**Comment by bgribaudo** [comment]
Thank you, @DougKlopfenstein.
