### ISSUE TITLE
Today i loaded from MS latest version of MS Power bi. There were no such connector in the list. Only to Google BigQuery

### ISSUE THREAD

**Issue by AndreyYakshin** [MicrosoftDocs/powerquery-docs#300]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a400b-9171-ddfd-02dc-3988a56a25f0
* Version Independent ID: a50a400b-9171-ddfd-02dc-3988a56a25f0
* Content: [Power Query Google Sheets connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/googlesheets)
* Content Source: [powerquery-docs/Connectors/GoogleSheets.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/GoogleSheets.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by AndreyYakshin** [comment]
Today i loaded from MS latest version of MS Power bi. There were no such connector in the list. Only to Google BigQuery

**Comment by DougKlopfenstein** [comment]
Hi @AndreyYakshin 
I assume you are referring to Power Query Desktop. If so, could you select "Help > About" and let me know what version you are using? For example: Version: 2.109.624.0 64-bit (September 2022). Thanks!

**Comment by DougKlopfenstein** [comment]
Closed accidentally.

**Comment by DougKlopfenstein** [comment]
Hi @AndreyYakshin 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
