### ISSUE TITLE
Does not support Google Analytics 4: docs say v4 of the GA API, code says v3

### ISSUE THREAD

**Issue by GrahamAndersonLawSoc** [MicrosoftDocs/powerquery-docs#301]
The documentation specifically states that the connector uses v4 of the API. However,
* when logging in, I can't see any GA4 properties
* the code example at the bottom has an API url that specifically says v3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b1dbd00-8e52-f989-bc84-15f2f4e97b11
* Version Independent ID: a96aae45-f677-d62c-17d1-f02bb9120cad
* Content: [Power Query Google Analytics connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/googleanalytics)
* Content Source: [powerquery-docs/Connectors/GoogleAnalytics.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/GoogleAnalytics.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
#assign:bezhan-msft

**Comment by DougKlopfenstein** [comment]
Hi @GrahamAndersonLawSoc 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
