### ISSUE TITLE
SSL_MODE

### ISSUE THREAD

**Issue by matthewpa** [MicrosoftDocs/powerquery-docs#302]
Is it SSL_Mode, SSLMODE or some other combination?  What are the valid values?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd23e9b3-8d91-4685-9506-f6d89024fa12
* Version Independent ID: bd23e9b3-8d91-4685-9506-f6d89024fa12
* Content: [Power Query Denodo connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/denodo)
* Content Source: [powerquery-docs/Connectors/Denodo.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Denodo.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
#assign:bezhan-msft

**Comment by JasonWHowell** [comment]
@matthewpa  thought I don't know much about Denodo itself, it seems to follow many of the PostgreSQL conventions, this list might be helpful:
https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS

**Comment by JasonWHowell** [comment]
@denodo-research-labs can you take a look at this question please?

**Comment by denodo-research-labs** [comment]
If you mean the property in ODBC connection strings, it's `SSLmode` (case insensitive) as explained in the connector [documentation](https://github.com/MicrosoftDocs/powerquery-docs/blob/9c983ef8deaa4d581582bc38c73fc31010198818/powerquery-docs/Connectors/Denodo.md#connect-to-an-odbc-data-source-from-power-query-desktop).

**Comment by JasonWHowell** [comment]
@denodo-research-labs thanks. I don't see the list of actual parameter values for SSLmode though. Like disable, allow, prefer. Do you have an enumerated list handy?
https://docs.microsoft.com/en-us/power-query/connectors/denodo

**Comment by denodo-research-labs** [comment]
Several pieces of the Denodo public documentation explain how to create an ODBC DSN / Connection String and what values should be used for each parameter (including the ones that can be used from Power BI). The most relevant one would be [_"Configuration of the ODBC Driver on Windows"_](https://community.denodo.com/docs/html/browse/8.0/en/vdp/developer/access_through_odbc/configuration_of_the_odbc_driver_on_windows/configuration_of_the_odbc_driver_on_windows).

As explained in the Denodo documentation, SSL-enabled connections should use `require`, whereas non-SSL-enabled connections (which we do not recommend other than in development environments) can make use of `prefer` or `allow`.

Our view is that specific values to be used in connection strings seem to belong more to the scope of the Denodo ODBC-based access configuration --and therefore Denodo's documentation-- than to the scope of the documentation of the Denodo Connector for Power BI, and that keeping it this way could avoid future synchronization issues with Denodo's own public docs. But we also see why you could see value in enunciating these value recommendations in the connector's doc so, if you prefer so, we can create a PR adding a sentence or two about this to the doc.

**Comment by DougKlopfenstein** [comment]
Thanks @matthewpa for your feedback. Since it has been over a year since a response has been received, we're closing this issue. However, if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
