### ISSUE TITLE
lacking content

### ISSUE THREAD

**Issue by gtrimis** [MicrosoftDocs/powerquery-docs#303]
I am trouble shooting an issue and I cannot figure out why the connection is failing, I can make the call in postman, and curl, but I cannot see where Power query is failing. It would be better if there was not a data source setting gui and it was just a console that opened, with the ability to capture log files.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aed81ee-bc6a-ed81-ba22-591d9cb7dc46
* Version Independent ID: 5adb25c0-2a4d-7b3f-df4f-82feb892b768
* Content: [Troubleshooting dataflow issues - connection to the data source - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/troubleshooting-dataflow-issues-connection-to-the-data-source)
* Content Source: [powerquery-docs/dataflows/troubleshooting-dataflow-issues-connection-to-the-data-source.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/troubleshooting-dataflow-issues-connection-to-the-data-source.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
@grtimis sounds like a decent idea. This forum is for documentation feedback though. 

Would you mind tracking the wish in the product feedback page?

Submitting feedback
To submit feedback about Power Query, provide the feedback to the "ideas" forum for the product you're using Power Query in. For example, for Power BI, visit the [Power BI ideas forum](https://ideas.powerbi.com/). If you have one, you can also provide feedback directly to your Microsoft account contact.

**Comment by JasonWHowell** [comment]
#please-close
