### ISSUE TITLE
Denodo Connector Native Query Support

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerquery-docs#304]
Earlier this year Denodo worked with the Microsoft Data Integration team to update their connector to support native query. This has to be done manually for now and it would be good to included this for customers that are not aware of this and unfortunately my images I have won't paste int this post -->

For better context, let me explain how this manual workaround works:

First, a dataset has to be defined the usual way using the Denodo Connector: by selecting a Denodo view (no SQL query at this point). Once created, we will need to access the Power Query Editor by clicking on Transform Data.

Once there, we will select the dataset (“Query”) to be modified and access the “Advanced Editor”:

The Advanced Editor will show us the definition of the dataset in Power Query’s M language, which will initially look similar to this:

Then we will need to modify this code in order to make use of Power Query’s Value.NativeQuery function. We will need to specify the native SQL query to be used (in this case SELECT * FROM books WHERE category = 'Computer'), and also the EnableFolding=true option, which will enable Direct Query mode for this dataset even if a native SQL query has been specified:

Once done and saved, our books dataset has been configured to use a native SQL query instead of a full scan of the Denodo view.

For instance, if we created a report on this dataset that we used for showing the sum of the prices of all books published by year, and we specifically filtered at the report for years before 2001, we would see Denodo receiving a query like this:

Note how Denodo receives the native SQL query instead of the entire view in the FROM clause of the query (in orange), and how report filters are applied on top of the results of that native SQL query (in blue), being all of it —native query and report filters— delegated to Denodo for execution because we are in Direct Query mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd23e9b3-8d91-4685-9506-f6d89024fa12
* Version Independent ID: bd23e9b3-8d91-4685-9506-f6d89024fa12
* Content: [Power Query Denodo connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/denodo)
* Content Source: [powerquery-docs/Connectors/Denodo.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Denodo.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
#assign:bezhan-msft

**Comment by JasonWHowell** [comment]
@denglishbi are you working at Denodo? Do you have contact with the PM team in email already?

**Comment by JasonWHowell** [comment]
@denodo-research-labs can you take a look

**Comment by denodo-research-labs** [comment]
We will be doing a PR soon that adds some explanations on the use of `Value.NativeQuery` with the Denodo Connector.

**Comment by denodo-research-labs** [comment]
PR added: #313

**Comment by denodo-research-labs** [comment]
This should now be closed as #313 has been merged.

**Comment by JasonWHowell** [comment]
The URL is live: https://learn.microsoft.com/en-us/power-query/Connectors/Denodo
#please-close
