### ISSUE TITLE
Access Google Analytics API using the API key created within the Google Service Account, not by signing in with a gmail account

### ISSUE THREAD

**Issue by Acteon-Jon** [MicrosoftDocs/powerquery-docs#305]
Good Afternoon!

Using the Google Analytics Connector how can I access Google Analytics API using the API key created within the Google Service Account, not by signing in with a Gmail account?

I'd guess that's not possible given the options in this documentation, and in which case I should possibly try to use the default Web Connector, but not certain how - could you give an example here?

Thanks in advance,

Jon.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b1dbd00-8e52-f989-bc84-15f2f4e97b11
* Version Independent ID: a96aae45-f677-d62c-17d1-f02bb9120cad
* Content: [Power Query Google Analytics connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/googleanalytics)
* Content Source: [powerquery-docs/Connectors/GoogleAnalytics.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/GoogleAnalytics.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
#assign:bezhan-msft

**Comment by DougKlopfenstein** [comment]
Hi @Acteon-Jon 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. You can also direct product support requests to the [Power Query discussion group](https://community.powerbi.com/t5/Power-Query/bd-p/power-bi-services).  #please-close
