### ISSUE TITLE
Guidance on Networking

### ISSUE THREAD

**Issue by jcoxdco** [MicrosoftDocs/powerquery-docs#306]
Is there any guidance on what networking would be needed if one wanted to not allow public access to the storage account?
I can find the list of IP Addresses for the AzureCloud in my region, but is adding those IP address ranges to the firewall configuration of the storage account all that's needed?

Any networking documentation would be a help to the page content.

**Comment by JasonWHowell** [comment]
@jcoxdco do you have a specific docs page in mind when you wrote this feedback? If you do, please share the URL so I can better direct your feedback to the right expert. Thanks, Jason

**Comment by DougKlopfenstein** [comment]
Hi @jcoxdco 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
