### ISSUE TITLE
"Extension Context" - correct term?

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#307]
Under "[Authentication exceptions](https://learn.microsoft.com/en-us/power-query/handlingstatuscodes#authentication-exceptions)", there is a note implying that when `Web.Contents` is used in an "extension context," it gains a special behavior (specifically, the ability offer manual handling of certain errors).

I have a question about the use of the term "extension context." Is this the correct term to use here? 

The behaviors exhibited by the below scenarios make me wonder that it may not be the right term—or the problem could simply be my misunderstanding of what this term means. :-)

## Scenario 1
Below, `Web.Contents` is used inside an extension (a.k.a. in "extension context"). However, it behaves identical to how it would if it were used from regular (consumer) Power Query code. The special behaviors (in this case, the ability to handle 401 errors) are **not** present.

This makes me wonder that "extension context" is not the correct term to use in the article.

````
section MyTester;

shared MyTester.WebShortcut = () => 
  Value.Metadata(Web.Contents("http://some-example-returning-401", [ManualStatusHandling={401}]))[Response.Status];
// returns null when invoked from Power BI's Query Editor
````

## Scenario 2 
Below, in addition to being in an extension, `Web.Contents` is called by a data source method. In this situation, it **has** the promised special behavior.

````
section MyTester;

[DataSource.Kind="MyTester"]
shared MyTester.WebConnect = () => 
  Value.Metadata(Web.Contents("http://localhost:5111/WeatherForecast", [ManualStatusHandling={401}])[Response.Status]);
// returns 401 when invoked from Power BI's Query Editor

MyTester = [Authentication = [Implicit = []];  
````

## Question
What are the correct terms for the methods in scenarios 1 and 2?

Is it correct to say that scenario 1's method is in "extension context" (after all, it is in an extension)? (This would imply that the wording in the article needs to be tweaked.)

Is scenario 2's method in an "enhanced extension context" or "augmented extension context" (e.g. in extension context, but augmented with special privileges/permissions)?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0c5979-06ba-056e-6d69-07911a04761a
* Version Independent ID: 0c877e8f-db6e-eed7-871a-6abc4845f88a
* Content: [Handling status codes with Web.Contents for Power Query connectors - Power Query](https://learn.microsoft.com/en-us/power-query/handlingstatuscodes)
* Content Source: [powerquery-docs/HandlingStatusCodes.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/HandlingStatusCodes.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by JasonWHowell** [comment]
This looks resolved via https://github.com/MicrosoftDocs/powerquery-docs-pr/pull/698

**Comment by bgribaudo** [comment]
Thanks, @JasonWHowell & @ptyx507x!
