### ISSUE TITLE
Language Grammar – Missing alternative from field-name?

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#31]
In the [language specification](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar), `field-name` (which is used to name record fields and in projection) is defined as only allowing generalized identifiers. However, both Excel and Power BI also allow quoted identifiers to be used as field names.

Both of the following are accepted as valid M code by Excel and Power BI:
````
[hi = 2][#"hi"]
[#"hi" = 2][hi]
````

To align the specification with this reality, would it make sense to add quoted identifier as an alternative for field name? E.g.:
````
field-name:
      generalized-identifier
      quoted-identifier
````

**Comment by DougKlopfenstein** [comment]
@bgribaudo Thanks for the feedback. The change in field-name has been added to the documentation.

**Comment by bgribaudo** [comment]
Thank you, @DougKlopfenstein!
