### ISSUE TITLE
Count ID column rows; Range and Total

### ISSUE THREAD

**Issue by PeachBreeze** [MicrosoftDocs/powerquery-docs#314]
I've been looking for this solution for the many years I've been using Power Query and the M Language. Using Excel Formulas to identify duplicates and remove the rows needed from a dataset, I would create at least three columns next to the data. The first would count the # of duplicates via a countifs formula over a shifting range from the header row to the active row. The second column would be the total # of rows the ID is in its column. The third column would then compare the count with the total and if they Equal each other, that is the row I want to keep and can filter out everything else. If there is anyone who has a Power Query solution for this, that would be incredibly helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fce395f-4b81-9327-100b-00e9e4708c50
* Version Independent ID: bd9dd0ab-b307-6ca4-2128-45cdc3efd874
* Content: [Working with duplicate values - Power Query](https://learn.microsoft.com/en-us/power-query/working-with-duplicates)
* Content Source: [powerquery-docs/working-with-duplicates.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/working-with-duplicates.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **miescobar**

**Comment by ptyx507x** [comment]
Hey!

Apologies for the late reply.

For more contextual guidance on how to apply these concepts inside of Excel for Windows, you can follow the article from the Excel team below:
https://support.microsoft.com/en-us/office/import-data-from-a-folder-with-multiple-files-power-query-94b8023c-2e66-4f6b-8c78-6a00041c90e4

@JasonWHowell  this can be closed

**Comment by JasonWHowell** [comment]
#please-close
