### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/powerquery-docs#315]
It would be useful to indicate in the documentation that sorting is done A-Z, then a-z.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1753278-9dd5-96b0-1f41-8c24f96b8863
* Version Independent ID: 00ff26c1-7e1e-4c97-6c27-4f93e9c5c9f0
* Content: [Sort columns - Power Query](https://learn.microsoft.com/en-us/power-query/sort-columns)
* Content Source: [powerquery-docs/sort-columns.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/sort-columns.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @HairyDrumroll 
Thanks for the feedback! The [Sort columns](https://learn.microsoft.com/power-query/sort-columns) article has been completely updated, including adding A-Z, a-z ascending sort order and z-a, Z-A descending sort order information.
