### ISSUE TITLE
Misleading menu title

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/powerquery-docs#318]
This section do not contain documentation exclusively for desktop apps as the menu title suggest
For example the client ids for services.
![image](https://user-images.githubusercontent.com/50009020/201028574-f662a6f2-8e13-483e-bee3-46516a9752e5.png)

This part seems more suitable in the "Authentication in Power Query Online" section, and as far as I know, there is no "desktop app" for power apps and power automate (which should perhaps be named "Dataverse" instead?).  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bae8544-11ae-3d75-3466-141bd22e900d
* Version Independent ID: dededa48-e69d-92f8-2932-be3a708cdabb
* Content: [Authentication with a data source - Power Query](https://learn.microsoft.com/en-us/power-query/connectorauthentication)
* Content Source: [powerquery-docs/ConnectorAuthentication.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/ConnectorAuthentication.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @Hjaf 
Thanks for providing feedback that helps improve our documentation. This issue has been resolved (maybe not perfectly) and we are closing the issue. #please-close
