### ISSUE TITLE
WebAPI connector error suggesting to use itself.

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/powerquery-docs#319]
The learn more link points directly to the [Load from the web](https://learn.microsoft.com/en-us/power-query/connectors/json#load-from-the-web) section which contradictory to the error message.
> To load a JSON file from the web, select the [Web connector](https://learn.microsoft.com/en-us/power-query/connectors/web/web), enter the web address of the file, and follow any credential prompts.

![image](https://user-images.githubusercontent.com/50009020/201117807-42864d2c-330b-43d3-9f6a-bc2af9580bcd.png)

Another matter I'm facing is figuring out hosts and headers relevant for setting the right CORS policies on the backend (APIM), the closest I've gotten so far is the application ids used by the different services providing dataflows. [Supported workflow](https://learn.microsoft.com/en-us/power-query/connectorauthentication#supported-workflow).  Information or reference on this subject would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb0f1a2b-b9a7-5fad-546b-007cf208df47
* Version Independent ID: aa7c597e-2dea-b0d8-ba9b-65b4f9aaaca8
* Content: [Power Query JSON connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/json#load-from-the-web)
* Content Source: [powerquery-docs/Connectors/JSON.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/JSON.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Thanks @Hjaf for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. However, this appears to be product feedback or a request for product support. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback). 

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
