### ISSUE TITLE
Language Grammar – type-expression and nullable identifier references

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#32]
Hello,

If I'm understanding the [language specification](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#type-expression) correctly, a `type-expression` allows nullable types to be used (e.g. `type nullable text`); however the expression after the keyword `nullable` must either be a `primary-type` or a `parenthesized-expression`. 

````
type-expression:
      primary-expression
      "type" primary-type
type:
      parenthesized-expression
      primary-type
primary-type:
      primitive-type
      record-type
      list-type
      function-type
      table-type
      nullable-type

nullable-type:
      "nullable" type

parenthesized-expression:
      "(" expression ")"
````

However, both Excel and Power BI support a third alternative here: after "type nullable" an `identifier` can be used with no  parentheses required. 

Both of the following are accepted as valid M code in those tools:
````
type nullable SomeIdentifier
type nullable #"SomeIdentifier"
````

Could the specification be updated to reflect this third alternative?

**Comment by CurtHagenlocher** [comment]
I agree that the current definition isn't correct but the proposed alternative isn't either because it doesn't account for this valid expression: `(x) => type nullable Value.Type(x)`. This may require some thought.

**Comment by bgribaudo** [comment]
After wreslting with this some more today, I think this one has larger ramifications than just `type nullable`. :-)

The grammar also doesn't support the following field type expressions--or similar expressions for column types in `row-type` or in list's `item-type`--all of which Query Editor allows:
````
type [FieldA = SomeExpression]
type [FieldA = SomeExpression()]
type [FeidlA = ...]
type [FieldA = #shared[Currency.Type]]
`````

Not sure what the correct rule change is to rectify these. Since `nullable-type`, `item-type` and `field-type` all point back to `type`, maybe these issues could be address there. 

Not sure I've thought through all cases here, but maybe something like:

````
type:
      parenthesized-expression
      primary-type
      identifier
      identifier "(" argument-list(opt) ")"
      section-access-expression
      not-implemented-expression
````
In essence, expand `type` to support all `primary-expression`s except those that start with "[", "{", or "(".

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by JasonWHowell** [comment]
This issue seems to be about this page:
URL: https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar#type-expression
Source: https://github.com/MicrosoftDocs/query-docs/blob/main/query-languages/m/m-spec-consolidated-grammar.md

@bgribaudo if you have time and are willing, feel free to propose the change in the public repo. Thanks much, Jason
#please-open

**Comment by bgribaudo** [comment]
Thanks, @JasonWHowell. I will see what I can do on this one and the others you similarly tagged me in. Won't be today, but hopefully in the near future.

**Comment by JasonWHowell** [comment]
We have hundreds of these to do, so it going to take a long while. Appreciate any help we can get from experts like you.

**Comment by JasonWHowell** [comment]
#please-close
