### ISSUE TITLE
A brief and nice overview of Power Query

### ISSUE THREAD

**Issue by Bibek-Ananda** [MicrosoftDocs/powerquery-docs#321]
This is a good and nice overview of Power Query for those with exposure to Power BI, Spreadsheets and Databases.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9b1e7c-616b-87e0-7858-7f9e83b69ea5
* Version Independent ID: 5ffba9ae-ac08-3375-df06-507e7b6336f3
* Content: [What is Power Query? - Power Query](https://learn.microsoft.com/en-us/power-query/power-query-what-is-power-query)
* Content Source: [powerquery-docs/power-query-what-is-power-query.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-what-is-power-query.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by JasonWHowell** [comment]
@Bibek-Ananda thanks for the feedback!

**Comment by Bibek-Ananda** [comment]
Hello Jason,
Sorry for the goof-up. Apologies for any confusion or inconvenience caused.
Regards,- - - - - - - B i b e k    On Saturday, November 12, 2022 at 08:44:02 AM GMT+5:30, Jason Howell ***@***.***> wrote:  
 
 


Closed #321 as completed.
