### ISSUE TITLE
I can connect but it's too slow to be useful

### ISSUE THREAD

**Issue by Wheels14** [MicrosoftDocs/powerquery-docs#324]
When I connect to my sharepoint folder,  It's too slow to be able to do anything.  It starts out working fine, but eventually the query refresh just stalls out.  Is this data throttling through Sharepoint?  How would I find out and what can I do about it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7fa007-53f0-1fa5-bbff-b59fe142c804
* Version Independent ID: acb9ddd9-08ea-79ea-3537-cf8bda64282b
* Content: [Power Query SharePoint folder connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/sharepointfolder?source=recommendations)
* Content Source: [powerquery-docs/Connectors/SharePointFolder.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointFolder.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
@Wheels14 I don't have any resources in the documentation team that have background about the Power Query Sharepoint connectivity performance concern. 

I think you'd have a better chance of getting an expert via the online forum here: https://community.powerbi.com/t5/Power-Query/bd-p/power-bi-services

Thanks for the feedback. 

#please-close
