### ISSUE TITLE
Requirements for On Premise Gateway

### ISSUE THREAD

**Issue by Chris-Burgess-ACTGOV** [MicrosoftDocs/powerquery-docs#325]
Hi Team
referring to this page re web connectors and then limitations section specifically for On Premise Gateway:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/60373199/202361849-0f82113c-bbb6-428a-942e-bcd2a7a2866d.png">
Mentions IE being a requirement on the gateway node machines. 
Is this now EDGE or webview2 or ?

Additionally, i cannot find a definitive source in the learn. portal outlining what applications need to be installed and maintained on the Gateway machines to ensure seamless connectivity to (supported) data sources. (webview2, powerbi desktop?, IE/Edge, gateway.exe, ???)

Can you point me in the right direction?
Cheers
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7136b5-122b-0e0e-8992-926ee09a5da8
* Version Independent ID: 6179e1c3-b6dc-5b3a-c748-a948afb77870
* Content: [Troubleshooting the Power Query Web connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/web/web-troubleshoot#limitations-on-web-connector-authentication-for-html-content)
* Content Source: [powerquery-docs/Connectors/Web/web-troubleshoot.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Web/web-troubleshoot.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @Chris-Burgess-ACTGOV 

The [Troubleshooting the Power Query Web connector](https://learn.microsoft.com/en-us/power-query/connectors/web/web-troubleshoot) article was updated in April of 2023. Does the update answer all of the questions you asked here? If so, please let us know so we can either close the issue or continue the conversation.

**Comment by DougKlopfenstein** [comment]
Hi @Chris-Burgess-ACTGOV 
Thanks for your dedication to our documentation. Since we haven't received an answer to our question posted above, we're closing this issue at this time. However, if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
