### ISSUE TITLE
Broken link to connector description?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#326]
This is regarding the link highlighted in the screenshot below.

![image](https://user-images.githubusercontent.com/1765732/202518457-4aa8877a-d8b1-444c-9e1f-a947d8bb6250.png)

Where is it supposed to go? It currently just goes to the Power BI home page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Version Independent ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Content: [Power Query Azure Synapse Analytics workspace connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/synapse)
* Content Source: [powerquery-docs/Connectors/Synapse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Synapse.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
Thanks for the feedback.

This seems to be product feedback or a request for product support. In this case, please direct those queries to the [Power BI community forum](https://community.fabric.microsoft.com/t5/Power-Query/bd-p/power-bi-services) or to the connector-specific support contact (if applicable).
