### ISSUE TITLE
AI Integration doc issue

### ISSUE THREAD

**Issue by mpoeckl** [MicrosoftDocs/powerquery-docs#329]
Section [**AI Integration**](https://learn.microsoft.com/en-us/power-query/dataflows/understanding-differences-between-analytical-standard-dataflows#ai-integration) sates:
_"These functionalities are available in Power BI dataflows and require a Premium workspace."
"Note that the features listed above are Power BI specific and **are not available when creating a dataflow in the Power Apps or Dynamics 365 customer insights** portals."_
This is not consistent with regards to the following two sections on the same page/article.

The table in section [**Standard vs. analytical dataflows**](https://learn.microsoft.com/en-us/power-query/dataflows/understanding-differences-between-analytical-standard-dataflows#standard-vs-analytical-dataflows) states:
<html>
<body>

Operation | Standard | Analytical
-- | -- | --
AI functions | No | **Yes**

</body>
</html>

The section [**AI features—analytical dataflow**](https://learn.microsoft.com/en-us/power-query/dataflows/understanding-differences-between-analytical-standard-dataflows#ai-featuresanalytical-dataflow) states:
_"If you're planning to use any AI functionality through the data transformation stage, you'll find it helpful to use an **analytical dataflow** because you can **use all the supported AI features** with this type of dataflow."_

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c08c29a4-99c2-69ca-6bcd-75541c697215
* Version Independent ID: 0516d7ae-4cf4-a5e7-d20a-e3839ecf6120
* Content: [Understanding the differences between dataflow types - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/understanding-differences-between-analytical-standard-dataflows)
* Content Source: [powerquery-docs/dataflows/understanding-differences-between-analytical-standard-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/understanding-differences-between-analytical-standard-dataflows.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @mpoeckl 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
