### ISSUE TITLE
Custom Connector development without debugger and proper logfiles is hard.

### ISSUE THREAD

**Issue by zebrassimo** [MicrosoftDocs/powerquery-docs#33]
Hi all,

while trying to develop a custom connector and going through the [TripPin 6 - Schema](https://docs.microsoft.com/en-us/power-query/samples/trippin/6-schema/readme) instructions, I keep getting the error "_We cannot convert a value of type Function to type Table_".

Without undoing all steps I have taken prior to arriving here, I would actually like to know what I'm doing wrong. Debugging is enabled, Diagnostics.LogValue calls are correclty implemented all over the code, I keep reading the logfiles just in time and watch the webcalls with fiddler.

The errors that I'm getting can of course be resolved, but what I'm saking for is:
- Give me an actual debugger, where I can set breakpoints and step through.
- In the logfiles, provide a stack trace on where errors occur.

Can you make that happen? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8257c0fb-b207-659f-7476-39cfb5243493
* Version Independent ID: cdce1369-f53a-29be-d3e2-6df649bc9ae9
* Content: [TripPin 6 - Schema](https://docs.microsoft.com/en-us/power-query/samples/trippin/6-schema/readme)
* Content Source: [powerquery-docs/samples/TripPin/6-Schema/README.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/samples/TripPin/6-Schema/README.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @zebrassimo

This appears to be a customer support issue rather than a documentation issue. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
