### ISSUE TITLE
Release State

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#334]
I think there is a typo here. Should say "Public Preview" instead of "Public Review".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Version Independent ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Content: [Power Query Azure Synapse Analytics workspace connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/synapse)
* Content Source: [powerquery-docs/Connectors/Synapse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Synapse.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by JasonWHowell** [comment]
Fixing in https://github.com/MicrosoftDocs/powerquery-docs-pr/pull/738

**Comment by JasonWHowell** [comment]
#please-close
