### ISSUE TITLE
The other Synapse Analytics connector

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#336]
It looks like the name has changed since this page was created. As of the current (November 2022) release of Power BI Desktop, the other connector is called "Azyre Synapse Analytics SQL". This has at least a few impacts to this page:

1) References in explanations 
2) Screenshot for Get Data experience. Here's how it looks now:

![image](https://user-images.githubusercontent.com/1765732/204700534-b39dfb10-410f-4586-8bcd-988415bd530d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Version Independent ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Content: [Power Query Azure Synapse Analytics workspace connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/synapse)
* Content Source: [powerquery-docs/Connectors/Synapse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Synapse.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
Thanks for your feedback! The Power Query Desktop section of the Azure Synapse Analytics connector article was changed to reflect the changes in the connector name. In Power Query Online, the name was not changed, so that section remains as-is.

**Comment by VitalyMCT** [comment]
Thanks @DougKlopfenstein !
