### ISSUE TITLE
New connector name

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#337]
The connector's name has changed. It's now called "Azure Synapse Analytics SQL".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f15da4f-8f22-3f68-165c-1bb0c4edc887
* Version Independent ID: 29d89981-6694-8b87-d5b6-614b8680cd90
* Content: [Power Query Azure Synapse Analytics (SQL DW) connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/azuresqldatawarehouse)
* Content Source: [powerquery-docs/Connectors/AzureSQLDataWarehouse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/AzureSQLDataWarehouse.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Related to #336

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
The Power Query article for this connector has been updated to use "Azure Synapse Analytics SQL" in the section on connecting from Power Query Desktop. The connector name in Power Query Online is still "Azure Synapse Analytics (SQL DW)". When and if the name is changed in Power Query Online, the documentation will be changed to reflect the new name. #please-close
