### ISSUE TITLE
Guidance to manually install SQL Server Native Client

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#338]
Regarding

> However, for optimal performance, we recommend that the customer installs the [SQL Server Native Client](https://learn.microsoft.com/en-us/sql/relational-databases/native-client/applications/installing-sql-server-native-client) before using the Azure Synapse Analytics (SQL DW) connector. SQL Server Native Client 11.0 and SQL Server Native Client 10.0 are both supported in the latest version.

Yet, from the recently-released SQL Server 2022 guidance at https://learn.microsoft.com/en-us/sql/relational-databases/native-client/sql-server-native-client?view=sql-server-ver16:

![image](https://user-images.githubusercontent.com/1765732/204701322-70a8d587-cb73-44e8-8d18-d11f28c1abaf.png)

What's the current guidance giving the update above? 

What happens if the customer follows the SQL Server guidance and skips installing SQL Server Native Client separately? What "optimal performance" aspects (if any) would be impacted?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f15da4f-8f22-3f68-165c-1bb0c4edc887
* Version Independent ID: 29d89981-6694-8b87-d5b6-614b8680cd90
* Content: [Power Query Azure Synapse Analytics (SQL DW) connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/azuresqldatawarehouse)
* Content Source: [powerquery-docs/Connectors/AzureSQLDataWarehouse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/AzureSQLDataWarehouse.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Yeah, Microsoft has changed courses several times on the favored connectors in recent years. SQL 2022 is quite new, and we haven't updated this page recently. I'm not sure if PowerQuery is taking advantage of the new features or not, so this boils down to a technical question for our product team.

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
