### ISSUE TITLE
Reference to an unrelated Azure service

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#340]
Regarding

> Once you've selected the advanced options you require, select OK in Power Query Desktop or Next in Power Query Online to connect to your Azure SQL database.

Azure SQL database is a different Azure service. Instead of "Azure SQL database" it should say "Azure Synapse Analytics", or perhaps reference the specific SQL pool technology (serverless or dedicated) within Azure Synapse Analytics. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f15da4f-8f22-3f68-165c-1bb0c4edc887
* Version Independent ID: 29d89981-6694-8b87-d5b6-614b8680cd90
* Content: [Power Query Azure Synapse Analytics (SQL DW) connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/azuresqldatawarehouse)
* Content Source: [powerquery-docs/Connectors/AzureSQLDataWarehouse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/AzureSQLDataWarehouse.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
@VitalyMCT  you seem like you are really knowledgeable about these subjects. If you have any time, we'd appreciate some help to repair the text when you see issues. There's a pencil icon on the top of the docs, and you can propose the necessary edit, and we'll triage and discuss those proposals. 

This is the link for the page you found the bug on if you want to give it a try. 
https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/AzureSQLDataWarehouse.md

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
Thanks for the feedback! The article has been updated and now refers to Azure Synapse Analytics.
