### ISSUE TITLE
On-prem data gateway

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#341]
Regarding

> If required, select the name of your on-premises data gateway.

This step does not make sense in the context of this page. Azure Synapse Analytics does not expose data via on-premises data gateways.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f15da4f-8f22-3f68-165c-1bb0c4edc887
* Version Independent ID: 29d89981-6694-8b87-d5b6-614b8680cd90
* Content: [Power Query Azure Synapse Analytics (SQL DW) connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/azuresqldatawarehouse)
* Content Source: [powerquery-docs/Connectors/AzureSQLDataWarehouse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/AzureSQLDataWarehouse.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
The article has been fixed. 
#please-close
