### ISSUE TITLE
Encryption is mandatory

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#342]
Regarding

> If the connection is not encrypted, clear the Use Encrypted Connection check box.

This seems to have been replicated from the SQL Server connector description. I don't think it applies here - i.e. if the user disables encryption the connection to Azure Synapse Analytics would fail. 

Source:  https://learn.microsoft.com/en-us/azure/synapse-analytics/guidance/security-white-paper-data-protection

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f15da4f-8f22-3f68-165c-1bb0c4edc887
* Version Independent ID: 29d89981-6694-8b87-d5b6-614b8680cd90
* Content: [Power Query Azure Synapse Analytics (SQL DW) connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/azuresqldatawarehouse)
* Content Source: [powerquery-docs/Connectors/AzureSQLDataWarehouse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/AzureSQLDataWarehouse.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
The irrelevant text has been removed.
#please-close
