### ISSUE TITLE
A 'does not' is missing, probably .

### ISSUE THREAD

**Issue by weijiashao** [MicrosoftDocs/powerquery-docs#345]
[Enter feedback here]

A 'does not' is missing, probably .

page: https://learn.microsoft.com/en-us/power-query/error-handling

Position:
If the value in the All Errors.Errors.Message column equals null, then the output will be the value from the Standard Rate column.
Else, if the value in the All Errors.Errors.Message column (**_does not_**) equals Invalid cell value '#REF!'., then the output will be the value from the Special Rate column.
Else, null.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f7f1a9f-5a30-6c87-01d1-e0c2f207b547
* Version Independent ID: ea8b93ab-e8d0-e8c0-0257-a74775241dff
* Content: [Error handling - Power Query](https://learn.microsoft.com/en-us/power-query/error-handling)
* Content Source: [powerquery-docs/error-handling.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/error-handling.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by ptyx507x** [comment]
Thank you for the feedback @weijiashao ! 

We'll be updating the article shortly.

**Comment by ptyx507x** [comment]
@JasonWHowell this can be closed

**Comment by JasonWHowell** [comment]
@ptyx507x thanks you can type `#please-close` - try it and let me know.

**Comment by ptyx507x** [comment]
#please-close
