### ISSUE TITLE
Linked help should be version-specific

### ISSUE THREAD

**Issue by NorthboundTrain** [MicrosoftDocs/powerquery-docs#346]
I'm running Excel for Mac 16.67 and I did a help search. The results gave me the exact thing I was looking for -- except it doesn't seem to apply to my version. What's the use of help if it's not relevant to the version of the software I'm on or have access to?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb0f1a2b-b9a7-5fad-546b-007cf208df47
* Version Independent ID: aa7c597e-2dea-b0d8-ba9b-65b4f9aaaca8
* Content: [Power Query JSON connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/json)
* Content Source: [powerquery-docs/Connectors/JSON.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/JSON.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
@NorthboundTrain Thanks for the feedback. 

We didn't have Mac hardware on the docs team, but recently got one and that will help us bring the Mac experience into the docs better. Would that help to mention if this page applies to Mac or not?

**Comment by NorthboundTrain** [comment]
Yes, most definitely!

**Comment by JasonWHowell** [comment]
@DougKlopfenstein a Mac exploration one for you.

**Comment by DougKlopfenstein** [comment]
Hi @NorthboundTrain 
Thanks for providing feedback that helps improve our documentation. This issue has been resolved some time ago by adding a note to the list of all connectors that links to the [Power Query data sources in Excel versions](https://support.microsoft.com/office/power-query-data-sources-in-excel-versions-e9332067-8e49-46fc-97ff-f2e1bfa0cb16). Therefore, we are closing the issue. #please-close
