### ISSUE TITLE
Left outer join doesn't keep all rows from the first table

### ISSUE THREAD

**Issue by gwilku** [MicrosoftDocs/powerquery-docs#347]
This is absolute nonsense. The Left outer join is bugged, because it DOES NOT keep all the rows from the first table. At least not after you expand columns from the second table in the view. The REAL result of the example shown would be a table with country IDs 1,2 and 3, and the 4th one would be gone - that's how the query editore REALLY behaves.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7ea80c-8f90-fa2e-12c0-b887abdb1533
* Version Independent ID: 8a23f2c7-86a6-df61-5251-6c5dc21f66ee
* Content: [Left outer join - Power Query](https://learn.microsoft.com/en-us/power-query/merge-queries-left-outer)
* Content Source: [powerquery-docs/merge-queries-left-outer.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/merge-queries-left-outer.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @gwilku 
After testing the procedure in the article above, the output generated is accurately created as described in the article. Therefore, this seems to be product feedback or a request for product support. For information about product feedback or customer support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback).
