### ISSUE TITLE
Add Permissions needed

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerquery-docs#348]
Hello,

I just had a customer who tried to connect from PBI to Excel on SharePoint via SharePoint folder connector.
As Cx access on the SharePoint is read only to the actual Excel they are getting credential errors.

While verifying with PG on escalation channels, they mentioned that permissions READ is sufficient, yet needs to be applied to all parent folders leading to the Excel.

Can you use the below 2 responses to add the minimum permission needed to this document page?
Thank you. Martina

Extract from the Escalation channels
 **[Navya Jammula]** 
(https://web.yammer.com/main/users/eyJfdHlwZSI6IlVzZXIiLCJpZCI6IjE0MTUxNjQ0NjEwNTYifQ/storyline)
(https://web.yammer.com/main/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjAzNTAwNTU1NTY2Mjg0OCJ9/eyJfdHlwZSI6Ik1lc3NhZ2UiLCJpZCI6IjIwMzk0MDAwODE1MzA4ODAifQ)

The user should have read access to all the parent folders, so the mashup is able to navigate to the file. If they do not want to grant permissions to all the folders, they need to move the file to a location where they can provide read access to the user. If the file name contains # or % or $, the user might see authentication issues as well. Please make sure the file name doesn't contain any of these special characters.

second response
**[Cameron Stillion]**
(https://web.yammer.com/main/users/eyJfdHlwZSI6IlVzZXIiLCJpZCI6IjE1MzAzMDE4MTQifQ/storyline)
(https://web.yammer.com/main/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjAyNzc5NTQ4MDM1NDgxNiJ9/eyJfdHlwZSI6Ik1lc3NhZ2UiLCJpZCI6IjIwMzk1MDQ0MTUzMjYyMDgifQ)

The current SharePoint connector requires that the user requesting document library contents have access to the SharePoint Site as well as the Document Library, and any folders leading to the requested file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7fa007-53f0-1fa5-bbff-b59fe142c804
* Version Independent ID: acb9ddd9-08ea-79ea-3537-cf8bda64282b
* Content: [Power Query SharePoint folder connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/sharepointfolder)
* Content Source: [powerquery-docs/Connectors/SharePointFolder.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointFolder.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @MartinaPoddana 
Thanks for your feedback! This information was added to the SharePoint folder article some time ago. So, I'm closing this issue as fixed.
