### ISSUE TITLE
Language Grammar - Type Equivalence

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#35]
Hello,

The language specification's section on [Type equivalence and compatibility](https://docs.microsoft.com/en-us/powerquery-m/m-spec-types#type-equivalence-and-compatibility) says:

> Type equivalence is not defined in M. Any two type values that are compared for equality may or may not return true. However, the relation between those two types (whether true or false) will always be the same.
   
However, based on a [TechNet forum post](https://social.technet.microsoft.com/Forums/en-US/2fa9b143-7fc4-45ab-8cb5-2eec83237b24/type-equality?forum=powerquery#39e024a7-93c1-41ba-a68f-9df632ed399a-isAnswer), it sounds like this is only the case for non-nullable primitive types, while equality comparisons for nullable primitive types work because the mashup engine shares the same value instance for all references to a given nullable primitive type. It seems like this holds true so long as the nullable primitive type also has the same type kind claim (which is way `Currency.Type = Currency.Type // true` while `Currency.Type = type number // false`). Could the specification be updated to reflect this? (Various examples around the Internet rely on this behavior--e.g. code that boils down to comparisons like `type text = type text`.) 

Also, the way the quoted statement is worded makes it sound like comparing two types that are different could in some cases return true. I think this is incorrect, that comparing different types won't ever return true. If so, could this be clarified?

It also appears that any `Type.Facets` are ignored in equality comparisons.

Maybe that spec section could be revised to something along the lines of:

> Type equivalence in M is only partially defined.
> 
> When two type values are compared for equality:
> * If both describe the same nullable primitive type and have the same type kind claim facet, true is returned.
> * If both describe different types, false is returned.
> * If both describe the same custom type, M does not define equivalence rules so true or false may be returned. However, the relation between those two types (whether true or false) will always be the same when they are compared using the same mashup engine version.
>
> A type value's `Type.Facets` are ignored when comparing for equality. 

Thank you for your consideration.

**Comment by JoeEdwardsGitHub** [comment]
I absolutely support Ben in this request. It is really important that the documentation is explicit in what can and cannot be relied upon. Like it or not, people will use methods such as "type text = type text" to solve their local challenges unless there is a good reason not to, and therefore it is critical that reliable behaviour is clearly stated, even if complex.

**Comment by JasonWHowell** [comment]
This issue seems to be about this page:
URL: https://docs.microsoft.com/en-us/powerquery-m/m-spec-types#type-equivalence-and-compatibility
Source: https://github.com/MicrosoftDocs/query-docs/blob/main/query-languages/m/m-spec-types.md

@bgribaudo if you have time and are willing, feel free to propose the change in the public repo. Thanks much, Jason
#please-open

**Comment by bgribaudo** [comment]
Related PR in the works: https://github.com/MicrosoftDocs/query-docs/pull/49

**Comment by JasonWHowell** [comment]
#please-close this one is now resolved thanks to @bgribaudo
