### ISSUE TITLE
Create dynamic parameter(s) with values stored in sql server (stored proc)

### ISSUE THREAD

**Issue by tahmid-bari** [MicrosoftDocs/powerquery-docs#352]
Hi PBI Team,

My dataset is linked using 'import' and a stored procedure in SQL server. I have created dynamic parameters (start date, end date, number) where I can enter values that change the result data in 'edit parameter'. However, I am having trouble (cannot find 'Advance' option) binding those dynamic parameters to the newly created tables. Furthermore, can I include another stored procedure in the dynamic parameter - number so that the end user can select from a drop down list? In fact, because the (Dynamic M query parameters) feature does not support RLS, I am attempting to implement row-level security by creating a table in SQL Server and using DAX on the table (dynamic parameter - number). I also understand that creating a dynamic user filter using a security field in the data can be done in Tableau, but we'd prefer to find a solution in the Power BI app. Thank you.

Sincerely,
Tahmid Bari

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7ae586a-2f62-ad6d-2ced-953908abe66e
* Version Independent ID: f4def8d1-85cd-1bed-2771-ed81cf8eeb78
* Content: [Parameters - Power Query](https://learn.microsoft.com/en-us/power-query/power-query-query-parameters)
* Content Source: [powerquery-docs/power-query-query-parameters.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-query-parameters.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by ptyx507x** [comment]
Hey!

My name is Miguel Escobar and I'm a Product Manager at Microsoft for the team behind Power Query.

I believe that the article below might be more in line with what you're looking for in terms of dynamic parameters inside of Power BI Desktop:
https://learn.microsoft.com/power-bi/connect-data/desktop-dynamic-m-query-parameters

For questions related to Power Query inside of Power BI Desktop, we recommend posting your scenario and any questions to the official Power BI forum using the link below:
https://community.powerbi.com/t5/Power-Query/bd-p/power-bi-services

For any feedback, suggestions or questions about existing articles we welcome you to provide such in this GitHub repository.

Best!

**Comment by ptyx507x** [comment]
#please-close

**Comment by tahmid-bari** [comment]
Hi Miguel,
Thank you for your feedback. I will post my scenario and any questions to the official Power BI forum moving forward. Thanks.
