### ISSUE TITLE
Power Automate - Condition Refresh

### ISSUE THREAD

**Issue by MoniekNL** [MicrosoftDocs/powerquery-docs#353]
When using Power Automate I can not select the condition Refresh Status as mentioned in the instruction (step 7)

[https://learn.microsoft.com/en-us/power-query/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially](https://learn.microsoft.com/en-us/power-query/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially)

**Comment by DougKlopfenstein** [comment]
Hi @MoniekNL 
Note that step 7c, the text says "Enter Success." This means (in most cases) that you type in the word "Success". There isn't any place to select the word "Success".

If this doesn't work, please feel free to reopen this issue.
