### ISSUE TITLE
Page needs instructions on getting a Google Doc's URL

### ISSUE THREAD

**Issue by JerryDNYC** [MicrosoftDocs/powerquery-docs#356]
[Enter feedback here]
This page needs a small section on exactly how to get the document's URL. I tried using the URL that showed when I opened a Google Sheet's file's URL but it's not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a50a400b-9171-ddfd-02dc-3988a56a25f0
* Version Independent ID: a50a400b-9171-ddfd-02dc-3988a56a25f0
* Content: [Power Query Google Sheets connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/googlesheets)
* Content Source: [powerquery-docs/Connectors/GoogleSheets.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/GoogleSheets.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Thanks @JerryDNYC for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. However, this appears to be product feedback or a request for product support. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback). 

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
