### ISSUE TITLE
Missing Components not addressed in the documentation

### ISSUE THREAD

**Issue by ToddChitt** [MicrosoftDocs/powerquery-docs#361]
Nice documentation. However, when I try to specify a MySQL source in Power BI, I get an error: "This connector requires one or more additional components to be installed before it can be used." and there is a link for "Learn more" 
I follow the link, install the required components, but still get this error. 

There are obviously prerequisites that you don't address. 

WHAT 'components' are missing? Nobody seems to be able to tell me. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 545a929c-1c6a-29b9-5e59-31f3823946da
* Version Independent ID: a7da33e7-7535-1dac-b36a-57f3ded22586
* Content: [Power Query MySQL database connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/mysql-database)
* Content Source: [powerquery-docs/connectors/mysql-database.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/mysql-database.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
@ToddChitt sometimes software installs require a service to be stopped/started or a reboot (kind of the same thing). Could be exiting the app (Excel / PowerBI / PowerQuery processes) and starting again would detect the new assemblies that are installed on your box.

**Comment by DougKlopfenstein** [comment]
Hi @ToddChitt 
This issue has been closed due to lack of any new information for several months. If you have more information to provide, please reopen this issue.
