### ISSUE TITLE
Why have all other mentions of M extensions been scrubbed from the internet?

### ISSUE THREAD

**Issue by chrstfer** [MicrosoftDocs/powerquery-docs#366]
This page is the only reference to an entire method of adding external libraries to power query M that I have not seen mentioned *anywhere* else but through chatgpt, which is *convinced* this is a real thing for PQM.

I want the Text.LevenshteinDistance function it claims is available from the M-Extension "Extension.PQLibrary" if it exists at all, but what is far more curious to me is how references to documention end in broken links (mysteriously none of which are archived by the wayback machine....), and the phrase "M-Extension" (with or without the dash)--despite obviously being an official term per the page I am referencing in this issue--doesn't have any other references returned by major search engines.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63706099-f414-4f48-165d-a3609437a37e
* Version Independent ID: 1807dacc-1bf2-79aa-70b1-bebd2f2c6331
* Content: [Helper functions for M extensions for Power Query connectors - Power Query](https://learn.microsoft.com/en-us/power-query/helper-functions)
* Content Source: [powerquery-docs/helper-functions.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/helper-functions.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by chrstfer** [comment]
And if this is just an artifact of ChatGPT hallucinating that yall were competent at language ecosystem design..... Well, perhaps its more optimistic than I. 

So what is it, memory hole or poor planning?

**Comment by migueesc123** [comment]
Hey!
This page is primarily for helper functions in the context of the Power Query SDK which is primarily aimed towards creating Power Query custom connectors. A Power Query custom connector is effectively an M extension. You can learn more about the Power Query SDK from the [official overview article](https://learn.microsoft.com/power-query/install-sdk). We hope that you can give it a try.

I'm not aware of anything related to "Extension.PQLibrary" or a "Text.LevenshteinDistance" function within the context of this article or any others. 

For the official list of functions available in the Power Query language you can visit the link below:
https://learn.microsoft.com/powerquery-m/

Hope this helps!

**Comment by chrstfer** [comment]
@migueesc123 I can't find any reference to it either, but in multiple separate "conversations" ive had it referenced by name in chatgpt sessions, so somewhere in the training data for that model there was a selection of documents that mention those things. Here's one iteration of a snippet i got it to generate a couple times by asking about power query extensions in the plus turbo model. Is this really a hallucination? If it is, I'm amazed. And the "import" 'keyword' (it insisted it wasnt a keyword...) too?

>Power Query provides several built-in extension libraries that offer additional functions and capabilities beyond the standard M library. These extension libraries are included with Power Query and do not require any additional installation.

>Here are some of the most commonly used Power Query extension libraries:

>Extension.PQLibrary: Provides a set of functions for string manipulation, regular expressions, and date/time calculations, including Text.LevenshteinDistance.

>Extension.PrimitiveValueFunctions: Provides a set of functions for creating and manipulating primitive data types, such as boolean, integer, decimal, and date/time.

>Extension.RecordFunctions: Provides a set of functions for creating and manipulating record data types.

>Extension.TableFunctions: Provides a set of functions for creating and manipulating table data types.

>Extension.ExcelFunctions: Provides a set of functions for working with Excel-specific features, such as worksheets, ranges, and cell values.

>Extension.JsonFunctions: Provides a set of functions for working with JSON data, including parsing and generating JSON strings.

>Extension.XmlFunctions: Provides a set of functions for working with XML data, including parsing and generating XML strings.

>Extension.DatabaseFunctions: Provides a set of functions for working with relational databases, including connecting to databases, executing SQL queries, and retrieving data.

**Comment by ninmonkey** [comment]
I've been around a while, I'm pretty sure there the url [https://docs.microsoft.com/en-us/powerquery-m/working-with-external-libraries](https://docs.microsoft.com/en-us/powerquery-m/working-with-external-libraries) hasn't existed. The Wayback machine having zero indexes means it's more likely it didn't.

ChatAI is good at making up things that are mixed with truth, or aren't true, but sound reason reasonable. They can be useful if you verify their answers. Like ask for a custom date format string, getting you most of the way -- then double check it against the docs. 



----
Here's some links that you're looking for

### Regex

There's nothing built in. The ways I've seen it done is

1) A web request that uses a web browser instance to do the actual parsing, or
2) `Web.Contents` /w a [REST API](https://github.com/firasdib/Regex101/wiki/API)

### Importing Queries? With the SDK

An example from the [sdk's `TripPin.pq` tutorial](https://github.com/microsoft/DataConnectors/blob/c7d7ba5cb8e2073c4d970bd9803dcaa6fd079695/samples/TripPin/9-TestConnection/TripPin.pq#L187) uses this:

```pq
Diagnostics = Extension.LoadFunction("Diagnostics.pqm")
```
- [TripPin.pq](https://github.com/microsoft/DataConnectors/blob/c7d7ba5cb8e2073c4d970bd9803dcaa6fd079695/samples/TripPin/9-TestConnection/TripPin.pq#L187) is importing a local file [Diagnostics.pqm](https://github.com/microsoft/DataConnectors/blob/c7d7ba5cb8e2073c4d970bd9803dcaa6fd079695/samples/TripPin/9-TestConnection/Diagnostics.pqm)

Then it has these statements (ignore the `;` for now and the `.`)
```pq
Diagnostics.LogValue = Diagnostics[LogValue],
Diagnostics.LogFailure = Diagnostics[LogFailure]
```
It's declaring two values. `MyLib` and `Diagnostics` are records with nested functions. ( [another  example](https://gist.github.com/ninmonkey/aadf784c387b9956039fcbb729c6b8ff) )
```
MyFancyFunction = MyLib[FunctionName],
function2 = MyLib[FunctionName2]
```
### Libraries are nested records

`Diagnostics.pqm` looks complicated. The important part to know is that
- it's one big `record`
- the values of the fields are functions.
- `Diagnostics.LogValue` is creating an alias to the nested function.
- There are no classes in PowerQuery. `Diagnostics.LogValue` or `Number.FromText` are all flat functions. there's no OOP relationships. The `.` is part of the variable name, itself.

### Importing without the SDK's functions

Outside of the SDK there isn't a standard method. I wrote a function: [ImportPQ.FromFile](https://github.com/ninmonkey/ninMonkQuery-examples/blob/main/Excel/pq/ImportPQ.FromFile.pq) that's similar. it lets you edit queries outside of Excel by calling `Expression.Evaluate(rawText, #shared)` 
- [r/PowerQuery/Editing_and_importing_local_pq_files_from_outside](https://www.reddit.com/r/PowerQuery/comments/yzrma4/editing_and_importing_local_pq_files_from_outside/)

### `#shared` ? `#sections` ? 

Those are built in records . `#shared` has everything declared in the global environment, every function, every constant. `sections` is similar, it's like all your queries, excluding the global scope. ( For regular queries, PowerBI Only really exposes `sections1` )


- [You can use `#sections` to dynamically generate a summary of your queries](https://github.com/ninmonkey/ninMonkQuery-examples/tree/90f92a52fc1b093ab64588aa69fe5e975af2e236/Testing)

![queries](https://github.com/ninmonkey/ninMonkQuery-examples/blob/90f92a52fc1b093ab64588aa69fe5e975af2e236/Testing/img/Summarize%20%E2%81%9E%20Queries%20%E2%94%90main_query.png?raw=true)


### Useful links

- [helper functions](https://learn.microsoft.com/en-us/power-query/helper-functions) referenced in the examples

- [VS Code - Power Query SDK Addon](https://github.com/microsoft/vscode-powerquery-sdk)
- [VS Code - Power Query addon](https://github.com/microsoft/vscode-powerquery) (it comes with the sdk)
- [learn.microsoft.com/en-us/power-query/samples-directory#functionality](learn.microsoft.com/power-query/samples-directory)

- The [`/r/powerbi` Discord server](https://discord.gg/9StERjyPEY) has a `#powerquery` channel that's fairly active. Power BI and Power Query  and PowerShell <https://discord.gg/powershell>

**Comment by JasonWHowell** [comment]
Sounds like a hallucination by ChatGPT. The file hasn't ever been in the repo. working-with-external-libraries.md
Interesting topic indeed. I don't think there is anything actionable left to discuss, but let us know if you had doubts.
#please-close
