### ISSUE TITLE
Premium Per User (PPU) vs Premium Capacity

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#368]
I think this article needs to be adjusted to make it clear which Premium features work on PPU vs which ones work on Premium capacity.

From the article:

> Depending on the features you use, a Power BI Premium or embedded capacity is required.

IMO, this and similar notes may lead the reader to believe that PPU does not provide additional dataflow capabilities beyond Pro. 

Yet according to https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq PPU in fact supports all or some Premium capacity features.

I think the article needs to be revised to sort out this aspect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8621de12-aa62-856d-9930-bffecb4c934a
* Version Independent ID: b047c6a1-981f-0201-2823-eb82714d9188
* Content: [What licenses do you need to use dataflows - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/what-licenses-do-you-need-in-order-to-use-dataflows)
* Content Source: [powerquery-docs/dataflows/what-licenses-do-you-need-in-order-to-use-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/what-licenses-do-you-need-in-order-to-use-dataflows.md)
* Service: **powerquery**
* GitHub Login: @Luitwieler
* Microsoft Alias: **jeluitwi**

**Comment by Luitwieler** [comment]
Fixed in soon to be released PR :) Thanks for feedback!

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
The article you mentioned was updated earlier this year and now covers more information about what licenses are required. Closing this issue as fixed. #please-close
