### ISSUE TITLE
Dataflow management

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#369]
The entry for this feature in the table says "Power BI". 

Is this Pro or Premium? If both, can you please adjust the make it consistent with other entries?

Also, some entries say "Yes". Does this mean both Pro and Premium? If so, can you please adjust to make consistent?

Basically for every feature we need to know if it requires Pro, Premium or is not supported at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8621de12-aa62-856d-9930-bffecb4c934a
* Version Independent ID: b047c6a1-981f-0201-2823-eb82714d9188
* Content: [What licenses do you need to use dataflows - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/what-licenses-do-you-need-in-order-to-use-dataflows)
* Content Source: [powerquery-docs/dataflows/what-licenses-do-you-need-in-order-to-use-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/what-licenses-do-you-need-in-order-to-use-dataflows.md)
* Service: **powerquery**
* GitHub Login: @Luitwieler
* Microsoft Alias: **jeluitwi**

**Comment by Luitwieler** [comment]
Resolved in PR

**Comment by DougKlopfenstein** [comment]
@VitalyMCT 

I believe this has been resolved, so I'm closing the issue. If you believe there's still an issue, feel free to reopen this issue.
