### ISSUE TITLE
Language Spec - Types - Typos

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#37]
Hello, 

In the language grammar's section on [Types](https://docs.microsoft.com/en-us/powerquery-m/m-spec-types), I've run across a few typos:

1. The first bullet contains a list of primitive types which does not include `anynonnull`; however, the list of primitive types given [later on](https://docs.microsoft.com/en-us/powerquery-m/m-spec-types#primitive-types) includes this type. Based on this, it seems like `anynonnull` should be added to the list in the first bullet (if this is incorrect, then `anynonnull` probably should be removed from the list given later on).

2. Immediately after the first bulleted list, the following sentence appears to be missing a word or phrase:
    > The set of primitive types includes the types of primitive values a number of abstract types, types that do not uniquely classify any values: function, table, any, and none.

   Maybe it should read something like:
    > The set of primitive types includes the types of primitive values **and** a number of abstract types, **which are** types that do not uniquely classify any values **(** function, table, any, **anynonnull**, and none **)**.

3. The next paragraph states that "All types that are not members of the closed set of primitive types are collectively referred to as custom types." -- shouldn't this be "not members of the closed set of **nullable** primitive types"? Verbiage later in this section (e.g. in the discussion of [Type equivalence and compatibility](https://docs.microsoft.com/en-us/powerquery-m/m-spec-types#type-equivalence-and-compatibility) implies that nullable primitive types are _not_ custom types).

4. In the list of [Primitive Types](https://docs.microsoft.com/en-us/powerquery-m/m-spec-types#primitive-types), the second sentence in last bullet should be its own bullet item, as it describes a separate type.
.

Sincerely,
Ben

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by JasonWHowell** [comment]
This issue is pending PR #13 which is in review. 
#please-open
