### ISSUE TITLE
Incremental refresh: filter date column requirements should be specified

### ISSUE THREAD

**Issue by simplesi** [MicrosoftDocs/powerquery-docs#373]
The excellent incremental refresh functionality expects the filter date column to be unchanging, and essentially be something like transaction date or transaction post date. This is evident from the troubleshooting docs:

- https://learn.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-troubleshoot#cause-date-in-the-date-column-at-the-data-source-is-updated
- https://learn.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-troubleshoot#cause-post-dates-have-changed

However, this requirement isn't specified in the documentation up-front, and hence can easily be misunderstood (we made this mistake). Here's what the documentation says:
> Filter field drop-down: Selects the query field on which the entity should be filtered for increments. This field only contains DateTime fields. You can't use incremental refresh if your entity doesn't contain a DateTime field.

It would be easy to assume that incremental refresh can use a ModifiedOn datetime, which would then automatically work whenever any data is updated, for any date. This also appears to work when data is only ever modified during the incremental refresh window. However, it then fails and creates duplicate rows (in the archive partition and the incremental one) if data is updated after the incremental refresh period. I think this should be clearly specified up front.

In practice, incremental refresh works only when the filter date is never changed in the source data, and the update period is at most x days after that date.  Otherwise, there's either a primary key conflict, or updates are missed. For this reason, createdon or transaction date are good candidates, but modifiedon does not work.

As an aside: wouldn't it be nice to have an additional optional feature in incremental refresh which checked historical partitions's sources for detect data changes field being updated, and warned that changes had been made to historical data, and prompting the user to refresh (or even doing a refresh, at some defined interval). Then we could use a detect data changes field of modifiedon, and have it spot archive data changing, and update that dataset too, say weekly or monthly. This is what our existing ETL pipeline did to solve this problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffc816e2-78f6-ca70-92a3-b2153461759d
* Version Independent ID: e6fec9a8-1c47-b739-5146-0fa717c4535e
* Content: [Using incremental refresh with dataflows - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/incremental-refresh)
* Content Source: [powerquery-docs/dataflows/incremental-refresh.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/incremental-refresh.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @simplesi 
The information about the Filter field drop-down has been updated to require the use of an unchanging date field. Closing this issue as fixed.
