### ISSUE TITLE
What is the recommended approach?

### ISSUE THREAD

**Issue by tasranson** [MicrosoftDocs/powerquery-docs#374]
So you are clearly telling us not to use Microsoft Graph Security Connector, but what are the alternatives?  Surely a list of options of what to migrate to would be helpful to readers of this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c3291b5-08aa-d48f-b7d3-aba6175ff3e5
* Version Independent ID: 3ad1ab75-5c37-e524-e6f6-a619ba0d1b85
* Content: [Power Query Microsoft Graph Security connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/microsoft-graph-security)
* Content Source: [powerquery-docs/connectors/microsoft-graph-security.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/microsoft-graph-security.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
There's a page here that probably has the advice. We can link to it more clearly.
https://learn.microsoft.com/en-us/power-query/connecting-to-graph

**Comment by DougKlopfenstein** [comment]
Hi @tasranson 
Thanks for your feedback! The link discussed above was added to the Microsoft Graph Security connector article sometime last year. Therefore I'm closing this issue as fixed. #please-close
