### ISSUE TITLE
Improve information how to connect using SAS OLE DB 

### ISSUE THREAD

**Issue by hski-bayer** [MicrosoftDocs/powerquery-docs#376]
Would love if you could enhance the chapter about connecting to SAS via OLE DB powerquery-docs/connect-using-generic-interfaces.md.

We tried to connect to local SAS datasets via OLE DB and it was quite some learning to go through. Would be great for others, if you could add a hint, that for reading local SAS sas7bdat files, you can use the following OLE DB Connection String.

`Provider=SAS.LocalProvider.1; Data Source=c:\temp\MySasData`

See also here corresponding information in Power BI Ideas Portal. https://ideas.powerbi.com/ideas/idea/?ideaid=f9a367db-eab8-ed11-9ac5-501ac50aaf16

**Comment by JasonWHowell** [comment]
Not sure if it helps, but there are a lot of permutations of connection strings. Here is a site that lists many of them: https://www.connectionstrings.com/sas/

**Comment by hski-bayer** [comment]
Thanks for the hint. But that is not a real reference. It is just crawled stuff 😉. A true reference is SAS documentation. 

But it took us a while to understand we can use SAS LocalProvider, which nicely does not require any SAS server components to run and configure, because most of the documentation is about the SAS IOM server to connect via.

With SAS LocalProvider you just read file via SAS OLE components. Very simple and straightforward, hence worth to mention.

**Comment by JasonWHowell** [comment]
@hski-bayer what learn site page are you referring to? Re: "enhance the chapter"

**Comment by hski-bayer** [comment]
https://learn.microsoft.com/en-us/power-query/connect-using-generic-interfaces

**Comment by JasonWHowell** [comment]
@hski-bayer that page doesn't have a list of specific connection strings, and it's cumbersome to list all maintain them, so I can't sign up my team to start listing the many combinations. 

Would you be willing to make a quick post on the forum here and share the scenario with the community:  https://community.powerbi.com/t5/forums/postpage/board-id/power-bi-services

**Comment by DougKlopfenstein** [comment]
Hi @hski-bayer 
Thanks for your feedback. Since this issue hasn't been updated in almost a year, I'm going to close the issue. f you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
