### ISSUE TITLE
Typo on Page

### ISSUE THREAD

**Issue by cbschley** [MicrosoftDocs/powerquery-docs#381]
The following line has a typo:

9. Search for the "Refresh a dataflow" connector, and then select it.

it should say:

9. Search for the "Refresh a dataset" connector, and then select it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53048912-9c2a-1cae-4e9a-02cf79307e3c
* Version Independent ID: d21f1dab-c67e-2100-f11a-82d3ba6fda9b
* Content: [Trigger dataflows and Power BI datasets sequentially - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially)
* Content Source: [powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @cbschley 
Thanks for the feedback. The procedure being demonstrated in this article is following the first scenario listed at the top of the page - "Trigger the refresh of a standard dataflow after the successful completion of an analytical dataflow refresh." In this case, step 9 is correct, the procedure is refreshing a dataflow. 

I've added a task to update the article after the procedure to include more information about refreshing a dataset. That should make the article more complete.
