### ISSUE TITLE
PowerQuery SDK for VS or just VS Code?

### ISSUE THREAD

**Issue by bjmHAL** [MicrosoftDocs/powerquery-docs#383]
Can I use the PQ SDK with VS or just VS code? This tutorial uses VS. What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f268458b-0823-daa4-2a92-4cdde33534ad
* Version Independent ID: b4739249-2a91-a9d5-a4d2-4b325fea2029
* Content: [TripPin tutorial sequence - Power Query](https://learn.microsoft.com/en-us/power-query/samples/trippin/readme)
* Content Source: [powerquery-docs/samples/trippin/readme.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/samples/trippin/readme.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by ptyx507x** [comment]
The VS Code version is currently in public preview, but once it is generally available it'll replace the Visual Studio one. You could use either one, but we will keep this issue open and update this article with VS Code related images and instructions once it reaches general availability.

Thank you for your feedback!

**Comment by bjmHAL** [comment]
Thanks Miguel. To confirm, the public preview version for vs code is v0.2.2?




Brad McDonald
Sr. Manager, NAML Performance Analytics

Email: ***@***.******@***.***>
Mobile: +1 281-714-8455
Houston, TX, USA

[HALLIBURTON]<http://logw332.ati-host.net/gopc.url?xts=553058&xtor=EPR-25-%5bHAL-signatures%5d&url=http://www.halliburton.com>


From: Miguel Escobar ***@***.***>
Sent: Tuesday, March 14, 2023 11:16 AM
To: MicrosoftDocs/powerquery-docs ***@***.***>
Cc: Bradley McDonald ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/powerquery-docs] PowerQuery SDK for VS or just VS Code? (Issue #383)

External Sender: Use caution with links/attachments.


The VS Code version is currently in public preview, but once it is generally available it'll replace the Visual Studio one. You could use either one, but we will keep this issue open and update this article with VS Code related images and instructions once it reaches general availability.

Thank you for your feedback!

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerquery-docs%2Fissues%2F383%23issuecomment-1468405930&data=05%7C01%7Cbradley.mcdonald%40halliburton.com%7C86a39413a7074c4cf95508db24a7597f%7Cb7be76866f974db79081a23cf09a96b5%7C0%7C0%7C638144073401954626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vnbV975l2fCEPXAJptuABXxhzzS%2F6dTU7JU%2BoKzxA1o%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA6PT3GIM7UYQSOVZ3MO56QTW4CKSTANCNFSM6AAAAAAV2VB5UQ&data=05%7C01%7Cbradley.mcdonald%40halliburton.com%7C86a39413a7074c4cf95508db24a7597f%7Cb7be76866f974db79081a23cf09a96b5%7C0%7C0%7C638144073401954626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wImDuWXc4ktAVLRKPVGukEIbG2eq6OXAH3hiKmHfJ54%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

This e-mail, including any attached files, may contain confidential and privileged information for the sole use of the intended recipient. Any review, use, distribution, or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive information for the intended recipient), please contact the sender by reply e-mail and delete all copies of this message.

**Comment by ptyx507x** [comment]
That is correct. You can check it out on https://marketplace.visualstudio.com/items?itemName=PowerQuery.vscode-powerquery-sdk

**Comment by DougKlopfenstein** [comment]
The Power Query SDK for Visual Studio Code has gone GA and the documentation has been updated. 
#please-close
