### ISSUE TITLE
The deprecation note simple doesn't make sense. 

### ISSUE THREAD

**Issue by OscarValerock** [MicrosoftDocs/powerquery-docs#384]
The deprecation note simple doesn't make sense. 

![image](https://user-images.githubusercontent.com/60475729/225549236-f70fc3ee-598d-4389-9d81-e6377068da44.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c3291b5-08aa-d48f-b7d3-aba6175ff3e5
* Version Independent ID: 3ad1ab75-5c37-e524-e6f6-a619ba0d1b85
* Content: [Power Query Microsoft Graph Security connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/microsoft-graph-security)
* Content Source: [powerquery-docs/connectors/microsoft-graph-security.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/microsoft-graph-security.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
@OscarValerock thanks for the feedback. Would it help if we add a link to an alternative connector to use instead?

**Comment by OscarValerock** [comment]
I would write it like this: 

" This connector is deprecated. We recommend users explore alternative solutions for retrieving analytics data based on Graph, such as Microsoft Graph data connect. "

https://learn.microsoft.com/en-us/power-query/connecting-to-graph?source=recommendations

**Comment by JasonWHowell** [comment]
I think proposing the alternative approach is a good idea. Thanks Oscar

#assign:DougKlopfenstein

**Comment by DougKlopfenstein** [comment]
Hi @OscarValerock 
Thanks for the feedback!. The [Microsoft Graph Security (Deprecated)](https://learn.microsoft.com/power-query/connectors/microsoft-graph-security) article has been updated with your suggestions.

**Comment by OscarValerock** [comment]
Awesome! Thanks.
