### ISSUE TITLE
Is UnitTesting supported in Visual Studio Code's Power Query SDK

### ISSUE THREAD

**Issue by karunpoudel-chr** [MicrosoftDocs/powerquery-docs#385]
Some information about if UnitTesting is supported in Visual Studio Code code would be helpful because

I am getting "Cannot find name" error on
Fact and Facts

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77917fa1-4cab-b13f-c4d2-d50cbe329f3d
* Version Independent ID: 3d42574b-7213-c9a5-e5f9-0a825f760541
* Content: [TripPin 7 - Advanced Schema - Power Query](https://learn.microsoft.com/en-us/power-query/samples/trippin/7-advancedschema/readme)
* Content Source: [powerquery-docs/samples/trippin/7-advancedschema/readme.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/samples/trippin/7-advancedschema/readme.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Thanks @karunpoudel-chr for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. However, this appears to be product feedback or a request for product support. For information about product feedback or customer support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback). 

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
