### ISSUE TITLE
Power Query SDK Diagnostics

### ISSUE THREAD

**Issue by simon-r-watson** [MicrosoftDocs/powerquery-docs#387]
Would it be possible to have this updated for the VS Code version of the SDK? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8bd9a4-c553-2572-233d-b35acf75e42b
* Version Independent ID: 3bcd4a41-3552-cc3b-fac4-09691fc754a7
* Content: [TripPin 8 - Adding Diagnostics - Power Query](https://learn.microsoft.com/en-us/power-query/samples/trippin/8-diagnostics/readme)
* Content Source: [powerquery-docs/samples/trippin/8-diagnostics/readme.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/samples/trippin/8-diagnostics/readme.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by ptyx507x** [comment]
hey!

Thank you for your feedback. We should be hitting GA with the VS Code SDK pretty soon. Once we reach GA we will be updating all the articles to reflect the way how things should be done in VS Code.

We'll keep this issue open and close it once this is addressed.

Thanks!

**Comment by DougKlopfenstein** [comment]
The Power Query SDK for Visual Studio Code has gone GA and the documentation has been updated. 
#please-close
