### ISSUE TITLE
SQL Server Failover Support

### ISSUE THREAD

**Issue by propellor** [MicrosoftDocs/powerquery-docs#399]
I am looking for information regarding the SQL Server Failover Support option for the SQL Server connection to know what it does.  From my testing, it is sending ApplicationIntent=ReadOnly which causes the query to be passed to a SQL AG read-only replica. You might add this information if it is true. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e77b6456-8d48-b1fc-cba3-993d1f8d5cae
* Version Independent ID: 0ca84a81-e16e-a2f7-1cac-00082cf0d86b
* Content: [Power Query SQL Server connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/sql-server)
* Content Source: [powerquery-docs/connectors/sql-server.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/sql-server.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @propellor 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
