### ISSUE TITLE
More confusing than insightful

### ISSUE THREAD

**Issue by ACDAX** [MicrosoftDocs/powerquery-docs#4]
May I suggest that this resource is updated for clarification. Generally the information is more confusing than insightful.

We hit quota limitations using Data Integration within the Power Platform Admin Portal while moving data from CDS to Dynamics 365 Finance and Operations.
As of writing there is currently no way (that I know of) to see API limits and query quotas against Actual usage (per user) in the Analytics section in the Power Platform Admin Portal or anywhere else for that matter.
Also, I don’t see any mention of such insights in the 2020 Dynamics 365 Release Plan, though, more telemetry features are to be added throughout 2020.

I have therefore raised this as an Idea for the Power Platform Product Team, please vote if you would like to see this feature.
https://experience.dynamics.com/ideas/idea/?ideaid=f8207ec8-554e-ea11-b698-0003ff689f0d

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3faffe45-9b88-7ca0-4fb9-1eaac7859baa
* Version Independent ID: 1781cb1b-0976-62e1-3060-7e3fdcd96225
* Content: [Power Query Online Usage Limits](https://docs.microsoft.com/en-us/power-query/power-query-online-limits#feedback)
* Content Source: [powerquery-docs/power-query-online-limits.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/power-query-online-limits.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by cpopell** [comment]
Hi ACDAX, I've raised this as a suggestion with the product group. Unfortunately there is no way to see your quota today--I'll see if I can rephrase things.
