### ISSUE TITLE
Language Specification - #shared clarification

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#40]
Hello,

In the language specification's section on Sections, [#shared](https://docs.microsoft.com/en-us/powerquery-m/m-spec-sections#shared) is described as follows:

> The #shared intrinsic variable returns a record containing the names and values of all shared section members currently in scope.

From the testing I've done, `#shared` contains all shared section members _as well as_ all members defined directly (i.e. outside of a section) in the global scope (e.g. the standard library).

### Examples

* Given a Power Query section document containing a single section named "Section1" having a single (shared) member named "Query1", the results returned by `#shared` will include `Query1` as well as almost 800 other entries corresponding with the names defined by the standard library.
* ````Expression.Evaluate("#shared", [Test = 123])```` returns a record listing "Test" as its sole field even though no sections exist in the evaluated environment (e.g. `````Record.FieldCount(Expression.Evaluate("#sections", [Test = 123]))```` returns 0).

### Suggestion

Could the above-quoted paragraph be revised to something like:

> > The #shared intrinsic variable returns a record containing the names and values of all shared section members currently in scope and of all members defined directly in the global scope.

Thank you,
Ben

**Comment by JasonWHowell** [comment]
This issue seems to be about this page:
- URL: https://docs.microsoft.com/en-us/powerquery-m/m-spec-sections
- Source: https://github.com/MicrosoftDocs/query-docs/blob/main/query-languages/m/m-spec-sections.md

@bgribaudo if you have time and are willing, feel free to propose the change in the public repo. Thanks much, Jason
#please-open

**Comment by bgribaudo** [comment]
Resolved by the linked PR.
