### ISSUE TITLE
Connect Power BI to Azure Blob Storage Account 

### ISSUE THREAD

**Issue by Friedduc** [MicrosoftDocs/powerquery-docs#400]
[Enter feedback here]
There is a note which states that PBI service must be located in the same region as the Blob Storage account in order for PBI to connect. This does not seem to be accurate since PBI should be able to connect to Blob Storage accounts in different regions. If this note is referring to the use of an Azure trial account, then it would be best to change the wording to point this out.

![image](https://user-images.githubusercontent.com/45743037/230673518-9534f79e-66be-43bf-afb9-1f1298b076c9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a352aea-fca9-8a16-f5f7-533244f037ef
* Version Independent ID: 4a352aea-fca9-8a16-f5f7-533244f037ef
* Content: [Azure Blob Storage - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/azure-blob-storage)
* Content Source: [powerquery-docs/connectors/azure-blob-storage.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/azure-blob-storage.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @Friedduc 
Thanks for providing feedback that helps improve our documentation. This issue has been resolved and we are closing the issue. #please-close
