### ISSUE TITLE
Verbiage is ambiguous with regards to linked dataflows

### ISSUE THREAD

**Issue by michaelweissDM** [MicrosoftDocs/powerquery-docs#408]
Verbiage is ambiguous with regards to linked dataflows.  Does the person utilizing the dataflow require view/member permissions in both the source work space and target work space or just the target work space?

Thanks for your assistance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 694206b9-4a15-727a-d8e0-20be04dcbc3e
* Version Independent ID: 06baf623-5afc-6396-956b-f4bb97a04eeb
* Content: [Best practices for reusing dataflows across environments and workspaces - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/best-practices-reusing-dataflows)
* Content Source: [powerquery-docs/dataflows/best-practices-reusing-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/best-practices-reusing-dataflows.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @michaelweissDM 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
