### ISSUE TITLE
Please add more information about AAD

### ISSUE THREAD

**Issue by kenakamu** [MicrosoftDocs/powerquery-docs#41]
First of all, thanks for great tool and information. I see you have AAD authentication option here, but it is not clear how to use it. Is it just to get authentication? Could you provide more detail example how to use against services such as Graph?

And it seems "Type" doesn't work but instead I need to specify "Resource". But I coudn't find a way to specify "scope"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58e66f41-e084-8f8a-8828-12474f21f0d7
* Version Independent ID: 77eafe80-5569-eee6-042e-e425a9056570
* Content: [Handling authentication for Power Query connectors](https://docs.microsoft.com/en-us/power-query/handlingauthentication)
* Content Source: [powerquery-docs/HandlingAuthentication.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/HandlingAuthentication.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by cpopell** [comment]
Hi Kenichiro,

We're hoping to provide some information about using Graph soon, but I don't have a promise as to when. It's more complex and has some limitations we need to work out.
________________________________

**Comment by kenakamu** [comment]
Thanks for quick reply. I understand it, then i will use OAuth for now.

**Comment by DougKlopfenstein** [comment]
Using Graph is no longer recommended in Power Query. For more information, go to [Lack of Support for Microsoft Graph in Power Query](https://docs.microsoft.com/power-query/connecting-to-graph).

If you need more information, please reopen this issue.
