### ISSUE TITLE
A list of DirectQuery required/supported for Power BI data sources

### ISSUE THREAD

**Issue by RyusukeGondo** [MicrosoftDocs/powerquery-docs#411]
[Enter feedback here]

In the previous document, the DirectQuery required/supported list of Power BI data sources was available on the Power BI data source page, but now that it has been integrated into the Power Query connector list, you have to go to each connector's detail page to see the information, which is very inconvenient. I would like to see a list of DirectQuery required/supported for Power BI data sources.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72df40f2-3c58-cbda-79ec-c65ba5cc32ac
* Version Independent ID: ab483b41-107f-2027-c65f-63285a847c63
* Content: [List of all Power Query connectors - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/?source=docs)
* Content Source: [powerquery-docs/connectors/index.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/index.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @RyusukeGondo 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
