### ISSUE TITLE
Correct 3rd image

### ISSUE THREAD

**Issue by bmtorres** [MicrosoftDocs/powerquery-docs#416]
Hi,

Could you check the 3rd image of this page? It's the one showing the use of computed entity. The image shows the source entity as the computed entity, when it should actually show the 2 entities on the right as the computed entities.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 016cc5b0-e90e-c87e-874f-d71cc5d740b8
* Version Independent ID: 486eeb0a-d69d-3a9a-f17d-10482de0dcf2
* Content: [Computed entity scenarios and use cases - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/computed-entities-scenarios?source=docs)
* Content Source: [powerquery-docs/dataflows/computed-entities-scenarios.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/computed-entities-scenarios.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @bmtorres 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
