### ISSUE TITLE
Confused about the translation table

### ISSUE THREAD

**Issue by mhennemuth** [MicrosoftDocs/powerquery-docs#420]
Hi ,

in the article you showing in the translation table in the from column "mike" translating in the To column to "Miguel" and "William" translating to "Bill". In the result picture of the table, you then show mike correctly translating to Miguel, but then Bill translating to William ???! Should this not show "Bill" ?

Plese explain, I am not been able to get this translation table function to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d60d874-f2be-3d00-cabd-9810e7e7a415
* Version Independent ID: 5ebfbeba-7e11-0a28-5fcd-a63670914d47
* Content: [Cluster values - Power Query](https://learn.microsoft.com/en-us/power-query/cluster-values#using-the-fuzzy-cluster-options)
* Content Source: [powerquery-docs/cluster-values.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/cluster-values.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @mhennemuth 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We have added this task to our list of documentation updates, and the new information about fuzzy matching should be coming online in the next couple of months.

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
