### ISSUE TITLE
No MSI for Postgres Downloads

### ISSUE THREAD

**Issue by fritz3000g** [MicrosoftDocs/powerquery-docs#428]
[Enter feedback here]
Your installation instructions say to find an MSI file to install the plugin from this page.  https://github.com/npgsql/Npgsql/releases

However, none of the installation downloads there contain an MSI file.  How do I install this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82f05c74-8262-6610-bd9e-efe4f112bbe1
* Version Independent ID: 09570cd3-3a8b-18c6-da4c-46beada3a387
* Content: [Power Query PostgreSQL connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/postgresql)
* Content Source: [powerquery-docs/connectors/postgresql.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/postgresql.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @fritz3000g 
Go to the NpgSQL provider release page (the link in the article), search for v4.0.10, and download and run the .msi file.

**Comment by DougKlopfenstein** [comment]
Hi @fritz3000g 
Thanks for the feedback! The [PostgreSQL](https://learn.microsoft.com/power-query/connectors/postgresql) article has been updated with the relevant information about finding the NpgSQL provider v4.0.10.
