### ISSUE TITLE
Invalid code sample

### ISSUE THREAD

**Issue by kpuls** [MicrosoftDocs/powerquery-docs#429]
The "Basic" code sample on this page does not compile when copied to Power Query (in either Excel or Power BI). It flags a Token Eof expected on the shared keyword in line 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a834875-02f7-683d-5845-618a5d02d888
* Version Independent ID: 36b3e58d-e580-a9fd-4239-7d51b24fdeb6
* Content: [Adding function documentation - Power Query](https://learn.microsoft.com/en-us/power-query/handling-documentation)
* Content Source: [powerquery-docs/handling-documentation.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/handling-documentation.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by kpuls** [comment]
Just to follow up on this... I am starting to think that this code sample is dependent on a specific project.  I would FAR prefer to see something that shows a standalone example which doesn't require a specific sample file to work.  Something that shows how to add a simple description to a custom function (maybe just add two numbers) and provide documentation for the input fields.

**Comment by DougKlopfenstein** [comment]
Hi @kpuls 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
