### ISSUE TITLE
Function reference on navigation table

### ISSUE THREAD

**Issue by zebrassimo** [MicrosoftDocs/powerquery-docs#43]
Hi Microsoft support,

could you please amend the referenced document with an example on how to return a function with parameters correctly from a navigation table? The example 
`{"MyFunction", "myfunction", AnotherFunction.Contents(),       "Function", "Function", true}`
is nice, but how do you return a function with parameters? 

Thanks and greets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e5bc95e-99a6-0d05-b3d5-c064daa417d0
* Version Independent ID: dfb79a5a-5419-44dc-389a-f4e46b5247c6
* Content: [Handling navigation for Power Query connectors](https://docs.microsoft.com/en-us/power-query/handlingnavigationtables)
* Content Source: [powerquery-docs/HandlingNavigationTables.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/HandlingNavigationTables.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @zebrassimo 
The current navigation table topic is in the process of being updated. In the meantime, you can find out how to return a function with parameters by going to [Invoke a function from a navigation table](https://github.com/microsoft/DataConnectors/issues/30).
