### ISSUE TITLE
Updating 'column profiling based on top 1000 rows' to column profiling based on the entire dataset in Power BI.

### ISSUE THREAD

**Issue by jeremiahomueti** [MicrosoftDocs/powerquery-docs#430]
[The explanation on how to update 'Column Profiling based on top 1000 rows' to the entire dataset is not clear. How exactly do I make the profiling based on the entire dataset? Kindly assist thanks. https://learn.microsoft.com/en-us/power-query/data-profiling-tools]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 003c71f8-2874-f664-fa87-8759f571107b
* Version Independent ID: d96c778a-06ba-1ca9-4e74-45df237bd048
* Content: [Using the data profiling tools - Power Query](https://learn.microsoft.com/en-us/power-query/data-profiling-tools)
* Content Source: [powerquery-docs/data-profiling-tools.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/data-profiling-tools.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @jeremiahomueti 
Thanks for the feedback! The method for changing between "Column profiling based on top 1000 rows" and "Column profiling based on entire data set" has been added to the first note in [Using the data profiling tools](https://learn.microsoft.com/en-us/power-query/data-profiling-tools).

**Comment by jeremiahomueti** [comment]
Cool. So I made Microsoft update its documentation. Nice :-)

Thanks for your careful attention to this matter.

Regards @DougKlopfenstein
