### ISSUE TITLE
no use

### ISSUE THREAD

**Issue by Didiermaignan** [MicrosoftDocs/powerquery-docs#433]
We nned a full list of errors and solutions for PQ online.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da00712f-d3f7-babf-f82a-138d4906150d
* Version Independent ID: ea0aae05-0e7f-4b65-8026-b03a851f212a
* Content: [Troubleshoot dataflow issues - creating dataflows - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/troubleshooting-dataflows-issues-creating-dataflow)
* Content Source: [powerquery-docs/dataflows/troubleshooting-dataflows-issues-creating-dataflow.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/troubleshooting-dataflows-issues-creating-dataflow.md)
* Service: **powerquery**
* GitHub Login: @Luitwieler
* Microsoft Alias: **jeluitwi**

**Comment by DougKlopfenstein** [comment]
Hi @Didiermaignan 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
