### ISSUE TITLE
Power BI Web.Content documentation(s) should mention that only anonymous authentication method is supported with POST requests

### ISSUE THREAD

**Issue by jikuja** [MicrosoftDocs/powerquery-docs#434]
Power BI Web.Content documentation should mention that only anonymous authentication method is supported with POST requests.

Power Query M function [reference](https://learn.microsoft.com/en-us/powerquery-m/web-contents) mentions following: `POST requests may only be made anonymously.`

Reported  [page](https://learn.microsoft.com/en-us/power-query/connectors/web/web-troubleshoot) and connector [overview](https://learn.microsoft.com/en-us/power-query/connectors/web/web) fail to mention this limitation. This limitation should be mentioned. Now both pages have a table that lists all supported authentication methods but does not mention exception for POST requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7136b5-122b-0e0e-8992-926ee09a5da8
* Version Independent ID: 6179e1c3-b6dc-5b3a-c748-a948afb77870
* Content: [Troubleshooting the Power Query Web connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/web/web-troubleshoot)
* Content Source: [powerquery-docs/connectors/web/web-troubleshoot.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/web/web-troubleshoot.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @jikuja 
Thanks for your feedback! Notes have been added to the Web overview and troubleshooting pages indicating that POST commands when using Web.Contents can only be made anonymously.
