### ISSUE TITLE
These instructions don't work

### ISSUE THREAD

**Issue by HAL9000ape** [MicrosoftDocs/powerquery-docs#436]
These instructions don't work because there is no "Transform" tab 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa9fd82-71d1-0a3f-4034-f9b5f48f544c
* Version Independent ID: 5ae72e59-d997-d53d-12ac-92285918acb8
* Content: [Promote or demote column headers - Power Query](https://learn.microsoft.com/en-us/power-query/table-promote-demote-headers)
* Content Source: [powerquery-docs/table-promote-demote-headers.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/table-promote-demote-headers.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **miescobar**

**Comment by HAL9000ape** [comment]
... group, not tab. There is no Transform group.

**Comment by DougKlopfenstein** [comment]
Hi @HAL9000ape 
Thanks for the feedback! What app are you using to get to Power Query? Is it Power BI Desktop, Excel, Power BI service, Power Apps, Customer Insights, Analysis Services, or something else? I've checked all of the above, and when Power Query is invoked from any of them, there's a Transform group under the Home tab.

**Comment by HAL9000ape** [comment]
I am using Excel. Here's what
![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/138730401/77943c55-9c48-41fd-8b1e-6071cd984ff6)
 I see on the Home tab.

**Comment by HAL9000ape** [comment]
And, I don't see an option for Transform in the Customize the Ribbon pop up window:

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/138730401/4b612e84-1112-4126-a3c1-4499c0b7bcd4)

**Comment by DougKlopfenstein** [comment]
Hi @HAL9000ape 
The **Transform** tab is in the Power Query editor ribbon, not the Excel ribbon. You have to select the **Data** tab in the Excel ribbon, select **Get data**, select what data you want to connect to, connect to the data, select the data you want to use, and then select **Transform data**. This opens the Power Query editor, which contains the **Transform** tab.

For example:

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/40473364/95ec8c74-d1bc-464c-9819-b0e89c89bbe2)

In this case, text/csv is selected, so File Explorer is opened and you select a text or csv file and then select **Import**.

The imported data looks like this:

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/40473364/bc2fa131-68f6-40f7-945a-af60946f423e)

Once you select **Transform data**, the Power Query editor opens. You now have access to the **Transform** tab.

If you've already got data loaded into Excel, you can also access the Power Query editor by selecting the **Data** tab in the Excel ribbon, then **Get data**, and then select **Launch Power Query Editor**. This will load your current data into Power Query editor, and you can then use the **Transform** tab.

Let me know if this answers your question. If so, I'll close this issue. Thanks.

**Comment by HAL9000ape** [comment]
Yes! ok. Thank you. As soon as I saw your post, the bell rang in my head. I've got it now. 

Thanks again!
