### ISSUE TITLE
Add a column for direct query

### ISSUE THREAD

**Issue by bwt615** [MicrosoftDocs/powerquery-docs#439]
Telling people to go into each connector to determine is one of the laziest things I have ever seen.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72df40f2-3c58-cbda-79ec-c65ba5cc32ac
* Version Independent ID: ab483b41-107f-2027-c65f-63285a847c63
* Content: [List of all Power Query connectors - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/)
* Content Source: [powerquery-docs/connectors/index.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/index.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @bwt615 
Thanks for the feedback. Currently we are only able to supply a limited amount of information in each table, so we are investigating ways to expand the table building process for our documentation. For the time being, the information about DirectQuery will need to remain in the individual connector articles while we come up with a viable solution.
