### ISSUE TITLE
Mention tracing in the quick start

### ISSUE THREAD

**Issue by tonyhallett** [MicrosoftDocs/powerquery-docs#44]
Instead of relying upon a developer to read through the walkthroughs to get to [Adding diagnostics](https://docs.microsoft.com/en-us/power-query/samples/trippin/8-diagnostics/readme) just mention that it needs to be turned on in the project properties in the quick start

**Comment by DougKlopfenstein** [comment]
Hi @tonyhallett -
Information about enabling diagnostics was added to the [TripPin tutorial overview](https://docs.microsoft.com/en-us/power-query/samples/trippin/readme). If you have any other suggestions about this information's location, you can reopen this feedback.
