### ISSUE TITLE
What about Excel for the web?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerquery-docs#440]
The product table should include Excel Online, since that product is getting closer and closer to Desktop parity.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9b1e7c-616b-87e0-7858-7f9e83b69ea5
* Version Independent ID: 5ffba9ae-ac08-3375-df06-507e7b6336f3
* Content: [What is Power Query? - Power Query](https://learn.microsoft.com/en-us/power-query/power-query-what-is-power-query)
* Content Source: [powerquery-docs/power-query-what-is-power-query.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-what-is-power-query.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @otravers 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
