### ISSUE TITLE
Google sheet connector is missing

### ISSUE THREAD

**Issue by NishRan** [MicrosoftDocs/powerquery-docs#441]
From yesterday the Google sheet connector is missing in my PowerBi Desktop. 

I re-installed powerBI today and the new version is 2.119.986.0 64-bit (July 2023) but the connector is still missing..

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/141194504/2a36d08d-b49a-4d92-aafc-037b58403058)

**Comment by DougKlopfenstein** [comment]
Hi @NishRan 

Thank you for your feedback.

This seems to be product feedback or a request for product support. In this case, please direct those queries to the [Power BI product forum](https://community.fabric.microsoft.com/t5/Power-Query/bd-p/power-bi-services).
