### ISSUE TITLE
there is no When a dataflow refresh completes

### ISSUE THREAD

**Issue by kent-culpepper** [MicrosoftDocs/powerquery-docs#442]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09b19bcc-dc9d-62c4-0093-815839ef54a5
* Version Independent ID: c9228618-2fb9-52b4-d813-e3c79411d82b
* Content: [Send a notification when a dataflow refresh completes - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/send-notification-when-dataflow-refresh-completes)
* Content Source: [powerquery-docs/dataflows/send-notification-when-dataflow-refresh-completes.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/send-notification-when-dataflow-refresh-completes.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @kent-culpepper 
Thanks for the feedback.

Could you be more specific about what you mean? Does the dataflow refresh never complete? Is there no notification when the dataflow refresh completes? Are the instructions incomplete or wrong?

Thanks.

**Comment by kent-culpepper** [comment]
the ms support documentation suggests using a connector\event that doesnt
exist.
https://learn.microsoft.com/en-us/power-query/dataflows/send-notification-when-dataflow-refresh-completes
Step #3, search for the "When a dataflow refresh completes" connector

And at this time there is now way that i can find that can send a
notification @ Power apps (canvas app) that informs the user that the
dataflow refresh actually completed. how is an end-user to know when it
completed besides sitting there repeatedly refreshing the gallery.

koherint.com | 201-424-1584
<http://voice.google.com/calls?a=nc,%2B12014241584> | my-calendar
<https://calendly.com/kent-culpepper>

**Comment by DougKlopfenstein** [comment]
Hi @kent-culpepper 
Not sure why you're not seeing the "When a dataflow refresh completes". I tested the procedure just now, and step 3 produces:
![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/40473364/e79576a3-dfd8-4fa5-af08-356046c6646b)

You might want to go to the [Power Apps forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1) and ask why you're not seeing this connector. Or contact your Microsoft support contact (if applicable).

Since this doesn't seem to be a documentation issue, I'll close this issue. I'll wait a couple of days to do so in case you want to add more information about the documentation.

**Comment by kent-culpepper** [comment]
Yes, you are correct. I see the same. I was wanting to add this step in a
flow where the dataflow actually refreshes. I guess I am not understanding
how this works.
In my mind, the end-user is triggering the Flow from the power apps client
interface, which executes the dataflow and then when it completes, it
informs the end-user it has completed successfully (the <Respond to a
PowerApp or flow> doesnt really do anything in this scenario, cause it
notifies the user even though the dataflow hasnt completed).

[image: image.png]

koherint.com | 201-424-1584
<http://voice.google.com/calls?a=nc,%2B12014241584> | my-calendar
<https://calendly.com/kent-culpepper>

**Comment by DougKlopfenstein** [comment]
Hi @kent-culpepper 
That appears to be more of a programming issue than a documentation issue. You probably need to get in contact with the [Power Apps forum](https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1) I mentioned above where someone who has more experience with Power Apps could answer your questions.

**Comment by kent-culpepper** [comment]
No not really. You have a step to refresh a data flow and you have a step
to inform the user the data flow completed. Pretty straight-forward. My
report was that the step wasn't avail, which it's not, which may or may not
be consistent with the doc (I'll let you figure that out). What is avail,
is the trigger, so I'll see how I work with that.

**Comment by DougKlopfenstein** [comment]
Hi @kent-culpepper 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
