### ISSUE TITLE
Potential solution for the Hyphens issue

### ISSUE THREAD

**Issue by estheban** [MicrosoftDocs/powerquery-docs#444]
Based on Snowflake documentation (https://docs.snowflake.com/en/sql-reference/identifiers-syntax#double-quoted-identifiers)
The solution can be as simple as allowing double quote in the database name.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38e8eb21-ce6a-dae6-8a93-a68659aedd30
* Version Independent ID: 112cbadd-b770-66af-a3d8-7291c157e9c2
* Content: [Power Query Snowflake connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/snowflake#hyphens-in-database-names)
* Content Source: [powerquery-docs/connectors/snowflake.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/snowflake.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @estheban 
The workaround that you describe here won't work because the ODBC driver is the one talking to Snowflake and it needs to do the quoting for identifiers with ‘-‘ characters. Until we upgrade that driver, there is no workaround.
#please-close
