### ISSUE TITLE
Unit testing code fails to serialize some emojis

### ISSUE THREAD

**Issue by tonyhallett** [MicrosoftDocs/powerquery-docs#45]
Given below as per [code used in this doc page](https://github.com/microsoft/DataConnectors/blob/master/samples/UnitTesting/UnitTesting.query.pq)
```
shared MyExtension.UnitTest =
[
    OkIcon = "👌",
    BugIcon = "🐛",
    facts =
    {        
        Fact("ValueToText cannot serialize emojis",
             BugIcon,
             OkIcon
        )
        
    },

    report = Facts.Summarize(facts)
][report];
```
The result is.
![image](https://user-images.githubusercontent.com/11292998/86347596-6b33fd00-bc56-11ea-8cf5-7c97a519ce0c.png)

[Character.ToNumber](https://github.com/microsoft/DataConnectors/blob/9f41d48cc9e9910d21c24c98c30f57716861bca1/samples/UnitTesting/UnitTesting.query.pq#L180) errors.

You could try the List.Accumulate and fallback to x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb462f4-eb4d-452d-9362-68cdd02c4849
* Version Independent ID: 655a3731-84be-1378-77b0-1e5d8c0b2006
* Content: [Handling unit testing for Power Query connectors](https://docs.microsoft.com/en-us/power-query/handlingunittesting)
* Content Source: [powerquery-docs/HandlingUnitTesting.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/HandlingUnitTesting.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by cpopell** [comment]
Hi Tony, we'll take it down as a bug. Hopefully this isn't blocking you.
