### ISSUE TITLE
Please add the generated M-Code

### ISSUE THREAD

**Issue by ronrosenfeld** [MicrosoftDocs/powerquery-docs#454]
Showing the generated `M-Code` on this Table.AddRankColumn (preview) article would be most helpful, especially since this method has yet to be added to the User Interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c68853a-27ba-b029-8667-630f0ec5d248
* Version Independent ID: 4c68853a-27ba-b029-8667-630f0ec5d248
* Content: [Rank column (Preview) - Power Query](https://learn.microsoft.com/en-us/power-query/rank-column)
* Content Source: [powerquery-docs/rank-column.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/rank-column.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by ptyx507x** [comment]
hi!
Thank you for the feedback. For M functions and documentation related to concepts of the M language we have a separate repo. Here's a direct link to the documentation of the Table.AddRankColumn function:
https://learn.microsoft.com/en-us/powerquery-m/table-addrankcolumn

The current rank feature is only available in Power Query Online as noted in the article, but it will come to Power Query in Excel for Windows and Power BI Desktop in the future.

Given that the pattern of the formula created by the feature could potentially change or be tweaked depending on the underlying context or future changes to the UX of the product, we typically do not document the functions or the formula pattern that gets generated by a particular feature.  Nevertheless, I will pass this feedback to the rest of the team and will take it into consideration.

Thanks!

**Comment by ronrosenfeld** [comment]
Thank you.
That article only shows the M-Code for a single column. I ran into some issues in trying to adapt it to multiple columns with different sort orders, hence my question. However, I seem to have it working now.

Ron
