### ISSUE TITLE
Data Import Entity Failure

### ISSUE THREAD

**Issue by zambubu** [MicrosoftDocs/powerquery-docs#456]
Facing this error when I try to import a Purchase Requisition entity from D365FO
![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/99586409/f5862c67-e673-4070-9c4f-64e972cc628c)

The following Screenshot shows that the type of column is auto changed upon uploading data file, but the following query doesn't unfold. Can somebody share the reason behind this? Maybe I am overlooking some steps.
Your valuable input would be much appreciated. 

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/99586409/8c024eff-1de1-404f-bc86-8fe295414cf1)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 670f76a2-bea6-6a5a-f2c2-b70473aafdc9
* Version Independent ID: a11aac61-513e-b4d2-96b0-bbcd56342bde
* Content: [Query folding indicators in Power Query - Power Query](https://learn.microsoft.com/en-gb/power-query/step-folding-indicators)
* Content Source: [powerquery-docs/step-folding-indicators.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/step-folding-indicators.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by ptyx507x** [comment]
Hi!

For specific scenario-related questions, we encourage you to use the Community Forum: https://aka.ms/DataFactoryCommunity

Answering the question directly, not all connectors and not all data sources support query folding. In this case it appears that you're connecting to a source (Excel file) that doesn't support query folding whatsoever, so the query folding indicators are reflecting that.

**Comment by ptyx507x** [comment]
#close

**Comment by zambubu** [comment]
Hi @ptyx507x 

Sure, I will direct my query there. However, can you help me spot the reason for it failing at folding? As it's just an ordinary file with no access restrictions on it.

Thank you so much for your kind assistance.

**Comment by DougKlopfenstein** [comment]
Hi @zambubu 
Thanks for your feedback. This is a site for discussing documentation feedback. To get support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback).
