### ISSUE TITLE
Dataflow per table - size limit

### ISSUE THREAD

**Issue by sha-k-anand** [MicrosoftDocs/powerquery-docs#458]
This document does not call out if there is any maximum size limit for a single dataflow table.   

If there is no max size limit, can you please update the documentation to indicate that there is no size limit exist for a single dataflow table.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3faffe45-9b88-7ca0-4fb9-1eaac7859baa
* Version Independent ID: 1781cb1b-0976-62e1-3060-7e3fdcd96225
* Content: [Power Query Online Usage Limits - Power Query](https://learn.microsoft.com/en-us/power-query/power-query-online-limits)
* Content Source: [powerquery-docs/power-query-online-limits.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-online-limits.md)
* Service: **powerquery**
* GitHub Login: @Luitwieler
* Microsoft Alias: **jeluitwi**

**Comment by DougKlopfenstein** [comment]
Hi @sha-k-anand 
Thanks for providing feedback that helps improve our documentation. We've added information to the article that indicates there is no max size limit to a single dataflow table, but that a timeout might occur if the table is too big, and the workaround if that error occurs.
#please-close
