### ISSUE TITLE
Table.ChangeType helper function doesn't handle nullable records properly

### ISSUE THREAD

**Issue by joefields** [MicrosoftDocs/powerquery-docs#461]
I am getting errors on Record type objects when I try to apply a schema in my custom connector even though I have added the nullable type identifier.

The below example shows whenever I have location = null, it throws an error.
![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/40640733/b0bc7676-8a3a-4b26-a413-21ffc460d21b)

Here is a condensed listing of how I am defining my schema in my PQ file:
```
ProjectType = type table [
...
    location = nullable LocationType,
...],
    LocationType = type [
        country = text,
        state = text,
        streetName = text,
        streetNumber = text,
        suite = text,
        city = text,
        zip = text,
        complete = text,
        coords = nullable CoordsType
    ]
``` 
I have defined location as being a nullable record however I get an error whenever I get a nullable record.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63706099-f414-4f48-165d-a3609437a37e
* Version Independent ID: 1807dacc-1bf2-79aa-70b1-bebd2f2c6331
* Content: [Helper functions for M extensions for Power Query connectors - Power Query](https://learn.microsoft.com/en-us/power-query/helper-functions)
* Content Source: [powerquery-docs/helper-functions.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/helper-functions.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @joefields 
Thanks for the feedback. This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
