### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by GermanPearls** [MicrosoftDocs/powerquery-docs#462]
don't is spelled do'nt in 2nd note

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1dca0d08-2e42-b068-eb45-4361fb4adb69
* Version Independent ID: 81697507-1e10-463f-5757-6fa14cc3a54d
* Content: [Power Query Oracle database connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/oracle-database)
* Content Source: [powerquery-docs/connectors/oracle-database.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/oracle-database.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
Seems like you've fixed it https://github.com/MicrosoftDocs/powerquery-docs/pull/463/files
Thank you so much! 
#please-close
