### ISSUE TITLE
View Native Query does not appear for SharePoint Odata

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerquery-docs#464]
per this article, it lists that odata data sources including SharePoint lists support query folding, however, when viewing the applied steps for filtering a SharePoint Odata list, it does not show the native query.

Should the article be updated to reflect how to do this, or should it be revised to remove that SharePoint lists as odata sources do not support query folding? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba36059-c3f8-d871-c45c-6425979e82d2
* Version Independent ID: a7662d1d-5915-a921-711c-8e8085419ff0
* Content: [Query folding - Power Query](https://learn.microsoft.com/en-us/power-query/power-query-folding)
* Content Source: [powerquery-docs/power-query-folding.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-folding.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by GitWesDone** [comment]
Check the validity of this clause "These data sources can include relational databases, OData feeds (including SharePoint lists)"  specifically "OData feeds (including SharePoint lists)".  This is the second sentence in the section "[Sources that support folding](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-folding.md#sources-that-support-folding)" This clause makes clear that SharePoint Lists Odata feeds support.  However, SharePoint List Odata data sources do not appear to support query folding.  Either the article should describe how sharepoint list odata data sources support query folding, or that clause should be removed.

**Comment by JasonWHowell** [comment]
@gitWeDone this part might help. Do you see that it's folding by checking the Query Diagnostics?

> The View Native Query option is only available for certain relational DB/SQL generating connectors. It doesn't work for OData based connectors, for example, even though there is folding occurring on the backend. The Query Diagnostics feature is the best way to see what folding has occurred for non-SQL connectors (although the steps that fold aren't explicitly called out—you just see the resulting URL that was generated).

**Comment by DougKlopfenstein** [comment]
@GitWesDone  We are closing this issue for now due to lack of engagement for the last several months. However, if you feel that it's still a concern, please respond and let us know.
#please-close
