### ISSUE TITLE
When do you expect the code will be available in the desktop version of power query?

### ISSUE THREAD

**Issue by Christianwhen** [MicrosoftDocs/powerquery-docs#468]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c68853a-27ba-b029-8667-630f0ec5d248
* Version Independent ID: 4c68853a-27ba-b029-8667-630f0ec5d248
* Content: [Rank column (Preview) - Power Query](https://learn.microsoft.com/en-us/power-query/rank-column)
* Content Source: [powerquery-docs/rank-column.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/rank-column.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @Christianwhen 
This seems to be product feedback or a request for product support. For information about product feedback or customer support for Power Query, go to [Power Query feedback](https://community.fabric.microsoft.com/t5/Power-Query/bd-p/power-bi-services).
