### ISSUE TITLE
Perhaps we should align with Power BI Article for best practices

### ISSUE THREAD

**Issue by bensack** [MicrosoftDocs/powerquery-docs#47]
See: https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-best-practices

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76bbffdf-18f6-9001-b75a-57aedc1dcfe0
* Version Independent ID: 928761e0-8e55-c01f-9228-7ee5d2971d52
* Content: [Best practices around designing and developing complex dataflows](https://review.docs.microsoft.com/en-us/power-query/dataflows/best-practices-developing-complex-dataflows?branch=pq-df-first-batch)
* Content Source: [powerquery-docs/dataflows/best-practices-developing-complex-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/dataflows/best-practices-developing-complex-dataflows.md)
* Service: **powerquery**
* GitHub Login: @radacad
* Microsoft Alias: **v-rerad**

**Comment by rootsmusic** [comment]
@bensack, I think you're referring to Power BI's doc at https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-best-practices

**Comment by DougKlopfenstein** [comment]
This has been done. See [Dataflows best practices](https://docs.microsoft.com/power-bi/transform-model/dataflows/dataflows-best-practices). Most links now go to Power Query best practices content.
