### ISSUE TITLE
Lack of clarity on licensing entitlements

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/powerquery-docs#470]
This article mentions Dynamics 365 Customer Insights and then later references "Dynamics 365 applications" for entitled license use with Dataflows. It's not clear if all Dynamics 365 licenses come with entitlements to use Dataflows or not. The Power Platform and Dynamics 365 licensing guides do not contain any details on this either. Please add content to help clarify if all Dynamics 365 licenses come with entitlements to use Dataflows.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2653ddba-9221-f7b0-1437-9c7602cc0ade
* Version Independent ID: 52479bdb-4832-07d8-1610-f43f8b2e4f3a
* Content: [An overview of dataflows across Microsoft Power Platform and Dynamics 365 products - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/overview-dataflows-across-power-platform-dynamics-365)
* Content Source: [powerquery-docs/dataflows/overview-dataflows-across-power-platform-dynamics-365.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/overview-dataflows-across-power-platform-dynamics-365.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @rrwolfe 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
