### ISSUE TITLE
Adobe Analytics connector hyperlink misdirections

### ISSUE THREAD

**Issue by joaoneves22** [MicrosoftDocs/powerquery-docs#476]
Under the "Limitations and issues" section of the page, last two paragraphs, the hyperlinks take you to completely different pages in the Adobe site.

Best practices takes you to a generic intro page - https://www.adobe.io/apis/experiencecloud/analytics/docs.html#!AdobeDocs/analytics-2.0-apis/master/reporting-guide.md

Recommended usage guidelines takes you to a product comparison page - https://experienceleague.adobe.com/docs/analytics/analyze/admin-overview/analytics-product-comparison.html?lang=en

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84ad828d-df05-53f0-b699-f4f8acdda29b
* Version Independent ID: f3cf3f07-7dc1-b721-2c1b-a4041f873400
* Content: [Power Query Adobe Analytics connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/adobe-analytics#limitations-and-issues)
* Content Source: [powerquery-docs/connectors/adobe-analytics.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/adobe-analytics.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @joaoneves22 
Thanks for the feedback. The links have been updated.
