### ISSUE TITLE
Groupby documentation

### ISSUE THREAD

**Issue by kwajpaige** [MicrosoftDocs/powerquery-docs#478]
Hi,
I went through this documentation and had toimprovise my way through the Groupby instructions. It might be my mistakes but just wanted to let you know that the documentation and screenshots provided did not work.....
Paige

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de794a3c-1a2b-ea25-a5ee-9f5e2486dc79
* Version Independent ID: d0ee45da-d64f-d594-bfa4-1b7f371646e3
* Content: [The Power Query user interface - Power Query](https://learn.microsoft.com/en-us/power-query/power-query-ui)
* Content Source: [powerquery-docs/power-query-ui.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-ui.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @kwajpaige 
Thanks for your feedback!
The entire Power Query user interface article has been updated and tested to ensure that all of the procedures performed as expected, including the Group by instructions.
