### ISSUE TITLE
Language Spec - Add Null coalescing operator (??)

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#48]
Power Query supports a null coalescing operator (`??`); however, this isn't mentioned in the language specification. Could it be added to the spec?

Example:
````
let
    A = null,
    B = 123
in
    A ?? B // returns 123
````

More Details: https://social.technet.microsoft.com/Forums/en-US/180757fe-47c0-4377-bb04-9cccadf4537b/null-coalescing-operator-?forum=powerquery

Thank you,
Ben

**Comment by DougKlopfenstein** [comment]
Hi @bgribaudo -
Thanks for the feedback. Information about the null coalescing operator has been added to the Power Query M formula language documentation.

**Comment by bgribaudo** [comment]
Thank you, @DougKlopfenstein!
