### ISSUE TITLE
examples should never have only one output row

### ISSUE THREAD

**Issue by spikerobinsonDLG** [MicrosoftDocs/powerquery-docs#480]
[Enter feedback here]

It's very unhelpful to have examples where the merge produces only a row  of output. This is conceptually unhelpful because the output of any merge is a table, not  a row. It will be unclear to many readers, especially those that are learning (and who need the most help) that a single row is a special case of a table. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 300640a1-3076-a508-5efb-00c1ed0dafe9
* Version Independent ID: a9493005-087b-5dff-80b3-622a8f9b54d7
* Content: [Right anti join - Power Query](https://learn.microsoft.com/en-us/power-query/merge-queries-right-anti)
* Content Source: [powerquery-docs/merge-queries-right-anti.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/merge-queries-right-anti.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @spikerobinsonDLG 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
