### ISSUE TITLE
Analytical dataflow storage encryption

### ISSUE THREAD

**Issue by clintonbale** [MicrosoftDocs/powerquery-docs#481]
Do Analytical Dataflows with `Dataverse provided Azure Data Lake storage for Power Platform dataflows` use the [customer managed keys](https://learn.microsoft.com/en-us/power-platform/admin/customer-managed-key) configured in that Dataverse environment to encrypt the Data Lake storage? 

I cannot find documentation on this anywhere and my support ticket has been unanswered for weeks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c08c29a4-99c2-69ca-6bcd-75541c697215
* Version Independent ID: 0516d7ae-4cf4-a5e7-d20a-e3839ecf6120
* Content: [Understanding the differences between dataflow types - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/understanding-differences-between-analytical-standard-dataflows)
* Content Source: [powerquery-docs/dataflows/understanding-differences-between-analytical-standard-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/understanding-differences-between-analytical-standard-dataflows.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @clintonbale 
Thanks for the feedback. Sorry that this question has taken so long to answer. Yes, analytical dataflows with Dataverse provided Azure Data Lake storage for Power Platform dataflows use the customer managed keys configured in that Dataverse environment to encrypt the Data Lake storage. Dataverse managed data lakes that use customer managed keys just work for dataflows.
