### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by ImkeF** [MicrosoftDocs/powerquery-docs#482]
[Enter feedback here]
The condition value "False" will not work. It must be "Failed" instead.
Also, it might be more economic to move this condition directly into the trigger condition so the flow only shoots if the dataflow actually failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1b1dbb-f8cb-a205-2069-ae3e664b7947
* Version Independent ID: 4f9e2c85-b57f-d75f-66ae-7e34257e5f87
* Content: [Open a ticket when a dataflow refresh fails - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/open-support-ticket-when-dataflow-refresh-completes)
* Content Source: [powerquery-docs/dataflows/open-support-ticket-when-dataflow-refresh-completes.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/open-support-ticket-when-dataflow-refresh-completes.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @ImkeF 
Thanks for your feedback! The condition value has been changed to "Failed" and the change is now live.
#please-close
