### ISSUE TITLE
Which ODBC Sources resp. Drivers are supported without Gateway?

### ISSUE THREAD

**Issue by MartinBubenheimer** [MicrosoftDocs/powerquery-docs#483]
I'd like to see a list or a reference to a list which ODBC drivers are supported by the cloud service without using an On Premise Gateway. Eben if the data source is accessible for the cloud, this does not necessarily mean that the type of data source is supported an I need a Gateway to have a machine where I can install the ODBC driver.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5508060-9aad-0c1c-12e1-952f053db469
* Version Independent ID: dedf3aab-565d-d42c-065c-e674feeb2bea
* Content: [Power Query ODBC connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/odbc#prerequisites)
* Content Source: [powerquery-docs/connectors/odbc.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/odbc.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @MartinBubenheimer 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
