### ISSUE TITLE
GetPage doesn't handle records with different field names

### ISSUE THREAD

**Issue by TBemrose** [MicrosoftDocs/powerquery-docs#484]
Issue
===
The function `GetPage` assumes every record has the same field names as the first record. It will:
* Ignore any fields not present in the first record, but present in subsequent ones.
* Enter any subsequent records as a row of `Error` if that record doesn't have a field present in the first record.

Solution
===
`GetPage` needs updated to add the `allFieldNames` line (and update the `data` line accordingly) as below.

Add:
---
`allFieldNames = List.Distinct(List.Combine(List.Transform(body[value], Record.FieldNames))),`

Replace:
---
~`data = Table.FromRecords(body[value])`~
`data = Table.FromRecords(body[value], allFieldNames, MissingField.UseNull)`

Result:
---
```
GetPage = (url as text) as table =>
    let
        response = Web.Contents(url, [ Headers = DefaultRequestHeaders ]),        
        body = Json.Document(response),
        nextLink = GetNextLink(body),
        allFieldNames = List.Distinct(List.Combine(List.Transform(body[value], Record.FieldNames))),
        data = Table.FromRecords(body[value], allFieldNames, MissingField.UseNull)
    in
        data meta [NextLink = nextLink];
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4867f9e3-aed1-7c2b-294e-cac264664a90
* Version Independent ID: a34a9995-0668-5574-a44a-753df829b31d
* Content: [TripPin 5 - Paging - Power Query](https://learn.microsoft.com/en-us/power-query/samples/trippin/5-paging/readme)
* Content Source: [powerquery-docs/samples/trippin/5-paging/readme.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/samples/trippin/5-paging/readme.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @TBemrose 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
