### ISSUE TITLE
Table.GenerateByPage doesn't handle pages with different column names

### ISSUE THREAD

**Issue by TBemrose** [MicrosoftDocs/powerquery-docs#485]
Issue
===
The function `Table.GenerateByPage` assumes every page has the same column names as the first page. It will:
* Ignore any columns not present in the first page, but present in subsequent ones.

Solution
===
`Table.GenerateByPage` needs updated to add the `allColumnNames` line (and update the `Value.ReplaceType` line accordingly) as below.

* Replace the `Value.ReplaceType` line with a let-in block.
* The `Value.ReplaceType` line goes in the 'in' section.
* The 'let' section contains the `allColumnNames` line below.

`allColumnNames = List.Distinct(List.Combine(List.Transform(firstRow[Column1], Table.ColumnNames)))`

* Within `Value.ReplaceType`, update the `Table.ExpandTableColumn` line as below.

~`Table.ExpandTableColumn(tableOfPages, "Column1", Table.ColumnNames(firstRow[Column1])),`~
`Table.ExpandTableColumn(tableOfPages, "Column1", allColumnNames),`

Result:
---
```
// The getNextPage function takes a single argument and is expected to return a nullable table
Table.GenerateByPage = (getNextPage as function) as table =>
    let        
        listOfPages = List.Generate(
            () => getNextPage(null),            // get the first page of data
            (lastPage) => lastPage <> null,     // stop when the function returns null
            (lastPage) => getNextPage(lastPage) // pass the previous page to the next function call
        ),
        // concatenate the pages together
        tableOfPages = Table.FromList(listOfPages, Splitter.SplitByNothing(), {"Column1"}),
        firstRow = tableOfPages{0}?
    in
        // if we didn't get back any pages of data, return an empty table
        // otherwise set the table type based on the columns of the first page
        if (firstRow = null) then
            Table.FromRows({})
    // check for empty first table
        else if (Table.IsEmpty(firstRow[Column1])) then
            firstRow[Column1]
        else
            let
                allColumnNames = List.Distinct(List.Combine(List.Transform(firstRow[Column1], Table.ColumnNames)))
            in
                Value.ReplaceType(
                    Table.ExpandTableColumn(tableOfPages, "Column1", allColumnNames),
                    Value.Type(firstRow[Column1])
                );
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63706099-f414-4f48-165d-a3609437a37e
* Version Independent ID: 1807dacc-1bf2-79aa-70b1-bebd2f2c6331
* Content: [Helper functions for M extensions for Power Query connectors - Power Query](https://learn.microsoft.com/en-us/power-query/helper-functions#tablegeneratebypage)
* Content Source: [powerquery-docs/helper-functions.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/helper-functions.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by TBemrose** [comment]
Hey @bgribaudo / @DougKlopfenstein, I just saw your messages. Heh, it has been a while and I had to think for a while to recall what I was pointing out. I no longer have access to the project I was working on when I discovered the issue, but reading over my message I can tell what I was trying to say, though I see with fresh eyes that I wasn't very clear.

I was making use of the custom / non-built-in function `Table.GenerateByPage` defined here:
https://learn.microsoft.com/en-us/power-query/helper-functions#tablegeneratebypage

While using it, I encountered an issue where expected columns were missing from my final table. I tracked down the issue to the fact that, those columns weren't in the first page of data (the oldest data), but were present in later pages (newer data tracked more than the older data). I fixed the issue and to save other users who copy the function from that page, from having to do the debugging I did, I propose my fix be incorporated into the definition/example on that page.

I've enclosed a screenshot of a comparison between the original and my update. You can see in line 22 of the original, that it just gets the column names by `Table.ColumnNames(firstRow[Column1])`, which only extracts the column names from the first page. We need `allColumnNames` for `Table.ExpandTableColumn`. Prior to that line, I added this one:
`allColumnNames = List.Distinct(List.Combine(List.Transform(firstRow[Column1], Table.ColumnNames)))`

If I'm reading it correctly, it takes `Column1` as a list (of pages) and iterates down the pages applying `Table.ColumnNames` to each page, then it combines all the results, and trims it down to distinct names. The resulting `allColumnNames` is then passed into `Table.ExpandTableColumn`.

Reviewing this now, I'm unsure if I missed something. The final parameter passed into `Table.ExpandTableColumn` is `Value.Type(firstRow[Column1])` (line 23 originally, line 26 in my update). Without access to that project, just reading that it's not immediately clear to me whether `Value.Type` is getting type metadata about `Column1` itself or whether it would just get the type metadata from the first page in `Column1` like `Table.ColumnNames` does. If it's the later, the column types from each page should be aggregated while `allColumnNames` is being built (each type sticking with its column name so we don't have any working out to do after `List.Distinct` gets rid of duplicates.

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/32970876/d0be0e55-642b-4f2d-aa60-5592b5462c03)

**Comment by bgribaudo** [comment]
Thanks for the follow-up, @TBemrose!

If I'm understanding your solution correctly, it's reading all API pages before returning the first page's worth of rows in order to get the full column list (full as in across all pages). 

However, there's a catch. :-) This approach can add quite a bit of cost to using the connector. Say the user does a `Table.TopN(Source, 1)` on the connector's output. To keep with Power Query's "only do as much work as needed" philosophy, it would be desirable that only the first results page be fetched from the API to satisfy this request. If all pages have to be read to output 1 row, quite a bit of "over reading" could occur.

If the only way you can come up with the expected column list is by reading all pages from the API, you might just have to do that—but this approach wouldn't be generally applicable to all custom connectors.

If you know the expected column list in advance, maybe you could adapt the version of this function that you are using so that it takes that list as an optional argument. That way, you avoid this possible cause of over reading pages!
