### ISSUE TITLE
onSelectedRows tutorial announcement has been removed. It is very much needed.

### ISSUE THREAD

**Issue by fmms** [MicrosoftDocs/powerquery-docs#49]
Hi,

18d9733a61107947fcc6079966bbcdcbd50bd04a was committed today and removed the sentence that a tutorial implementing onRowsSelected will be published.

I am very much looking forward for the next part. Could you please publish this or release a demo connector where one sees the `onSelectedRows` in action.

@DougKlopfenstein  was that intentionally? 

regards

**Comment by DougKlopfenstein** [comment]
Hi @fmms -

Unfortunately, this information is not going to be added to the documentation anytime soon. However, the [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback) lists several places you can go to ask questions about connectors (including custom connectors).
