### ISSUE TITLE
Incremental refresh for computed entities

### ISSUE THREAD

**Issue by cool-Blue** [MicrosoftDocs/powerquery-docs#496]
Can you please add a note about best practice for incremental refresh, when using the recommmended two-layer architecture, of seperate extract and transform dataflows?  Is there any advantage in using incremental refresh in the transformation dataflow and, if so, should the partitions be aligned in any way?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76bbffdf-18f6-9001-b75a-57aedc1dcfe0
* Version Independent ID: 928761e0-8e55-c01f-9228-7ee5d2971d52
* Content: [Best practices for designing and developing complex dataflows - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/best-practices-developing-complex-dataflows)
* Content Source: [powerquery-docs/dataflows/best-practices-developing-complex-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/best-practices-developing-complex-dataflows.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @cool-Blue 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
