### ISSUE TITLE
Insufficient Permission Diagnostic

### ISSUE THREAD

**Issue by GeneCCC947** [MicrosoftDocs/powerquery-docs#5]
When trying  to either  "Start Diagnostics" or "Diagnose Step" a Diagnostic window appears that says "Insufficient permissions while starting the diagnostic listener. Consider running elevated."  What does this mean and how do I proceed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85b2f2aa-3c25-3d7f-4cea-3bcbcbddbfda
* Version Independent ID: eba64268-4667-6c01-0d73-5071c032acbd
* Content: [Query Diagnostics](https://docs.microsoft.com/en-us/power-query/QueryDiagnostics#feedback)
* Content Source: [powerquery-docs/QueryDiagnostics.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/QueryDiagnostics.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by cpopell** [comment]
You need to either run as administrator, or install the February version of Power BI and enable the following in options

[cid:image004.png@01D5E73A.BC3CAC70]

﻿
--
Colin Popell
Senior Program Manager
Data Integration
Office: (425) 706-9843 X69843
gepopell@microsoft.com<mailto:gepopell@microsoft.com>
[Microsoft]

**Comment by cpopell** [comment]
Sigh, image didn't attach over email.

https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-february-2020-feature-summary/#_Data_prep Instructions are here.
