### ISSUE TITLE
Missing limitation for linked entities

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerquery-docs#50]
Reading this documentations limitation, you might think that it's possible to use M parameters to adress the linked entity, but according to a support case to MS, automated refresh then does't happend and this is by design. Then this shall also be listed as an limitation for linked entities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 474d74d7-1c4b-310e-e381-c5ef6de14f65
* Version Independent ID: d8532777-57e4-51b1-306f-29cd3178bfda
* Content: [Link entities between dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/linked-entities)
* Content Source: [powerquery-docs/dataflows/linked-entities.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/dataflows/linked-entities.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @erapade -
Thanks for your feedback. This limitation has been added to the limitation list.
