### ISSUE TITLE
Lakehouse connector not visible

### ISSUE THREAD

**Issue by schofiep** [MicrosoftDocs/powerquery-docs#503]
In my Fabric Trial environment the Fabric Lakehouse connector is not visible
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4bcc52c-fd62-970a-0d7d-bc179018cb6e
* Version Independent ID: c4bcc52c-fd62-970a-0d7d-bc179018cb6e
* Content: [Power Query Lakehouse (Beta) connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/lakehouse#connect-to-a-lakehouse-from-power-query-online)
* Content Source: [powerquery-docs/connectors/lakehouse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/lakehouse.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **dougklo**

**Comment by DougKlopfenstein** [comment]
Hi @schofiep 
This appears to be a customer support issue rather than a documentation issue. For information about customer support for Microsoft Fabric, go to [Microsoft Fabric support](https://support.fabric.microsoft.com/en-US/support/).
