### ISSUE TITLE
Issues and Limitations should include the fact that Power Query caching is broken on macOS

### ISSUE THREAD

**Issue by MushyMiddle** [MicrosoftDocs/powerquery-docs#505]
On macOS Excel, you get exactly one shot at a query to an OData source.  From then on, OData has ignored the various Cache-Control headers, and will never re-query the source.

It doesn't matter if you close Excel, open a new sheet, etc.  The OData endpoint can be queried in other tools with no issue, e.g. Postman.

Fundamentally, Power Query is simply broken on macOS.  Unlike on Windows, on macOS Excel, there is no way to clear the cache, and since the Excel cache ignores any directives to *not cache* information (standard on OData), you are forever stuck with stale or dead data on macOS Excel.

FWIW, I have confirmed this behavior using tcpdump.  Once a query succeeds once, no further queries to the same endpoint will retrieve data, no matter what you do in Excel (restart, new sheets, etc.).

On the other hand, if there *is* a way to clear the cache on macOS Excel, feel free to document that feature, but other posts on this issue indicate that Microsoft is aware of the problem, with no plan to fix it.  OK, then document it, please.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a619085-d6e2-14ee-f78c-0d6bae7d6e18
* Version Independent ID: 2de6483e-cceb-51c6-9604-80001b61946d
* Content: [Power Query OData Feed connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/odata-feed)
* Content Source: [powerquery-docs/connectors/odata-feed.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/odata-feed.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **dougklo**

**Comment by JasonWHowell** [comment]
@mushymiddle sounds like you have done some great testing to study and form the assessment about the caching on MacOs.

Could you send that feedback to the community support for further discussion, and maybe they can track a bug for the product team to further investigate?  Here: https://powerusers.microsoft.com/t5/Power-Query/bd-p/PA_PowerQuery

We're not at a point where we can confidently document it, which is what this feedback site is used for.
Thanks, Jason

**Comment by DougKlopfenstein** [comment]
Hi @MushyMiddle 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Because there has been no followup for this issue, we are closing this issue for now. If you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
