### ISSUE TITLE
ARG connector and Lighthouse

### ISSUE THREAD

**Issue by pthomas848** [MicrosoftDocs/powerquery-docs#508]
Does the ARG connector support the scope of a lighthouse query?  I know native ARG supports Lighthouse, but I'm not sure how to set the scope of the query in Power BI to encompass the child subscriptions data using  https://techcommunity.microsoft.com/t5/azure-governance-and-management/azure-resource-graph-x-power-bi-is-finally-here/ba-p/3981207.
thanks for your time

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd6b034-1753-6368-19d9-bb699a24b768
* Version Independent ID: 5b80c524-3870-f774-e4cd-950e56da9653
* Content: [Power Query feedback - Power Query](https://learn.microsoft.com/en-us/power-query/feedback)
* Content Source: [powerquery-docs/feedback.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/feedback.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @pthomas848 
This seems to be product feedback or a request for product support. For information about connector support or feedback, go to [Power Query connector feedback](https://learn.microsoft.com/power-query/connectors/connector-feedback) and scroll down to "Microsoft-owned connectors".
