### ISSUE TITLE
Changes to recurrence are not saved

### ISSUE THREAD

**Issue by MartinPiccinini** [MicrosoftDocs/powerquery-docs#510]
When I try to modify the recurrence of the trigger in the Power Automate edit mode I can change the parameters, but the changes are not saved once I exit edit even though I pressed on the save button.

Specifically this section

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/76134315/03bd63b9-c094-4c5a-a29a-a575752f36c1)

and I see the changes in the code view

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/76134315/260aaf34-8a0e-4e63-bc7c-b0e3bba8f7e1)

But after I save and exit edit mode it reverts to the default which is 5 minutes and no timeZone or startTime at all

I have verified this behavior when the Flow runs and the time it takes to trigger the action that I have designated

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09b19bcc-dc9d-62c4-0093-815839ef54a5
* Version Independent ID: c9228618-2fb9-52b4-d813-e3c79411d82b
* Content: [Send a notification when a dataflow refresh completes - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/send-notification-when-dataflow-refresh-completes)
* Content Source: [powerquery-docs/dataflows/send-notification-when-dataflow-refresh-completes.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/send-notification-when-dataflow-refresh-completes.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @MartinPiccinini 
This seems to be product feedback or a request for product support rather than a documentation issue. For information about product feedback or customer support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback).
