### ISSUE TITLE
The default value for workforce pool id appears to be impossible

### ISSUE THREAD

**Issue by galactic-north** [MicrosoftDocs/powerquery-docs#514]
From the documentation:  "The format for the Audience Uri value is //iam.googleapis.com/locations/global/workforcePools/\<workforce pool ID\>/providers/azuread. The default value for the \<workforce pool ID\> is powerquery-\<TenantId\>, where \<TenantId\> is your current Power BI tenant ID."

Workforce pool IDs are 32 characters max, while Azure tenant IDs are a GUID containing 36 characters (32 hexadecimal digits separated by 4 hyphens), making the workforce pool ID "powerquery-\<TenantId\>" impossible.

Am I misunderstanding the intended default value for workforce pool ID?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dfb55340-4ee9-4726-2a24-1232e189f289
* Version Independent ID: dfb55340-4ee9-4726-2a24-1232e189f289
* Content: [Google BigQuery (Azure AD) (Beta) - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/google-bigquery-aad)
* Content Source: [powerquery-docs/connectors/google-bigquery-aad.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/google-bigquery-aad.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **dougklo**

**Comment by DougKlopfenstein** [comment]
Thanks @galactic-north for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. However, this appears to be product feedback or a request for product support. For information about customer support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback). 

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
