### ISSUE TITLE
comma separate value https://www.commadelimitedonline.com/

### ISSUE THREAD

**Issue by maliksaleem** [MicrosoftDocs/powerquery-docs#515]
[i like to use this site is it safe https://www.commadelimitedonline.com/?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4e3bb11-ba2a-382e-febd-676b430d7fe0
* Version Independent ID: a194eff4-786b-92cd-7d69-dfc2cc1948f8
* Content: [Split columns by delimiter - Power Query](https://learn.microsoft.com/en-us/power-query/split-columns-delimiter)
* Content Source: [powerquery-docs/split-columns-delimiter.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/split-columns-delimiter.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @maliksaleem 
This seems to be product feedback or a request for product support rather than a documentation issue. For information about product feedback or customer support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback).
