### ISSUE TITLE
Where to invoke NavigationTable.Simple function?

### ISSUE THREAD

**Issue by thekrut** [MicrosoftDocs/powerquery-docs#52]
It would be great if you add a link to a page which explains how/where to invoke the NavigationTable.Simple function to show this dialog in Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e5bc95e-99a6-0d05-b3d5-c064daa417d0
* Version Independent ID: dfb79a5a-5419-44dc-389a-f4e46b5247c6
* Content: [Handling navigation for Power Query connectors](https://docs.microsoft.com/en-us/power-query/handlingnavigationtables)
* Content Source: [powerquery-docs/HandlingNavigationTables.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/HandlingNavigationTables.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
This has been done - see https://docs.microsoft.com/power-query/handlingnavigationtables#flat-navigation-table.
