### ISSUE TITLE
linked-tables.md states linked tables don't copy or duplicate data

### ISSUE THREAD

**Issue by JTDotNet** [MicrosoftDocs/powerquery-docs#529]
Article states that 'linked tables simply point to the tables in other dataflows, and don't copy or duplicate the data'. As per [this question](https://community.fabric.microsoft.com/t5/Service/Dataflows-linked-table-refreshes-in-different-workspaces/m-p/3838621#M229359) it appears that linked tables that are in different workspaces to their sources likely do copy or duplicate data - this should be clarified

**Comment by DougKlopfenstein** [comment]
Hi @JTDotNet 
Thanks for the feedback! The sentence in [Link tables between dataflows](https://learn.microsoft.com/power-query/dataflows/linked-tables) has been updated.
#please-close
