### ISSUE TITLE
Quickbooks version vs Quickbooks Online

### ISSUE THREAD

**Issue by yang2k** [MicrosoftDocs/powerquery-docs#53]
Currently Power BI only supports US editions of QuickBooks Online

Is this still the case if only US editions of Quickbooks Online can work now?

How about the Reckon Account Hosted Edition ? 
Many thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4c81dc-0503-5134-ddaf-2ce3e166b52d
* Version Independent ID: e4e84344-d034-5f1f-9739-7623e311672f
* Content: [QuickBooks Online](https://docs.microsoft.com/en-nz/power-query/connectors/quickbooksonline)
* Content Source: [powerquery-docs/Connectors/QuickBooksOnline.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/QuickBooksOnline.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **v-douklo**

**Comment by DougKlopfenstein** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the application-specific support site (in this case, the [Power BI support site](https://powerbi.microsoft.com/support/)).
