### ISSUE TITLE
Common Data Model folder view not supported in Power Query Online

### ISSUE THREAD

**Issue by rajrao** [MicrosoftDocs/powerquery-docs#56]
Power Query Online, does not seem to support "Common Data Model" folder view and that distinction I think would be good to call out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de89bef7-dbd7-c901-d329-f9838f8dbaf9
* Version Independent ID: 583cc4ae-3fdb-0d6c-6314-8aaf8e51e922
* Content: [Analyze data in Azure Data Lake Storage Gen2 by using Power BI](https://docs.microsoft.com/en-us/power-query/connectors/datalakestorage)
* Content Source: [powerquery-docs/Connectors/DataLakeStorage.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/DataLakeStorage.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @rajrao -
This feature was introduced in February 2021.
