### ISSUE TITLE
Missing note on limitation of parameters supported for Standard Gateway

### ISSUE THREAD

**Issue by migueesc123** [MicrosoftDocs/powerquery-docs#57]
Parameter types supported in the standard gateway are only text, number, and/or anynonnull. Any other data types will result in the custom connector not being visible in the data source kind list in the Power BI service.

The article is missing this critical caution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc2464b-1d4c-3fe7-1375-c95b791fe312
* Version Independent ID: 5f142ea5-c08a-eb02-de68-41dccdefb141
* Content: [Gateway Support for Power Query connectors](https://docs.microsoft.com/en-us/power-query/handlinggatewaysupport)
* Content Source: [powerquery-docs/HandlingGatewaySupport.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/HandlingGatewaySupport.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
There's already a discussion about this change in internal email, and a pull request has been written regarding this change. Because of these ongoing discussions, I'm closing this issue - to be resolved internally. #please-close
