### ISSUE TITLE
please could you clarify this page a bit

### ISSUE THREAD

**Issue by cxputcm** [MicrosoftDocs/powerquery-docs#6]
Hi Guys, I can get up to the stage where I get an authenticaiton URL but no further. is there any chance you could edit the page to include a screenshot of the full and final code required in Power Query. When I try to add the "token response" block of code its showing an EOF error and no matter how I try to restructure the code I cant get it to work. Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6f55e2-dc4a-c0ac-296b-c41d02bea7f5
* Version Independent ID: 767b1dbc-dd20-f5cd-7afa-bdd17458c233
* Content: [Microsoft Graph tutorial for Power Query](https://docs.microsoft.com/en-us/power-query/samples/mygraph/readme#feedback)
* Content Source: [powerquery-docs/samples/MyGraph/README.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/samples/MyGraph/README.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by alex-v-ivanov** [comment]
When we call the exchange token function (TokenMethod in the example above) we must pass a client_secret as header. Pay attention, it's unsafe if you want to share your connector with other people.

**Comment by dynamicapps** [comment]
The full code is at https://github.com/microsoft/DataConnectors/tree/master/samples/MyGraph.
I haven't been able to get it to work as it gets authentication errors.

**Comment by cpopell** [comment]
Hi all,

This sample isn't working because the underlying structure, etc., changed - we're hoping to get a fixed walkthrough up but it requires some more work.
________________________________

**Comment by dynamicapps** [comment]
Thanks @cpopell,
Are you aware of any way for us to get AAD users and groups information into PowerBI that works and can refresh with PBI Service?  We want to do RLS by group instead of user.

**Comment by cpopell** [comment]
@dynamicapps  I'm not aware of any off hand. @mattmasson might know.

**Comment by WillShea** [comment]
Thanks for looking at this.  I have been struggling with it the last couple of days.   Any idea when you might get this tutorial updated?   Kind of a pressing need for us.   Also I've noticed that the full code sample available on the github site seems more complete.   I'm going to give that version a try to see if that gets me any further.   Thanks for your work on this.   It is much needed since MS broke the ability to use Oauth to access Graph API.   Thx.

**Comment by WillShea** [comment]
@dynamicapps there is a cludgy workaround that I have put in place until I can get this connector working.   I've used Get-MsolUser to get Azure AD users and their properties to do an extract to csv file and then connected to that in Power BI.

**Comment by BakkerJan** [comment]
@dynamicapps @willshea take a look at this: https://janbakker.tech/2020/05/09/use-graph-api-data-in-power-bi-using-logicapps/

**Comment by dynamicapps** [comment]
Thanks, @BakkerJan .  I was hoping not to have to use a proxy, but it's definitely an option.

**Comment by rootsmusic** [comment]
@mattmasson This issue's doc (content) no longer exists.

**Comment by DougKlopfenstein** [comment]
Closed because all mention of using Graph in Power Query has been removed from the documentation.
