### ISSUE TITLE
No reply from dataconnectors@microsoft.com

### ISSUE THREAD

**Issue by ramalho-tiago** [MicrosoftDocs/powerquery-docs#60]
Hi there,

We have been trying to get an answer from Microsoft on how to certify a connector. So far there has been no reply. First email sent 07/09/2020. Is the email address still active?

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24df4b38-33ae-90a7-f8ba-24d49641bd9e
* Version Independent ID: c5e1aa54-cefb-61d3-7536-1ea73a2d3090
* Content: [Connector Certification](https://docs.microsoft.com/en-us/power-query/connectorcertification)
* Content Source: [powerquery-docs/ConnectorCertification.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/ConnectorCertification.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @ramalho-tiago  To certify a custom connector, you first need to complete our [registration form](https://forms.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR2DcOSp0ibhKolmfRqZYZ51UN1MzQ0ZYNVlIMUM4MUQ1SUpPTEo3SFg1VC4u). To find out everything you need to know about certifying a connector, go to [Power Query Connector Certification](https://docs.microsoft.com/power-query/connectorcertification).
