### ISSUE TITLE
Wording is Incorrect

### ISSUE THREAD

**Issue by kurtwz** [MicrosoftDocs/powerquery-docs#62]
[Enter feedback here]

Passage reads: "If the View Native Query option is not enabled (greyed out), this is evidence that **all query steps cannot be folded.** However, it could mean that a subset of steps can still be folded." 

Passage should read: "If the View Native Query option is not enabled (greyed out), this is evidence that **not all query steps can be folded.** However, it could mean that a subset of steps can still be folded." 

Thanks,

Kurt 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba36059-c3f8-d871-c45c-6425979e82d2
* Version Independent ID: a7662d1d-5915-a921-711c-8e8085419ff0
* Content: [Query folding](https://docs.microsoft.com/en-us/power-query/power-query-folding)
* Content Source: [powerquery-docs/power-query-folding.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/power-query-folding.md)
* Service: **powerquery**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by DougKlopfenstein** [comment]
Hi @kurtwz 

The text has been fixed.
