### ISSUE TITLE
Provide example codeblock of OAuth2 flow for this section

### ISSUE THREAD

**Issue by geologyrocks** [MicrosoftDocs/powerquery-docs#63]
I strongly believe that you should include an example code block demonstrating OAuth 2 auth flow, and a working refresh token.  This is the code I am using after digging around in the internet, eventually finding this post, which is the only working code block I've found! https://github.com/microsoft/DataConnectors/issues/280 

If you agree that this would be useful to include, and as it took me 1 day+ of searching I assure you it is useful, then I would be happy to help pare down this code block to the essentials should you want assistance doing so :)

Best wishes,

Ed HP

```
// Data Source Kind description
ManagementInformationConnector = [
    TestConnection = (redirect_uri) => { ManagementInformationConnector.Contents(azureEnvironment, "jobs") },
    Authentication = [
        OAuth = [
            StartLogin = StartLogin,
            FinishLogin = FinishLogin,
            Refresh = Refresh
        ]
    ],
    Label = Extension.LoadString("DataSourceLabel")
];

StartLogin = (resourceUrl, state, display) =>
    let
        codeVerifier = Text.NewGuid() & Text.NewGuid(),
        authorizeUrl = "https://login.microsoftonline.com/" & environmentVariables[AzureTenantId]{0} & "/oauth2/authorize?" & Uri.BuildQueryString([
            client_id = environmentVariables[AzureClientId],
            resource = environmentVariables[AzureResource],
            response_type = "code",
            response_mode = "query",
            redirect_uri = redirect_uri,
            code_challenge_method = "plain",
            code_challenge = codeVerifier,
            state = state,
            login = "login"
        ])
    in
        [
            LoginUri = authorizeUrl,
            CallbackUri = redirect_uri,
            WindowHeight = windowHeight,
            WindowWidth = windowWidth,
            Context = codeVerifier
        ];

FinishLogin = (context, callbackUri, state) =>
    let
        parts = Uri.Parts(callbackUri)[Query],
        result = if (Record.HasFields(parts, {"error", "error_description"})) then 
                    error Error.Record(parts[error], parts[error_description], parts)
                 else
                    TokenMethod(parts[code], "authorization_code", context) // code is the authorization code itself
    in
        result;

Refresh = (resourceUrl, refresh_token) => TokenMethod(refresh_token, "refresh_token");

TokenMethod = (authCode, grant_type, optional verifier) =>
    let
        codeVerifier = if (verifier <> null) then [code_verifier = verifier] else [],
        codeParameter = if (grant_type = "authorization_code") then [ code = authCode ] else [ refresh_token = authCode ],
        query = codeVerifier & codeParameter & [
            client_id = environmentVariables[AzureClientId],
            client_secret = environmentVariables[ApiManagementClientSecret],
            grant_type = grant_type,
            redirect_uri = redirect_uri
        ],

            tokenResponse = Web.Contents("https://login.microsoftonline.com/" & environmentVariables[AzureTenantId]{0} & "/oauth2/token",
            [
            Content = Text.ToBinary(Uri.BuildQueryString(query)),
            Headers = [
                #"Content-type" = "application/x-www-form-urlencoded",
                #"Accept" = "application/json"
            ]
            ]),
        parts = Json.Document(tokenResponse)
    in
        // check for error in response
        if (parts[error]? <> null) then 
            error Error.Record(parts[error], parts[message]?)
        else
            parts;
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58e66f41-e084-8f8a-8828-12474f21f0d7
* Version Independent ID: 77eafe80-5569-eee6-042e-e425a9056570
* Content: [Handling authentication for Power Query connectors](https://docs.microsoft.com/en-us/power-query/handlingauthentication)
* Content Source: [powerquery-docs/HandlingAuthentication.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/HandlingAuthentication.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by geologyrocks** [comment]
@mattmasson or someone else from MS, what are your thoughts on this?

**Comment by spencerhuang** [comment]
@mattmasson and @geologyrocks 
Hi all, this ticket has been around for about 1 year and no movement. My question is that this code block is meant for OAuth 2 Authorization Grant Flow's PKCE flow. The reason for doing PKCE in the first place is that you don't want to expose client_secret inside Power Query (M Query) code. In other words, in above code block, 
`        query = codeVerifier & codeParameter & [
            client_id = environmentVariables[AzureClientId],
            client_secret = environmentVariables[ApiManagementClientSecret],
            grant_type = grant_type,
            redirect_uri = redirect_uri
        ]`
I don't see why you would want client_secret to be there. If you are going to use client_secret, then you should not use code challenge and/or code verifier.

**Comment by ptyx507x** [comment]
Hey @spencerhuang and @geologyrocks 

Apologies for the late reply on this. My name is Miguel Escobar. I recently joined as a Product Manager for the Power Query team and I'm going through the issues that we have in our repo.

At the current moment the only public facing documentation that we have is for OAuth 2.0 is the one below:
https://docs.microsoft.com/en-us/power-query/samples/github/readme

Nevertheless, we do have plans to add more content and samples related to OAuth 2.0 and PKCE being one of those.

Thanks for your feedback and, again, my apologies for the lateness
