### ISSUE TITLE
Learn more hyperlink not there

### ISSUE THREAD

**Issue by ra67052** [MicrosoftDocs/powerquery-docs#64]
This bullet point DirectQuery (Power BI only, **learn more**) has a missing hyperlink to to learn more

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f05c74-8262-6610-bd9e-efe4f112bbe1
* Version Independent ID: 09570cd3-3a8b-18c6-da4c-46beada3a387
* Content: [Power Query PostgreSQL connector](https://docs.microsoft.com/en-us/power-query/connectors/postgresql)
* Content Source: [powerquery-docs/Connectors/PostgreSQL.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/PostgreSQL.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @ra67052 -

For consistency with other connector articles, the "learn more" text has been removed.
