### ISSUE TITLE
Typesetting issue?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/powerquery-docs#65]
| No. | Description | |---------|-------------| | 1 | On the ribbon, many buttons are now active so you can interact with the data in the query. | | 2 | In the Queries pane, queries are listed and available for selection, viewing, and shaping. | | 3 | In the center pane, data from the selected query is displayed and available for shaping. | | 4 | In the Query Settings pane, the properties and applied steps for the selected query are listed. |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea0d834-cf02-7769-9bc1-e71f53d34743
* Version Independent ID: b3ba5a41-079b-7c65-8fb9-c1a956a46f4a
* Content: [Quickstart - using Power Query in Power BI](https://docs.microsoft.com/en-us/power-query/power-query-quickstart-using-power-bi)
* Content Source: [powerquery-docs/power-query-quickstart-using-power-bi.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/power-query-quickstart-using-power-bi.md)
* Service: **powerquery**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by DougKlopfenstein** [comment]
Hi @hwkwicre -

This article has been completely rewritten and no longer contains this table.
