### ISSUE TITLE
Update Instructions and Screenshots

### ISSUE THREAD

**Issue by DaxelCA** [MicrosoftDocs/powerquery-docs#66]
Hi.

Menu ribbons were updated in 2020.
Edit Queries button is now entitled Transform Data
> Text and screenshots should be updated accordingly.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea0d834-cf02-7769-9bc1-e71f53d34743
* Version Independent ID: b3ba5a41-079b-7c65-8fb9-c1a956a46f4a
* Content: [Quickstart - using Power Query in Power BI](https://docs.microsoft.com/en-us/power-query/power-query-quickstart-using-power-bi)
* Content Source: [powerquery-docs/power-query-quickstart-using-power-bi.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/power-query-quickstart-using-power-bi.md)
* Service: **powerquery**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by DougKlopfenstein** [comment]
Hi @DaxelCA 

This article has been updated and completely rewritten.
