### ISSUE TITLE
Convert To Parameter

### ISSUE THREAD

**Issue by giucon** [MicrosoftDocs/powerquery-docs#67]
[Please specify in what situations the "Convert To Parameter" in the query context menu is greyed out.
I am using latest Microsoft 365 release. It remains greyed out for single values and lists.
Thank you.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ae586a-2f62-ad6d-2ced-953908abe66e
* Version Independent ID: f4def8d1-85cd-1bed-2771-ed81cf8eeb78
* Content: [Parameters](https://docs.microsoft.com/en-us/power-query/power-query-query-parameters#creating-a-parameter)
* Content Source: [powerquery-docs/power-query-query-parameters.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/power-query-query-parameters.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **v-miesco**

**Comment by ptyx507** [comment]
Thanks for the feedback. We've updated the content to be more specific as to what type of queries can be converted into a parameter. This section addresses such scenarios:

> You can easily right-click a query whose value is a simple **non-structured constant** such as, but not limited to, a date, text, or number, and select Convert to Parameter.

Please keep the feedback coming and let us know if there's anything else that we could do to improve the content.
