### ISSUE TITLE
Image shows full outer join instead of inner join

### ISSUE THREAD

**Issue by naomistuart** [MicrosoftDocs/powerquery-docs#68]
The top image shows a full outer join, instead of an inner join.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 123ac609-3092-d713-ec4b-299dad23310d
* Version Independent ID: 42bc7a48-4e9f-6dd5-8c40-d727b328a18f
* Content: [Inner join](https://docs.microsoft.com/en-us/power-query/merge-queries-inner)
* Content Source: [powerquery-docs/merge-queries-inner.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/merge-queries-inner.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **v-miesco**

**Comment by ptyx507** [comment]
Thank you for reporting this! We've recently pushed an update to the article to address this issue.
Please keep the feedback coming and let us know if there's anything else that we could do to improve the content.
