### ISSUE TITLE
Porting Issue from the previous version of this page

### ISSUE THREAD

**Issue by normesta** [MicrosoftDocs/powerquery-docs#7]
Porting this issue from an open issue on the previous version of this page: The comments are these:
"Add the following content.
Title: Restrictions and workarounds for access by external users
Body: Access by external users must be in the form "UserA_A.onmicrosoft.com#EXT#@B.onmicrosoft.com"."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de89bef7-dbd7-c901-d329-f9838f8dbaf9
* Version Independent ID: 583cc4ae-3fdb-0d6c-6314-8aaf8e51e922
* Content: [Analyze data in Azure Data Lake Storage Gen2 by using Power BI](https://docs.microsoft.com/en-us/power-query/connectors/datalakestorage#feedback)
* Content Source: [powerquery-docs/Connectors/DataLakeStorage.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/DataLakeStorage.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by normesta** [comment]
This issue is carried over. It was posted by @YoshitakaTakada form issue [45835](https://github.com/MicrosoftDocs/azure-docs/issues/45835)

**Comment by DougKlopfenstein** [comment]
Could you supply more context on what this is referring to? 

What specifically is an "external" user? 

Is the "form" referring to the URL of the user's Azure Data Lake Storage Gen2 account? If so, what parts of the example URL are changed by the user and what parts are not? Should the example URL look like this:

_UserA_A.onmicrosoft.com_#EXT#@_B.onmicrosoft.com_

Can "onmicrosoft.com" be replaced with "contoso.com", or is that address required?

**Comment by DougKlopfenstein** [comment]
Hi @normesta  - this issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
