### ISSUE TITLE
I don't see FHIR in power bi desktop

### ISSUE THREAD

**Issue by jabeenstudy** [MicrosoftDocs/powerquery-docs#70]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b0f303d-3edf-ac97-0874-89b24dd73053
* Version Independent ID: 3f25ae3a-4d94-58f6-6887-00dfbfb020cb
* Content: [Power Query connector for FHIR](https://docs.microsoft.com/en-us/power-query/connectors/fhir/fhir#feedback)
* Content Source: [powerquery-docs/Connectors/FHIR/FHIR.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/FHIR/FHIR.md)
* Service: **powerquery**
* GitHub Login: @hansenms
* Microsoft Alias: **mihansen**

**Comment by DougKlopfenstein** [comment]
Hi @jabeenstudy - this issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
