### ISSUE TITLE
Additional details for connecting to Access 2016 file format and using a Gateway

### ISSUE THREAD

**Issue by DavidPeraza** [MicrosoftDocs/powerquery-docs#72]
Hello,

Got feedback from two different CRIs:

1) Access databases with bigInt support enabled get stamped to Access 2016 file format. If the user has Office 365 installed then there shouldn't be a problem. However, if they have the Access database engine 2010 installed, connecting to the Access db from PBI Desktop will fail with something like "the file you are trying to connect to requires a newer version of Access". This error will happen when (only when connecting to a file with bigInt support enabled):
- Office 365 is installed AND Access db engine 2010 is installed
- Only Access db engine 2010 is installed.

If both O365 and the 2010 engine are installed, the fix is to uninstall the 2010 engine and do a quick repair of Office (from control panel) to fix the registry.

2) When trying to use a Gateway (standard mode) to connect to an Access file stored in a shared folder, it is important that the impersonated user account has full permissions to a Temp folder owned by the Gateway service account (located in the Gateway machine). The folder path should be something like C:\\Users\\PBIEgwService\\AppData\\Local\\Temp. If the impersonated user account does not have access to this folder, refresh via the Gateway should fail with an error similar to 'Unspecified error DataFormat.Error'.

I'm happy to provide more details on this.
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53cc4f3b-fa10-fb57-5146-b321c016349c
* Version Independent ID: 117f1d37-f83f-6696-eb19-13088b464511
* Content: [Power Query Access database connector](https://docs.microsoft.com/en-us/power-query/connectors/accessdatabase)
* Content Source: [powerquery-docs/Connectors/AccessDatabase.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/AccessDatabase.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **v-douklo**

**Comment by JasonWHowell** [comment]
@DavidPeraza  Sorry we haven't gotten around to fixing this issue yet. We're behind.

If you have any time, and are willing, you can help us edit the doc at this URL in the open source repo:
https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/AccessDatabase.md

Thanks, Jason
#please-open

**Comment by DougKlopfenstein** [comment]
@DavidPeraza 
I am closing this issue because it has become stale since the Access connector no longer uses the 2010 provider but instead uses the [Access Database Engine 2016 OLEDB provider](https://www.microsoft.com/download/details.aspx?id=54920). If the problem still persists using the 2016 provider, you can reopen this issue.
