### ISSUE TITLE
Incorrect steps at 8 & 9

### ISSUE THREAD

**Issue by jcbendernh** [MicrosoftDocs/powerquery-docs#77]
The documentation you are providing causes the datasource to be read as a local data source and will not refresh via the Power BI web service.  Instead of choosing binary, the user should select the combine files button on the Content header.  This allows the dataset to be refreshed on the web service without the use of a local data gateway.

Happy to walk you though this issue as I am a Microsoft employee.  My alias is jobender.

Sincerely,

Jack Bender | Cloud Solution Architect | Azure Data & AI 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de89bef7-dbd7-c901-d329-f9838f8dbaf9
* Version Independent ID: 583cc4ae-3fdb-0d6c-6314-8aaf8e51e922
* Content: [Analyze data in Azure Data Lake Storage Gen2 by using Power BI](https://docs.microsoft.com/en-us/power-query/connectors/datalakestorage)
* Content Source: [powerquery-docs/Connectors/DataLakeStorage.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/DataLakeStorage.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by albertoRamon** [comment]
Jack is Correct, 
[link](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-combine-binaries#combine-files-behavior)

And in the point 8 (the name of the button is not correct)

**Comment by JasonWHowell** [comment]
@jcbendernh @albertoRamon 
Sorry we haven't gotten around to fixing this issue yet. We're behind. 

If you have any time, and are willing, you can help us edit the doc at this URL: 
https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/DataLakeStorage.md

Thanks, Jason 
#please-open
