### ISSUE TITLE
Documentation suggests this is OOB already, but it doesn't appear to be.

### ISSUE THREAD

**Issue by JamieChicago** [MicrosoftDocs/powerquery-docs#78]
[Enter feedback here]
I am using December 2020 PBI Desktop. Fuzzy Grouping does not appear to be an OOB option and there is no indication of that in this article. In order to perform Fuzzy Grouping on my system I had to group first, then open the advanced editor and modify the code.

--- 
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11ad4d0-a7ce-8e2a-115b-b343ca789a93
* Version Independent ID: 05e7d736-b6ef-86bd-8101-eafc02d474b6
* Content: [Grouping or summarizing rows](https://docs.microsoft.com/en-us/power-query/group-by#fuzzy-grouping)
* Content Source: [powerquery-docs/group-by.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/group-by.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **v-miesco**

**Comment by ptyx507** [comment]
Thanks for the feedback! We've added a small note to this section of the article that mentions that the Fuzzy group is currently only available in Power Query Online.

Thanks again!
