### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerquery-docs#80]
Excellent information. A minor typo in [this section](https://docs.microsoft.com/en-us/power-query/dataflows/best-practices-developing-complex-dataflows#split-data-transformation-t-and-stagingextraction-e-dataflows).. I think the author may have wanted to say (_staging_ dataflow) and not (_stating_ dataflows)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76bbffdf-18f6-9001-b75a-57aedc1dcfe0
* Version Independent ID: 928761e0-8e55-c01f-9228-7ee5d2971d52
* Content: [Best practices around designing and developing complex dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/best-practices-developing-complex-dataflows)
* Content Source: [powerquery-docs/dataflows/best-practices-developing-complex-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/dataflows/best-practices-developing-complex-dataflows.md)
* Service: **powerquery**
* GitHub Login: @radacad
* Microsoft Alias: **v-douklo**

**Comment by DougKlopfenstein** [comment]
Hi @pawarbi -

Thanks for your feedback. This typo is fixed.
