### ISSUE TITLE
Fuzzy grouping

### ISSUE THREAD

**Issue by stevewrt** [MicrosoftDocs/powerquery-docs#81]
I thought that this and the clustering option were included in the December 2020 release, but I can't find them.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11ad4d0-a7ce-8e2a-115b-b343ca789a93
* Version Independent ID: 05e7d736-b6ef-86bd-8101-eafc02d474b6
* Content: [Grouping or summarizing rows](https://docs.microsoft.com/en-us/power-query/group-by#fuzzy-grouping)
* Content Source: [powerquery-docs/group-by.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/group-by.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **v-miesco**

**Comment by ptyx507** [comment]
Thank you for your feedback, @stevewrt !

This functionality is currently only available in the Power Query Online experience as mentioned in the note at the start of this section in the article. You can find this experience in Power BI and the Power Platform Dataflows.

Thanks again for your feebdack and please keep the feedback coming!
