### ISSUE TITLE
Cannot find template

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerquery-docs#82]
![image](https://user-images.githubusercontent.com/12585652/102923300-e3d98080-4465-11eb-856a-428812fe7b26.png)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53048912-9c2a-1cae-4e9a-02cf79307e3c
* Version Independent ID: d21f1dab-c67e-2100-f11a-82d3ba6fda9b
* Content: [Trigger Dataflows and Power BI Datasets sequentially](https://docs.microsoft.com/en-us/power-query/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially)
* Content Source: [powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/dataflows/trigger-dataflows-and-power-bi-dataset-sequentially.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @asocorro -
Thanks for your feedback. The documentation has been fixed and updated.
