### ISSUE TITLE
Need updated instructions; UI is no longer the same as in the screenshots.

### ISSUE THREAD

**Issue by FelixMycinian** [MicrosoftDocs/powerquery-docs#85]
Screenshot doesn't match what I see in PowerBI.  There's no "Edit Queries" button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea0d834-cf02-7769-9bc1-e71f53d34743
* Version Independent ID: b3ba5a41-079b-7c65-8fb9-c1a956a46f4a
* Content: [Quickstart - using Power Query in Power BI](https://docs.microsoft.com/en-us/power-query/power-query-quickstart-using-power-bi)
* Content Source: [powerquery-docs/power-query-quickstart-using-power-bi.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/power-query-quickstart-using-power-bi.md)
* Service: **powerquery**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by DougKlopfenstein** [comment]
Hi @FelixMycinian -

Thanks for your feedback. This article has been completely rewritten from the ground up with up-to-date screenshots.
