### ISSUE TITLE
Date Clarification > Salesforce Objects Connector Documentation > Troubleshooting Section

### ISSUE THREAD

**Issue by jkadilak** [MicrosoftDocs/powerquery-docs#86]
Under the Troubleshooting section of the page there is a reference to Enabling OAuth Authentication in Power BI Desktop "Starting in December 2021". Should that be "December 2020", or is the availability really delayed until December 2021? 

"Enabling OAuth Authentication in Power BI Desktop

Starting in **December 2021** Power BI Desktop:

-Install the new Edge Chromium browser, (at least beta) from https://www.microsoftedgeinsider.com/download.
-In your Environment Variables, set the System variable PQ_EnableEdgeChromiumOAuth to true . Once that is set it will use Edge Chromium for only QuickBooksOnline. For this release, only QuickBooksOnline is enabled by default.
-To set it for Salesforce, in System Environment Variables set PQ_ExtendEdgeChromiumOAuthAllowList to Salesforce"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c78a664-32c4-68c5-97ec-99d5fa4e5aab
* Version Independent ID: 75152c2f-8bed-c5df-5fa3-2470920f6dde
* Content: [Power Query Salesforce Objects connector](https://docs.microsoft.com/en-us/power-query/connectors/salesforceobjects)
* Content Source: [powerquery-docs/Connectors/SalesforceObjects.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/SalesforceObjects.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @jkadilak -

The documentation has been corrected to December 2020.
