### ISSUE TITLE
Excel, Power Query Sharepoint Folder connector 

### ISSUE THREAD

**Issue by MDHutch** [MicrosoftDocs/powerquery-docs#88]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7fa007-53f0-1fa5-bbff-b59fe142c804
* Version Independent ID: acb9ddd9-08ea-79ea-3537-cf8bda64282b
* Content: [Power Query SharePoint Folder connector](https://docs.microsoft.com/en-us/power-query/connectors/sharepointfolder)
* Content Source: [powerquery-docs/Connectors/SharePointFolder.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/SharePointFolder.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @MDHutch -

This issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
