### ISSUE TITLE
Date Error?  Salesforce connector

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerquery-docs#89]
On the following site: https://docs.microsoft.com/en-us/power-query/connectors/salesforceobjects

In the enabling OAuth section (https://docs.microsoft.com/en-us/power-query/connectors/salesforceobjects#enabling-oauth-authentication-in-power-bi-desktop)

We use the date December 2021.   Is this supposed to read December 2020?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c78a664-32c4-68c5-97ec-99d5fa4e5aab
* Version Independent ID: 75152c2f-8bed-c5df-5fa3-2470920f6dde
* Content: [Power Query Salesforce Objects connector](https://docs.microsoft.com/en-us/power-query/connectors/salesforceobjects)
* Content Source: [powerquery-docs/Connectors/SalesforceObjects.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/SalesforceObjects.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @rosscouldrey -

This date in the documentation has been corrected to 2020.
