### ISSUE TITLE
TestConnection = (dataSourcePath)

### ISSUE THREAD

**Issue by zebrassimo** [MicrosoftDocs/powerquery-docs#9]
It took quite a while to identify this line missing from my code after endless tries to get a custom connector to work. It turned out that the visual studio 2019 (Version 15.9.15) code template when setting up the project misses this. Maybe you should add it.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: cbc2464b-1d4c-3fe7-1375-c95b791fe312
* Version Independent ID: 5f142ea5-c08a-eb02-de68-41dccdefb141
* Content: [Gateway Support for Power Query connectors](https://docs.microsoft.com/de-de/power-query/handlinggatewaysupport)
* Content Source: [powerquery-docs/HandlingGatewaySupport.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/HandlingGatewaySupport.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @zebrassimo -

This seems to be product feedback or a request for product support. To see where to direct these kinds of queries, see [Power Query feedback](https://docs.microsoft.com/en-us/power-query/feedback).
