### ISSUE TITLE
Docs Request: BigQuery Data Connector

### ISSUE THREAD

**Issue by sgoley** [MicrosoftDocs/powerquery-docs#90]
This is now released in PowerBI Desktop but does not yet have a docs page!

M function:
`GoogleBigQuery.Database()`

Optional Parameters:
`[BillingProject="my-billing-project-id"]`

![image](https://user-images.githubusercontent.com/10283176/108426463-cb89a600-7209-11eb-9f54-68d23113b4d9.png)

Request:
Please create a new docs page for this connector with all valid M function parameters, api limits, etc. 

Link to powerbi specific docs:
https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-bigquery.md

**Comment by DougKlopfenstein** [comment]
Hi @sgoley -

The new [Power Query Google BigQuery connector page](https://docs.microsoft.com/power-query/connectors/googlebigquery) has been published.
