### ISSUE TITLE
DataSource.Error: FHIR connector getting error while data transformation : "The downloaded data is HTML, which isn't the expected type."

### ISSUE THREAD

**Issue by ronyv** [MicrosoftDocs/powerquery-docs#91]
I was just exploring the Microsoft FHIR power query connector. I was able to do it successfully with the AZURE FHIR service with data loaded from Synthea Bundles. Everything went well here and after successful data transformation, i was able to visualize data through power bi.

Now i've implemented my own fhir server using the open source hapi fhir project and loaded the same synthea data. I've connected my power bi to this new server using the power query connector. But while transforming data i am seeing an entire last row with "Error" . On clicking the error, it just says the following.

> DataSource.Error: The downloaded data is HTML, which isn't the expected type. The URL may be wrong or you might not have provided the right credentials to the server.

Had anyone faced the issue of same kind ? The error message says its an issue with the data, but the data is generated and loaded from Synthea and cant be wrong. I've even verified the data manually using Postman and made sure that everything comes from my fhir server is in JSON format only.

I am clueless on why this error is happening as the same data was working fine with the Azure FHIR service. Any help on this will be greatly appreciated!

![image](https://user-images.githubusercontent.com/15177814/108697120-7068f380-7528-11eb-9409-c98f2d1bd0ca.png)

![image](https://user-images.githubusercontent.com/15177814/108697236-98585700-7528-11eb-89ec-4cde4291e324.png)
 

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b0f303d-3edf-ac97-0874-89b24dd73053
* Version Independent ID: 3f25ae3a-4d94-58f6-6887-00dfbfb020cb
* Content: [Power Query connector for FHIR](https://docs.microsoft.com/en-us/power-query/connectors/fhir/fhir)
* Content Source: [powerquery-docs/Connectors/FHIR/FHIR.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/FHIR/FHIR.md)
* Service: **powerquery**
* GitHub Login: @hansenms
* Microsoft Alias: **mihansen**

**Comment by DougKlopfenstein** [comment]
Hi @ronyv -

This is a connector support issue rather than a documentation issue. For information about how to get support for Power Query connectors, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
