### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerquery-docs#94]
It's mention here that custom connectors are only supported in Power BI Desktop - https://docs.microsoft.com/en-us/power-query/startingtodevelopcustomconnectors

This is no longer true and they are now supported by the gateway as well. Please update documentation to reflect this change.

**Comment by DougKlopfenstein** [comment]
Hi @haider392 -
Thanks for your feedback. This issue has been fixed.
