### ISSUE TITLE
Test Connection - Personal Gateway Error.

### ISSUE THREAD

**Issue by marthiniusj** [MicrosoftDocs/powerquery-docs#95]
Hellos.

I've followed the steps listed here.

https://docs.microsoft.com/en-us/power-query/samples/trippin/9-testconnection/readme

I always end up with the same error.

Unable to determine the data source due to unknown functions. When custom connectors are used, the error can happen if gateway doesn't have the extension enabled. Details: Query contains unknown function name: TripPin.Contents.
Data source for Query1

Any advice on what I'm doing wrong?

See the screenshots below.

Kind regards,
Thinus

![Capture3](https://user-images.githubusercontent.com/79978614/109802241-3c788700-7c28-11eb-9929-e41e0a12bce1.PNG)
![Capture2](https://user-images.githubusercontent.com/79978614/109802154-24086c80-7c28-11eb-9209-38ff85349d46.PNG)
![Capture](https://user-images.githubusercontent.com/79978614/109802014-ed325680-7c27-11eb-81b8-d0a751ba7541.PNG)

**Comment by ptyx507x** [comment]
Hey @marthiniusj!

My apologies for the delay on this response. My name is Miguel Escobar. I recently joined the Power Query product team as a Product Manager.

I'm following up now and, again, apologies for the lateness. Were you able to resolve this scenario? You should be able to click the "Discover Data Sources" link to trigger the scan of the custom connectors in your gateway.

**Comment by JasonWHowell** [comment]
@marthiniusj we haven't heard back lately. Please check the thread when you have a chance. 

I'm resolving this issue for now, but if you need continued assistance, please let us know. Thanks, Jason

**Comment by JasonWHowell** [comment]
#please-close

**Comment by ivargj** [comment]
Hi! I'm having the exact same issue, and would appreciate some assistance on the matter. 
My gateway (personal mode) reports no problems, reports it's ready to be used, and the trip pin data connector shows up in the list. I get the same error as reported here: "Query contains unknown function name: TripPin.Contents" 

When I go to Settings -> Manage Gateways on app.powerbi.com, I see the data gateway listed, reporting status Online (see screenshot) 
![image](https://user-images.githubusercontent.com/17049481/195344839-c931059e-ee54-41fa-a2fd-4f8cabcee41d.png) 

However there is nothing listed under data sources, and I am not able to pick any gateway clusters when entering New Data Source. Am I supposed to see anything here? 

Thanks in advance for any help on this matter! 

Ivar

**Comment by ptyx507x** [comment]
@ivargj hey! Could you please share a link of what version of the TripPin connector you’re using? Some versions do not have the TestConnection implemented (this is only added in Part 9), so those versions will have the issue of not being discoverable on the refresh settings page for a dataset.

**Comment by ivargj** [comment]
> 

Hi @ptyx507x , thanks for replying! 

I am not quite sure what version you're referring to, but I've followed the TripPin walkthrough from the start until [part 9](https://learn.microsoft.com/en-us/power-query/samples/trippin/9-testconnection/readme). 
Using the service url of `https://services.odata.org/v4/TripPinService/` 

The data source description is as follows. 
`
TripPin = [
    TestConnection = (dataSourcePath) => { "TripPin.Contents" },
    Authentication = [
        Anonymous = []
    ],
    Label = "TripPin Part 9 - TestConnection"
];
`

**Comment by ptyx507x** [comment]
@ivargj is your gateway setup correctly and has the same version of the connector that you’re using for that pbix ?

if you have, and you’re still not seeing the data source, then please reach out to the Power BI support team so they can help you troubleshoot the issue.

I’m currently unable to repro this issue on my end with that version of the TripPin connector and with the latest personal gateway on my machine.

**Comment by ivargj** [comment]
As far as I know the gateway is setup correctly. It shows the TripPin under Connectors, and reports status as connected and ready to use. Gateway version: 3000.142.14. 
Under Settings -> Manage gateways -> On-premises data gateways, it reports status as Online. That being said, I can't seem to provoke any other status. It still reports Online even if I close the data gateway window, or when it is not logged in. 

How can I verify that the versions are the same? This is all I see in the connectors list: 
![image](https://user-images.githubusercontent.com/17049481/195603671-ceaaf20e-ce29-496a-87dc-73787c3fe0c3.png)

**Comment by marthiniusj** [comment]
Hi, Ivargj.

My errors all went away the moment I bought a Power BI Pro license. So I just assumed I got the errors because of the free license.

Out of curiosity, are you using a free license, or a pro/premium license?

**Comment by ivargj** [comment]
> Out of curiosity, are you using a free license, or a pro/premium license?

Hi @marthiniusj, I'm using the Pro license. 

By the way, is it supposed to show up automatically as a data source under Settings -> Manage gateways? Or do you have to add it?

**Comment by marthiniusj** [comment]
ok cool.

I tested now.

When I sign in to the gateway application, it prompts me to configure the gateway. Right after the configuration, I see this screen, saying the gateway is online and ready to be used.

![image](https://user-images.githubusercontent.com/79978614/195619705-23adea3a-3bb8-43cc-a322-1af3ba7577e6.png)

And then the gateway automatically appears in power bi online gateway screen.

![image](https://user-images.githubusercontent.com/79978614/195619952-5209e505-7670-4c01-90ac-fd09e546440e.png)

Another thing it tried while trying to figure all this out, was to move the location of my connectors directory, for example, to C:\Connectors.

![image](https://user-images.githubusercontent.com/79978614/195620301-77a5b05b-e502-4578-b0d5-aeb51764b8b0.png)

And I also made sure that this folder had the PBIEgwService user assigned with full access.

![image](https://user-images.githubusercontent.com/79978614/195620732-b247db80-9098-40d4-bbee-831b7f6a7e28.png)

I really don't know how it started working.

**Comment by ivargj** [comment]
@marthiniusj , thanks for sharing! 
One difference between our setups is I'm using the personal mode gateway. I have the same status as yours has in your original post. Did you get it working with the personal mode gateway? I could maybe try with the other one as well. 

Also I can't seem to find the same user as you added to the access permissions. How did you find the right one to add? 
I tried giving full control to all users, same result as before.

**Comment by marthiniusj** [comment]
Yeah, I tried the personal gateway, but it didn't work for me. So since then, I always download the standard mode one, and it's been working great so far.

Hmm I'm guessing the PBIEgwService user only gets created when you install the standard mode gateway.

Try the standard mode gateway, hopefully that sorts out the problem.

**Comment by ivargj** [comment]
So for the record, the standard mode worked for me. So it seems to be problems with the personal mode gateway. I also managed to make it pick up the connector from the correct folder by adding permissions for the PBIEgwService. :)

**Comment by brandonstubbs** [comment]
I just ran into the same problem. Can confirm [installing the standard gateway](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-install#download-and-install-a-standard-gateway) works
