### ISSUE TITLE
How can I see partition status

### ISSUE THREAD

**Issue by lbendlin** [MicrosoftDocs/powerquery-docs#96]
Being able to set up incremental refresh is very nice, but how do I validate that it is actually working?  For datasets I can monitor the partition refresh statistics.  How can I do the same for dataflows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffc816e2-78f6-ca70-92a3-b2153461759d
* Version Independent ID: e6fec9a8-1c47-b739-5146-0fa717c4535e
* Content: [Using incremental refresh with dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/incremental-refresh)
* Content Source: [powerquery-docs/dataflows/incremental-refresh.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/dataflows/incremental-refresh.md)
* Service: **dataflows**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Thanks @lbendlin for your dedication to our documentation. Unfortunately, we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We have added information about monitoring dataflow refreshes at the following location in the Power Query docs - [Monitor your dataflow refreshes with Power BI](https://learn.microsoft.com/power-query/dataflows/monitor-dataflow-refreshes).

**Comment by lbendlin** [comment]
That is rather pointless. We need this for Power BI, not CDS/Dataverse.

**Comment by Luitwieler** [comment]
Expect that over time we introduce incremental refresh in Dataflows Gen2 with a better and detailed refresh diagnostics. If you download the CSV file for dataflow gen1 refreshes to look into the partitions that got refreshed.

**Comment by lbendlin** [comment]
Will we get the option to refresh individual partitions?On Feb 9, 2024 2:24 AM, Jeroen Luitwieler ***@***.***> wrote:
Expect that over time we introduce incremental refresh in Dataflows Gen2 with a better and detailed refresh diagnostics. If you download the CSV file for dataflow gen1 refreshes to look into the partitions that got refreshed.
