### ISSUE TITLE
TripPin Walkthrough Part 1 instructions incorrect.

### ISSUE THREAD

**Issue by PKCheap** [MicrosoftDocs/powerquery-docs#97]
"Loading Your Extension in Power BI Desktop" section incorrect. As of February 2021, the option for enabling custom connectors does not exist. Not sure if this means that it is just on by default now. Nevertheless, After creating the Documents directory "Power BI Desktop/Custom Connectors", and copying TripPin.mez, Power BI Desktop is not able to find the connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea5ab12-0b6e-20b5-1659-d872db778b6d
* Version Independent ID: d642b0fd-460c-c8aa-922a-28569d7cf986
* Content: [TripPin 1 - OData](https://docs.microsoft.com/en-us/power-query/samples/trippin/1-odata/readme)
* Content Source: [powerquery-docs/samples/TripPin/1-OData/README.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/samples/TripPin/1-OData/README.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by DougKlopfenstein** [comment]
Hi @PKCheap -
Thanks for your feedback. This has been fixed in the documentation.
